### ISSUE TITLE
Executable BPMN with SQL annotations

### ISSUE THREAD

**Issue by MGlauer** [openego/data_processing#1]
Given are BPMN diagrams with SQL Annotations. 

We need a tool that reads the BPMN from a [yEd](https://www.yworks.com/products/yed) xml-file (e.g. [here](https://github.com/openego/data_processing/files/226186/bpmn_examples_simple_data_processing.graphml.txt)) and executes it according to the [BPNM specification](http://www.omg.org/spec/BPMN/2.0/) .
Flow elements may be annotated by SQL statements or the name of a file that contains SQL statements. These statements should be executed in the corresponding steps of the execution on a Postgresql database.
![bpmn_examples_simple_data_processing](https://cloud.githubusercontent.com/assets/7835111/14644688/331b2820-0653-11e6-96f9-bff44e64cd06.png)

**Comment by prathamesh-pradhan** [comment]
Executed SQL annotation by annotating diagram with script file name.
