### ISSUE TITLE
Power plants in EHV level with wrong otg_id

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#100]
Power plants in EHV level are not assigned correctly to the corresponding substation. 
The subst_id seems to be correct, whereas the otg_id is corrupted. In case of EHV substations the otg_id seems to be assigned falsely at some point.

**Comment by IlkaCu** [comment]
The changes in branch feature/otg_id seem to fix this bug. @ulfmueller: Could you please test this by running the assignment_generator scripts?

**Comment by ulfmueller** [comment]
cool. locally or directly on the model_draft?

**Comment by ulfmueller** [comment]
The assignment scripts ran and I tested some samples which are positive. Thx @IlkaCu ! I will create a pull request for  the feature/otg_id to dev branch
