### ISSUE TITLE
change/check source other_non_renewable marginal costs

### ISSUE THREAD

**Issue by ulfmueller** [openego/data_processing#101]
up until now the marginal costs of other_non_renewable were set to 0 which does not make sense.
I changed the costs to the ones of oil with this commit: 52f9c0117bda24039186ec7b17962d7ee4c65a79. @wolfbunke If you have a better approach please tell us and change it right away. 
@ClaraBuettner please pull consider this also when setting the marginal costs for the 2050 scenario. I saw that this section is so far not included in your branch, [see here](https://github.com/openego/data_processing/blob/feature/future-scenarios/dataprocessing/sql_snippets/ego_dp_powerflow_lopf_data.sql#L15-L45)

**Comment by wolfbunke** [comment]
It is not very easy to make a "right" assumption. This units are mostly industrial plants which are fired with wast, oil, gas and industrial heat. I  suggest a low medium price like waste. 

I found a nice definition:
> **Fossile Energieträger**
>  In der erdgeschichtlichen Vergangenheit insbesondere aus abgestorbenen Pflanzen entstandene feste, flüssige und gasförmige Brennstoffe wie Kohle, Erdöl, Erdgas, Holz und **sonstige Energieträger** wie Sulfitablauge, Raffineriegas, Altreifen.  http://www.statistik-bw.de/Glossar/326 

I would

**Comment by ulfmueller** [comment]
Did you want to add anything more (because your sentence broke up accidentally)?

**Comment by wolfbunke** [comment]
Yes, the sentence got lost... 
During the scenario development @s3pp and me agreed on wast prices for mixed_fuels or other_non_renewable fuels. See: https://github.com/znes/FlEnS/tree/master/open_eGo/SQ

I will change the values now.

**Comment by wolfbunke** [comment]
let me see, i saw we have 15 sources but not all are different in the script or?

**Comment by wolfbunke** [comment]
ok, checked

**Comment by ulfmueller** [comment]
I dont understand what you checked. 
As I see it, you changed the values in the future scenario branch, [here](https://github.com/openego/data_processing/blob/feature/future-scenarios/dataprocessing/sql_snippets/ego_dp_powerflow_lopf_data.sql)
Therefore I close this issue now.

**Comment by wolfbunke** [comment]
If not a source was missing due to the future power plant list
