### ISSUE TITLE
 column/attribute name "metadata" collides with SQLA-reserved name

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#102]
In SQLAlchemy table definition `EgoScenarioLog` the attribute `metadata` is used. The attribute collides with auto-generated SQLA [MetaData instance](https://github.com/openego/ego.io/blob/a39e879710e48fe8ae2b79983bd6bf1df8b16dc5/egoio/db_tables/model_draft.py#L11).

As a workaround, I mapped the column name using [`meta_data`](https://github.com/openego/ego.io/blob/a39e879710e48fe8ae2b79983bd6bf1df8b16dc5/egoio/db_tables/model_draft.py#L2546), see no. 4 in the [wiki page](https://github.com/openego/ego.io/wiki/How-to-update-database-definitions).

To avoid this ugly workaround I propose to rename the table column `metadata` in _model_draft.ego_scenario_log_ (and accessing scripts) to `meta_data`.

See also: https://github.com/openego/ego.io/issues/21#issuecomment-307155866

**Comment by Ludee** [comment]
If there is a collision, we can rename the column. 
Instead of "meta_data" we can also just use "meta"!?
It has to be changed in some places of the eGoDP, so it will be a feature branch of dev?

**Comment by ulfmueller** [comment]
> Instead of "meta_data" we can also just use "meta"!?

I like meta_data but I do not really care how it is called. if there is no other collision 'meta' would be fine I guess.
> It has to be changed in some places of the eGoDP, so it will be a feature branch of dev?

yes. It sounds like an easy and fast adjustment? So you can quickly merge that feature branch back to dev.

**Comment by Ludee** [comment]
OK, I will change the column to "meta_data". That already used in SQLA and makes more sense.

**Comment by nesnoj** [comment]
thx
