### ISSUE TITLE
Check for best location to set storages

### ISSUE THREAD

**Issue by lukasol** [openego/data_processing#103]
Currently, extendable storages are defined in lopf_data.sql with regards to ego_grid_pf_hv_bus (so each bus gets a storage). Does it make more sense to assign these extendable storages only to hvmv substations? If yes, realize.

**Comment by ulfmueller** [comment]
both ways seem reasonable. I would prefer the answer 'yes'. That way storages are built were substations are which generally would be more realistic and at the same time the number of decision variables gets minimized (I am not sure if that is really a benefit).

**Comment by lukasol** [comment]
Me too.
Problem: the substation tables do not have scn_name and the bus tables do not distinguish the bus types.

**Comment by lukasol** [comment]
Problem solved if otg_id works fine. (Does it? #100)
Each hvmv_substation gets a battery storage, its bus_id is the otg_id. 

Storages need only to be set once in ego_dp_powerflow_lopf_data.sql for the two scenarios, definition for SH test scenario is then taken from this table. The new assignment for the SH test scenarios will only be in place after the next dp run.

As of now, extendable hydrogen storages are defined to buses with a technical potential.

See https://github.com/openego/data_processing/commit/8be69d8f03c88a44fb8435979f4de796d15a9486 for the implementation.

@IlkaCu could you please check if I can add a "DELETE FROM" query to model_draft.ego_grid_pf_hv_storage before the assignment in order to clean the table without deleting something unintended?

**Comment by lukasol** [comment]
> @IlkaCu could you please check if I can add a "DELETE FROM" query to model_draft.ego_grid_pf_hv_storage before the assignment in order to clean the table without deleting something unintended?

Has been discussed. There will be no delete query, since all tables referring to powerflow are deleted at the beginning of each dp run.

Changes have been implemented, checks for plausibility will be carried out once @ulfmueller has finished the run that shall validate #100

**Comment by lukasol** [comment]
will be validated in #95
