### ISSUE TITLE
Harmonize of scenario names 

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#104]
For the documentation and scripts I saw, that we are using different names for our scenario naming.

| res script          | dp hv powerflow          |       |  scenario input   |
|--------------------|--------------|-----|----------------------|
| ego-status-quo| Status Quo |...   |...                        |
|ego-nep-2035  | NEP 2035  |...   |B12035/B22035 |
|ego-100RES    | NEP 2050  |...   | ego-100-2050   |

**Comment by ulfmueller** [comment]
yeah, good point. in the SciGRID paper we used the notation: Status Quo - NEP 2035 - eGo100% .
In my mind, we can use the notation from the res scripts or from the hv powerflow!
Should we have a small poll here in order to vote for which notation we want to use in the dp?

Anyhow, the NEP 2050 naming is a bug. @ClaraBuettner Could you please change the name "NEP 2050" to 'ego-100RES' or sth. similar? Definitely no NEP should be part of that name.

**Comment by lukasol** [comment]
I am pro the SciGRID paper notation, but would leave the % sign since I expect trouble with that...

**Comment by ClaraBuettner** [comment]
Shall I change only the entrys in the scn_name column or the table names as well?

**Comment by ulfmueller** [comment]
table names as well! Since it hasn't been used so far so the tables only exist in the script and maybe for test reasons locally so it is still easy to change everything...

**Comment by ulfmueller** [comment]
I am also in favor with the SciGRID paper notation. We decided it there once and after all there are just names - and even more after all names in code. So the code notation would be:
- Status Quo
- NEP 2035
- eGo 100

Note, that there are blank spaces in the names. That could be a slight adjustment for the future to get rid of them. But within v03 I would not suggest to waste time on that.

if there are no objections, 
@ClaraBuettner could adapt everything concerning the powerflow scripts concerning the eGo100 scenario
@wolfbunke could adapt the naming within the rea scripts

@IlkaCu @gplssm @wolfbunke if you disagree, please state that today.

**Comment by wolfbunke** [comment]
ok, I will change the scenario names.

**Comment by IlkaCu** [comment]
I'm fine with the SciGRID paper notation!

**Comment by wolfbunke** [comment]
Scenario naming is changed to:
- Status Quo
- NEP 2035
- eGo 100

for renewable and conventional power plant table.

**Comment by wolfbunke** [comment]
I am ready with all changes. From my point this ticket can be closed.
