### ISSUE TITLE
Restructure RES and Rea for v3

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#105]
The new power plant table includes units of all scenarios in one table of renewable and one of conventional power plants. By using Views single power plant tables by scenario can integrated into the scripts like before as table.

**Comment by IlkaCu** [comment]
New table structure and naming is described in issue #114

**Comment by wolfbunke** [comment]
Done. Views are created in https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_dp_res_rea_by_scenario.sql#L1787-L1900 and https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_dp_conv_by_scenario.sql#L342-L415
