### ISSUE TITLE
Intensive week DP v0.3 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#108]
-  19 to 23.06 intensive week to finalize DP v0.3 

-  daily wrap-up webco at 10 o'clock

**Comment by lukasol** [comment]
As I said, I won't be in for the webco tomorrow.

**Comment by wolfbunke** [comment]
As fare as I can see the most task are done.

- change of scripts of res and rea of renewable power plants
- change of scenario naming
- change meta documentation to v1.3
- Removed res and conv  scripts from .../dataprocessing/sql_snippets/rea to preprocessing folder. My scripts are removed but I don't know if all rea scripts are parts of the Dataprocessing? @Ludee ?


- All new Geometries are in the column rea_geom_new the old ones are still in geom. I am not sure if an change / renaming is maybe needed -> rea_geom_new -> geom and geom -> geom_old ??? @IlkaCu @ulfmueller @lukasol ?

- For the scenario_log I already inserted v0.3.0 as version I hope that was right.

- Scrips of @s3pp are untouched those need to be checked

- Yesterday we figured out that after changing data or table structures the MView needs to be dropped and created again. A change of the MView data/structure is not possible as fare as I know. 

- The part to create the MViews per scenario can be found here 
 -  https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/rea/ego_dp_res_rea_by_scenario.sql#L1760-L1867
 -  https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/rea/ego_dp_conv_by_scenario.sql#L336-L403

- All in all the scripts needs about 8h to run
 
 Have a good day. Partly I can change or do things from Riga.

**Comment by Ludee** [comment]
4. Rea must be part of the data_processing because it uses TP, MVGD, LA, and LVGD! And by definition it has assumptions and therefore is not "just preparation"
6. Did you change it [here](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_structure_scenariolog.sql#L26-L40)?

**Comment by wolfbunke** [comment]
> Rea must be part of the data_processing because it uses TP, MVGD, LA, and LVGD! And by definition it has assumptions and therefore is not "just preparation"

ok, it was not really clear for me 

> Did you change it here?

No. Ok I wait until visioning is set

Thx @Ludee

**Comment by IlkaCu** [comment]
Required for v0.3: #76, #72, #111, #120, #147(Dingo), #114
Note necessarily required for v0.3/Later release: #18, #136, #129, #137

**Comment by IlkaCu** [comment]
New Deadline for the last adjustments in v0.3 is the 5th of July. 
Until then all issues required for v0.3 should be solved and closed. We will create a release branch and start the debugging then.

**Comment by gplssm** [comment]
During the week of intensive work on the data processing we created a bunch of new tables/mviews and changed some.
I was on the way to use `model_draft.ego_supply_res_powerplant_sq_mview` in Dingo. But, then I as find myself asking:  how to we create ORM table classes for newly generated tables and views? 
@openego/data_processing Do we use the script? And if yes, when do we generate these?

**Comment by IlkaCu** [comment]
Our deadline for the remaining adjustments concerning v 0.3 expired yesterday. 
There are some open issues left. If there are any left which need to be solved before we start the new DP run, please let me know until tomorrow. Otherwise I will start the run tomorrow.

**Comment by wolfbunke** [comment]
From my side everything should be ok.

**Comment by Ludee** [comment]
Schema renaming #142 and data types #72 are in progress.
Will be completed and merged today.

**Comment by IlkaCu** [comment]
We will create the release branch on Monday and start the DP run (providing that all adjustments on the oedb are completed by then). 
If there are any changes or problems which affect the DP run, please let me know.

**Comment by IlkaCu** [comment]
The pull requests #147 and #148 are still pending. 
@Ludee: These are necessary for release v0.3, aren't they?

**Comment by IlkaCu** [comment]
Are there any other issues which we need to resolve before creating the release branch and start debugging the DP? 
Providing that the open pull requests are processes by then, I will create the release branch after the lunch break. If you have any concerns please let me know!

**Comment by MGlauer** [comment]
Remember to set the new database URL ;)

Am 10.07.2017 11:03 schrieb "IlkaCu" <notifications@github.com>:

**Comment by IlkaCu** [comment]
I created the branch release/v0.3

**Comment by IlkaCu** [comment]
I couldn't start the DP run due to problems with the oedb connection. We will try to solve this tomorrow.

**Comment by IlkaCu** [comment]
We will move the current powerflow data set from the model_draft to our versioned schemata (as v0.2.11) before starting the new run.

**Comment by gplssm** [comment]
Thanks for initiating the run of eGo DP v0.3.0! Currently, I'm focused on other things but I can give support when needed. If I don't react fast enough, just call me.

I'm curious how it goes on!

**Comment by IlkaCu** [comment]
At the moment we are executing snippet 'ego_dp_loadarea_loadmelt.sql'. 
Still a long way to go...

**Comment by IlkaCu** [comment]
The dp stopped in the REA part. I am out of office until 7/8/2017 and meanwhile @ulfmueller will continue the debugging. 
@Ludee: Please keep the github issues in mind I created during the past days.

**Comment by gplssm** [comment]
Thanks for the update. @Ludee will take care about it tomorrow. Today he's out of office.

**Comment by Ludee** [comment]
The REA part was refactored by @wolfbunke. I can help next week. Paper deadlines everywhere.
