### ISSUE TITLE
MViews for REA / RES data per scenario for integration

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#109]
Planned MView names of renewable and conventional power plants per scenario:

_conventional_:
-  model_draft.ego_supply_conv_powerplant_sq_mview
-  model_draft.ego_supply_conv_powerplant_nep2035_mview
-  model_draft.ego_supply_conv_powerplant_ego100_mview

_renewables:_
- model_draft.ego_supply_res_powerplant_sq_mview
- model_draft.ego_supply_res_powerplant_nep2035_mview
- model_draft.ego_supply_res_powerplant_ego100_mview

I am not sure if we need also to integrate the new scenario names as / into the mview names? See: #104

**Comment by IlkaCu** [comment]
From my point of view according to #104 the mviews for the 100% RE scenario should be named 'ego100' instead of 'ego2050'.

**Comment by lukasol** [comment]
@wolfbunke you asked us to update all table names and referenced this issue. Please provide a clear list of the new names (i.e. do you consider the comment of @IlkaCu ?)

**Comment by wolfbunke** [comment]
I changed the MView naming to `model_draft.ego_supply_res_powerplant_ego100_mview `and  `model_draft.ego_supply_conv_powerplant_ego100_mview` and updated it in the ticket description.

**Comment by wolfbunke** [comment]
The naming `_sq_ ` can be changed to `_statusquo_` in order to be more related to the scenario naming. I am fine with both naming. Do you have an idea or favourite ?

**Comment by lukasol** [comment]
Dont really care, but I think we need a quick solution.

**Comment by IlkaCu** [comment]
I would prefer to use _sq_ to limit the length of our table names.

**Comment by Ludee** [comment]
http://www.abbreviations.com/abbreviation/Status+Quo

> Status Quo - SQ
> Governmental » US Government

+1 for sq

**Comment by Ludee** [comment]
perhaps add additional info to Status Quo! Like **sq2016**?

**Comment by wolfbunke** [comment]
ok, we have now two option _sq_ or _sq2016_. According to the previous idea to stick to the ego paper I prefer _sq_.

**Comment by ulfmueller** [comment]
just leave it to sq , please.
A year number would not be good because it intentionally does not directly/consistently refer to a specific year (we have the weather year 2011 because it is a rather good representation of a normal weather year)...

**Comment by Ludee** [comment]
right, the year is not a good idea: **egosq** (in view of _ego100_) or only **sq**.

**Comment by wolfbunke** [comment]
I think we simply stick to `_sq_` because ego is already written at the beginning and we only have one sq scenario. Thanks a lot to all of you !!!

**Comment by wolfbunke** [comment]
ok, i close this ticket. thx

**Comment by gplssm** [comment]
I was looking for the RES tables and found a table named `model_draft.ego_supply_res_powerplant_2035_out_mview`. I assumed this is the same table as `model_draft.ego_supply_res_powerplant_nep2035_mview`. Two questions

1. Is my assumption right and only the table name is wrong?
2. Will the name of this mview change in future versions?

**Comment by Ludee** [comment]
0. The indicates that both are MViews and not tables. 
I used a NN to relocate some power plants outside Germany (outside MVGD) to the next substation.
[See code here](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/rea/ego_dp_rea_setup.sql#L73-L128)
1. `ego_supply_res_powerplant_2035_out_mview` makes no sense at all because we should not create power plants outside Germany for our future scenarios. Out only contains a selection (about 1000) and the nep2035 should contain the whole list.
2. I'm not aware of the naming concept of the REA. @wolfbunke is working with it right now.

**Comment by gplssm** [comment]
Ok, this is obviously the wrong table. Maybe I found the right one with `model_draft.ego_dp_supply_res_powerplant` @wolfbunke ?

If so, I would like to mention there is some confusion with scenario names

Executing 
```
SELECT count(id), scenario
  FROM model_draft.ego_dp_supply_res_powerplant
  GROUP BY scenario;
```
returns 

|count(id)|scenario|
|-----------|-----------|
|61867|NEP 2035|
|958082|ego-nep2035|
|1608354|Status Quo|
|2435284|eGo 100|

I assume eGo_100 is the intended scenario name, right?

**Comment by ulfmueller** [comment]
@wolfbunke is still in Riga. But maybe I can help a bit.

> I assume eGo_100 is the intended scenario name, right?

Right! the ego-nep2035 should not be there.

> Will the name of this mview change in future versions?

At least there is nothing like that thought of of far. We just changed our scripts. I prefer keeping that notation.

> Ok, this is obviously the wrong table. Maybe I found the right one with `model_draft.ego_dp_supply_res_powerplant @wolfbunke ?`

That should be the right table. Anyhow, the idea was to read the data from the scenario-specific mviews (naming see first post). But there should not be any problem taking the table and filter by scenario if you want...

**Comment by gplssm** [comment]
Thanks for the quick reply!

Now, I'm doing exactly as you suggested. Once the mviews are accessible, I use these in my analysis script.

**Comment by wolfbunke** [comment]
Hi @gplssm,
there are still old table and views I like to delete which are not for use, see #120.  
The changes of owner rights is running now.  The old scenario name ego-nep2035 was a bug which is changed to NEP 2035 now. 

Please note the flags repowering etc. and logic that only new or changed units are listed now. For example:  `SQ_constantly+NEP_commissioning - NEP_decommissioning -/+ NEP_repowering = NEP`

```
SELECT
  count(id),
  round(sum(electrical_capacity)/1000000,3) as el_cap, -- in GW
  generation_type,
  scenario
FROM model_draft.ego_dp_supply_res_powerplant 
GROUP by  generation_type, scenario
Order by scenario;
```

**Comment by gplssm** [comment]
Ok, I got it the half way...

@wolfbunke could you please notify me, once the MViews exist and are accessible?

**Comment by gplssm** [comment]
A quick comparison of capacity data in new MViews that replace former RES generation capacity table supply.ego_dp_res_powerplant

|Technology|v0.2.10|v0.3.0|
|---------------|---------|--------|
|solar|38513|38512|
|wind|48040|46976|
|geothermal|39|39|
|run_of_river|1649|1649|
|gas|632|632|
|biomass|7053|7053|

@wolfbunke numbers didn't changed that much. But do you know where deviations come from?

For the comparison I used for 
v0.3.0
```
SELECT generation_type, round(sum(electrical_capacity)/1e3)
	FROM model_draft.ego_supply_res_powerplant_sq_mview
	GROUP BY generation_type;
```

v0.2.10
```
SELECT generation_type, round(sum(electrical_capacity)/1e3)
	FROM supply.ego_dp_res_powerplant
	WHERE version = 'v0.2.10'
	GROUP BY generation_type;
```

**Comment by wolfbunke** [comment]
Without a closer look, it look like a old data bug of duplicate entries of wind_offshore in v2.10. @IlkaCu ?

**Comment by gplssm** [comment]
Another quick question: will these mviews be versioned as well? If unsure, I suggest yes.

**Comment by wolfbunke** [comment]
ok, I will implement it

**Comment by wolfbunke** [comment]
All changes are done in:
* https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_dp_res_rea_by_scenario.sql
* https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_dp_conv_by_scenario.sql

Thank you!

**Comment by nesnoj** [comment]
I checked the new mviews and get some odd results. Are the data up-to-date?
Executing
```
SELECT
	generation_type,
	count(id) as count,
	round(sum(electrical_capacity)/1000) as capacity_MVA
FROM
	model_draft.ego_supply_res_powerplant_sq_mview
GROUP BY
	generation_type
ORDER BY
	generation_type
;

```
I get only a little part of plants. Executing the same on the deprecated table `supply.ego_dp_res_powerplant` (with version filter) I get the right numbers. Is this due to the missing version no in the mviews (entire column `version` is set to "tba") or is there another bug?
@wolfbunke

**Comment by wolfbunke** [comment]
"tba" was the starting point (to be announced) from the branch. I will change it to the last version. thx.

**Comment by wolfbunke** [comment]
ok, I found the bug and solved it in  d54158f

**Comment by wolfbunke** [comment]
sorry misunderstanding. I checked the data with our query and got the full data:
```
SELECT  version,
	generation_type,
	count(id) as count,
	round(sum(electrical_capacity)/1000) as capacity_MVA,
	scenario
FROM
	model_draft.ego_supply_res_powerplant_sq_mview
GROUP BY
	generation_type,version,scenario
ORDER BY
	generation_type, version, scenario
;
```
Result:

|version|type|count|cap MVA|scn |
|----------|------|------|---------|---------|
|tba|biomass|15.308|7.053|Status Quo|
|tba|gas|838|632|Status Quo|
|tba|geothermal|30|39|Status Quo|
|tba|run_of_river|7.491|1.649|Status Quo|
|tba|solar|1.558.217|38.512|Status Quo|
|tba|wind|26.470|46.976|Status Quo|


Looks fine for me for the SQ Renewable Scenario or what is missing. If you wondering because of missing hydro Capacities over P >50MW  Hydro, pumped or run_of_river units can be found in conv.

```

SELECT  version,
	fuel,
	count(id) as count,
	round(sum(capacity)) as capacity_MVA,
	scenario
FROM
	model_draft.ego_supply_conv_powerplant_sq_mview 
GROUP BY
	fuel,version,scenario
ORDER BY
	fuel, version, scenario
;
```



|version|fuel|count|cap MVA|scn |
|---|---|---|---|---|
|tba|biomass|63|1.196|Status Quo|
|tba|coal|118|31.468|Status Quo|
|tba|gas|287|27.276|Status Quo|
|tba|gas_mine|2|75|Status Quo|
|tba|lignite|80|22.931|Status Quo|
|tba|oil|57|4467|Status Quo|
|tba|other_non_renewable|35|2.592|Status Quo|
|tba|pumped_storage|44|9.275|Status Quo|
|tba|reservoir|10|1.382|Status Quo|
|tba|run_of_river|90|2.344|Status Quo|
|tba|uranium|9|12.068|Status Quo|
|tba|waste|84|1.663|Status Quo|


From both tables you can find the scenario set (merge) for the grid calculation in  model_draft.ego_grid_pf_hv_generator

**Comment by nesnoj** [comment]
Thanks for your quick reply!
Sorry, my bad, it is working now!

One more problem with the current data:
```
SELECT version, count(id), sum(electrical_capacity)/1000000
  FROM supply.ego_dp_res_powerplant
  GROUP BY version;
```
returns 1,608,386 plants with a capacity of ~95.23 GW whereas the same command on `model_draft.ego_supply_res_powerplant_sq_mview` returns 1,608,354 plants with a cap. of 94.86 GW.
**I assume this small difference origins from an updated RES dataset?**

But now for the real odd stuff if you select the pp for 1 MVGD only:
```
SELECT version, count(id), sum(electrical_capacity)/1000
  FROM supply.ego_dp_res_powerplant
  WHERE subst_id = 3545
  GROUP BY version;
```
-> Results: plants: 957, capacity: 18.09 MW

Same query on `model_draft.ego_supply_res_powerplant_sq_mview`
-> Results: plants: 104, capacity: 3.86 MW

**Did the MVGD ids change between these 2 versions?**

**Comment by wolfbunke** [comment]
I think in supply.ego_dp_res_powerplant are all scenarios and maybe versions together without having the new table structure with scenario and version. @Ludee was ones uploading the model_draft tables to the supply schema in https://github.com/openego/data_processing/tree/release/v0.3/dataprocessing/sql_snippets/rea  or similar?  I will look for it tomorrow and change it. Ok?

Thank you for checking!

Here my query:
```
SELECT version, count(id), sum(electrical_capacity)/1000,scenario
  FROM supply.ego_dp_res_powerplant
  WHERE subst_id = 3545
  GROUP BY version,scenario;
```

```
SELECT version, count(id), sum(electrical_capacity)/1000, scenario
  FROM model_draft.ego_supply_res_powerplant_sq_mview
  WHERE subst_id = 3545
  GROUP BY version,scenario;
```

**Comment by nesnoj** [comment]
To my mind, the `supply.ego_dp_res_powerplant` is the current stable of RES data, isn't it? Hence the data should be correct?! @Ludee
And your improved MVIEW version `model_draft.ego_supply_res_powerplant_<SCENARIO>_mview` is the current unstable.
But I'm might not up-to-date..

**Comment by nesnoj** [comment]
Got it. The subst_id/MVGD ids simply changed.
Thanks for digging!

**Comment by wolfbunke** [comment]
Ok, nevertheless supply.ego_dp_res_powerplant should be changed.

**Comment by nesnoj** [comment]
> Ok, nevertheless supply.ego_dp_res_powerplant should be changed.
What exactly do you mean by this? That the table will be replaced by your versions in the v0.3 release?
