### ISSUE TITLE
Update all metadata to version 1.3

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#111]
metadata must follow new version 1.3.
@Ludee: 

- [x] Check all eGoDP tables (versioning)
Check all Input tables (OSM, borders, zensus)
- [x]  OSM
- [x] borders
- [x] zensus
- [x] gva (economic.destatis_gva_per_district)
- [x] demand federalstate (demand.ego_demand_federalstate)
- [x] wpa (supply.vernetzen_wind_potential_area)
- [x] supply.* @wolfbunke 
- [ ] forwind (supply.forwind_oeko_renewable_capacity_per_federalstate)
- [x] boundaries.gn250_b and boundaries.gn250_p

@MGlauer: 
- [x] Adjust OEP to display all fields from new version

**Comment by wolfbunke** [comment]
changed metadata to v0.3 of model_draft.supply conv and res

**Comment by wolfbunke** [comment]
supply.ego_renewable_power_plants_germany and supply.ego_conventional_powerplant are changed.

**Comment by KilianZimmerer** [comment]
'economic.destatis_gva_per_district', 'demand.ego_demand_federalstate' and 'supply.vernetzen_wind_potential_area' are updated to v.1.3.

Snippets are labeld with "_v.1.3" in the end and stored in /preprocessing/sql_snippets.

**Comment by IlkaCu** [comment]
Is this issue completed?

**Comment by MGlauer** [comment]
I will write a script that checks the state of the comments of all tables in the (visible schemas of the) oedb. Keep it open until then

**Comment by KilianZimmerer** [comment]
I updated all existing metadata to v1.3. Since some of the tables were using old metadata versions, their v1.3 version is not complete.

So far no metadata is existent for the following tables:
- climate.cosmoclmgrid
- environment.copernicus_clc_2012_v_18_4_filter
- environment.copernicus_clc_2012_v_18_4_filter_germany
- grid.ego_pf_hv_load_pq_set
- hydrolib.fred_gaugeheight_station
- openstreetmap.osm_deu_polygon_urban
- society.destatis_zensus_population_per_bkg_vg250_6_gem

**Comment by KilianZimmerer** [comment]
sorry, closing it was an accident ;-)

**Comment by IlkaCu** [comment]
The metadata for table grid.ego_pf_hv_load_pq_set can be found [here.](https://github.com/openego/data_processing/blob/release/v0.3/preprocessing/sql_snippets/ego_dp_structure_versioning.sql#L2699-L2784) This part of the snippet simply needs to be executed or am I wrong?

**Comment by Ludee** [comment]
Yes, I executed the sting and its valid.
@KilianZimmerer I just saw that you included RLI as copyright owner of all updated metadata strings. This is not correct! It depends on which institute created the table / code. So please have another look at all tables that were updated with your scripts.

**Comment by Ludee** [comment]
The other tables are not part of eGoDP and thus don't need to be updated for v0.3

**Comment by KilianZimmerer** [comment]
@Ludee I might did this with an older version of the conversion script. Recent updates should be alright, though. I will have a look.

**Comment by wolfbunke** [comment]
Hi, I just saw that the metadata of
* supply.ego_dp_res_powerplant 
* supply.ego_dp_res_powerplant 

includes wrong data. I didn't check further table. What is the status and who was to fix this bug?

**Comment by wolfbunke** [comment]
I changed the metadata of both tables with  8bd3509.
