### ISSUE TITLE
clean oedb schema openstreetmap

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#112]
We still have two versions of OSM in the schema. Are the tables openstreetmap.ego_deu_**power**_osm_X still in use? If not we should drop them.

**Comment by lukasol** [comment]
Good point. I created these tables once, but they are not in use any more and can be deleted from my point of view. 
@Ludee you can go ahead and delete them if @ulfmueller or @IlkaCu do not object.

**Comment by ulfmueller** [comment]
I have very rare knowledge on that. I do not know if we use them. But I guess it is fine. I do not want to object.
@IlkaCu do you know of any script which uses these osm tables?

**Comment by Ludee** [comment]
I searched all scripts and didn't find them.
Already dropped them and prepare the OSM metadata now. Thanks
