### ISSUE TITLE
Include 'eGo 100' scenario in DP 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#113]
New scripts for the scenario 'eGo 100' need to be included in the DP.

**Comment by wolfbunke** [comment]
**Info:** The power plant list of conventional power plants is ready. The script can be found [here](https://github.com/openego/data_processing/blob/features/power-plants-in-one-tb/dataprocessing/sql_snippets/rea/ego_dp_conv_by_scenario.sql). Path and names are also in ticket #109

**Comment by IlkaCu** [comment]
Duplication of #89
