### ISSUE TITLE
Adaptation of common power plant table structure

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#114]
After the restructuring of the conventional and renewable power plant tables MView per scenario should be integrated in the other scripts. see #109 

Please make sure:
- [ ]  that all Table names are changed to the MView Table ( Path in #109)
- [ ] control column names because of column inclusion by all scenarios

## Changed columns:

from   `model_draft.ego_supply_conv_powerplant_2035,
`
-   power_plant_name -> name,
-   commissioning -> commissioned
-   rated_power_b2035 ->  capacity,
-   tso -> network_operator,

## Full structure of renewable power plant table:
```
  version text NOT NULL,
  id bigint NOT NULL,
  start_up_date timestamp without time zone,
  electrical_capacity numeric,
  generation_type text,
  generation_subtype character varying,
  thermal_capacity numeric,
  city character varying,
  postcode character varying,
  address character varying,
  lon numeric,
  lat numeric,
  gps_accuracy character varying,
  validation character varying,
  notification_reason character varying,
  eeg_id character varying,
  tso double precision,
  tso_eic character varying,
  dso_id character varying,
  dso character varying,
  voltage_level_var character varying,
  network_node character varying,
  power_plant_id character varying,
  source character varying,
  comment character varying,
  geom geometry(Point,4326),
  subst_id bigint,
  otg_id bigint,
  un_id bigint,
  voltage_level smallint,
  la_id integer,
  mvlv_subst_id integer,
  rea_sort integer,
  rea_flag character varying,
  rea_geom_line geometry(LineString,3035),
  rea_geom_new geometry(Point,3035),
  scenario character varying NOT NULL,
  flag character varying,
  nuts character varying,
```

## Full structure of conventional power plant table:

```
  version text NOT NULL,
  id integer NOT NULL,
  bnetza_id text,
  company text,
  name text,
  postcode text,
  city text,
  street text,
  state text,
  block text,
  commissioned_original text,
  commissioned double precision,
  retrofit double precision,
  shutdown double precision,
  status text,
  fuel text,
  technology text,
  type text,
  eeg text,
  chp text,
  capacity double precision,
  capacity_uba double precision,
  chp_capacity_uba double precision,
  efficiency_data double precision,
  efficiency_estimate double precision,
  network_node text,
  voltage text,
  network_operator text,
  name_uba text,
  lat double precision,
  lon double precision,
  comment text,
  geom geometry(Point,4326),
  voltage_level smallint,
  subst_id bigint,
  otg_id bigint,
  un_id bigint,
  la_id integer,
  scenario text,
  flag text,
  nuts varchar
```

**Comment by ulfmueller** [comment]
[Here](https://github.com/openego/data_processing/tree/refactor/adaptation-powerplant-tables) the branch, where we can prepare our scripts for the upcoming changes.
@lukasol just told me will deal with the powerflow storage scripts

**Comment by lukasol** [comment]
> Here the branch, where we can prepare our scripts for the upcoming changes.
@lukasol just told me will deal with the powerflow storage scripts

just did that.

**Comment by lukasol** [comment]
Is the restructuring of the tables and their columns only true for the model_draft.ego_supply_conv_powerplant_2035 ? Or does it also apply to other tables?

**Comment by ulfmueller** [comment]
it applies to 6 tables, which you can find here: #109

**Comment by wolfbunke** [comment]
can this ticket be closed?

**Comment by gplssm** [comment]
Jap, RLI has made the adaptions.

**Comment by wolfbunke** [comment]
I close this issue.
