### ISSUE TITLE
Move scripts from dataprocessing to preprocessing 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#125]
All preprocessing scripts which are still integrated in the dataprocessing section need to be moved to the newly introduced preprocessing part of our repository. 
The authors of the respective scripts are responsible to do so.

**Comment by Ludee** [comment]
I moved most of the files that are not part of the eGoDP.
In **dataprocessing\sql_snippets** there are two scripts left that I don't know:

- [ ] ego_scenario_SH_NEP2035.sql
- [ ] ego_scenario_SH_status_quo.sql

**Comment by Ludee** [comment]
Just moved them to preprocessing as well because not part of eGoDP
