### ISSUE TITLE
How to handel scenarios for dingo in ego_dp_rea_results.sql 

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#128]
By changing all three scenarios in one table I saw that the script [ego_dp_rea_results.sql ](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/rea/ego_dp_rea_results.sql#L20-L30) is creating following tables:

- model_draft.ego_supply_rea_per_gentype_and_voltlevel
- model_draft.ego_supply_rea_per_mvgd
- model_draft.ego_supply_rea_per_loadarea
- model_draft.ego_supply_rea_per_method 
- etc. 

I don't know how you like to change his tables in order to have all scenarios in mind? At the moment I see two option:

1.  Creating three table
2. Or restructuring everything to one table by all scenarios

@gplssm  @Ludee @nesnoj at the moment I have no idea to change it for dingo or the eDisGO Tool.

**Comment by Ludee** [comment]
I'm not sure if these tables are used by DINGO. I don't think so. @gplssm ?

**Comment by gplssm** [comment]
We don't use any of the above tables in DINGO or eDisGo.

**Comment by wolfbunke** [comment]
ok thank you , please take a look in  #120 and delete not used table or views.
