### ISSUE TITLE
Wrong place for preprocessing scripts

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#131]
There are three scripts in a subfolder 'preprocessing' of the folder 'dataprocessing'. See [here](https://github.com/openego/data_processing/tree/dev/dataprocessing/preprocessing)
This is not the right place for preprocessing scripts any more. 
Please move them to the preprocessing [section](https://github.com/openego/data_processing/tree/dev/dataprocessing/preprocessing).

**Comment by wolfbunke** [comment]
ok, sorry

**Comment by wolfbunke** [comment]
done

**Comment by Ludee** [comment]
done
