### ISSUE TITLE
grant power plant mviews to oeuser

### ISSUE THREAD

**Issue by ulfmueller** [openego/data_processing#139]
concerning: 

- [ ] "ego_supply_conv_powerplant_sq_view"
- [ ]  "ego_supply_conv_powerplant_nep2035_mview" 
- [ ]  "ego_supply_conv_powerplant_ego2050_mview" 

@wolfbunke is the owner. That would lead to bugs in a dp run...
Please grant to oeuser!

**Comment by wolfbunke** [comment]
thank you, I changed it
