### ISSUE TITLE
Structure & setup in data processing

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#149]
Some of the structure & setup scripts are still included in the data processing. 
From my point of view this scripts belong to the preprocessing as they are not supposed to be executed in every data processing run. 
In the current status it is pretty hard to decide which scripts in the eGo_data_processing.py
must be execute and which must not. Therefore I would suggest to keep only those scripts in the dataprocessing which can/must be executed in every DP run.
For the first debugging I will keep the 'Structure & setup' segment in the eGo_data_processing.py and uncomment these scripts, but I would like to find a solution for this issue before we release v0.3.0. 

I see two different options in the moment
1. We create an own ego_setup.py which executes all scripts from the current 'structure & setup' segment
2. We include this segment in the ego_preprocessing.py 

@Ludee: Do you have any ideas and suggestions concerning this issue? Are there parts in the 'structure & setup" scripts which need to be executed in every DP run?

**Comment by IlkaCu** [comment]
This issue is still pending. 
@Ludee: Please add your comments here.

**Comment by Ludee** [comment]
I think option 2 is best.
Then we don't need a third script.

**Comment by IlkaCu** [comment]
> Are there parts in the 'structure & setup" scripts which need to be executed in every DP run?

@Ludee: Please let me know if there are scripts in den 'structure and setup' part which need to be executed in every DP run. Otherwise I will move all of them to the preprocessing section.

**Comment by IlkaCu** [comment]
Most of the structure and setup snippets are moved to the preprocessing section.
