### ISSUE TITLE
Empty and remove top-level folders

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#15]
Old structure orientated at db structure. Empty all these folders and delete them

**Comment by ulfmueller** [comment]
Where will we put scripts which are not part of the clean-run process? I think it would not be convenient to add these to the sql snippet folder. so we do need some new structure, right?

**Comment by gplssm** [comment]
Yes, you're right! Currently, I have no idea where to put the scrips. I'm open for suggestions.

**Comment by ulfmueller** [comment]
allright. maybe we can orient it with respect to the new oedb structure and create a folder for each of the new schemes (economic, grid,...).

**Comment by gplssm** [comment]
Good suggestion! 

I'll postpone to v0.2...

**Comment by Ludee** [comment]
I'm not sure. Then we have the same problems as in v0.1! Most scripts and programs use data from different schemas. 
I would suggest a structure oriented on models and submodels like **powerflow**, **dea allocation** ...

**Comment by Ludee** [comment]
bump my last comment!
I will take out ego_dea_allocation sql-scripts and organise in a separate folder.

**Comment by Ludee** [comment]
Still no feedback, so here are my suggests:
All parts of the ego tool should be inside the package folder **dataprocessing**.
The structure of the package is another issue I will open after this one.
The following list has all top level folders.

- [ ] calc_ego_hv_powerflow [ZNES] @ulfmueller @IlkaCu 
- [ ] calc_ego_powerflow  [ZNES] @ulfmueller @IlkaCu 
- [ ] calc_ego_substation [ZNES] @jong42 @ulfmueller @IlkaCu 
- [ ] calc_geo_powerplants 
- [ ] calc_renpass_gis
- [ ] orig_ego_consumption
- [ ] 
- [ ]

**Comment by ulfmueller** [comment]
Sorry, I am not sure what you want us to do now?
Yes we have some scripts which are not part of the clean-run procedure. And they will always be some scripts which are e.g. data pre-processing which does not make sense to inlcude in the clean run.
If we want to get rid of these top level folder we need a new place to put them.
I proposed a structure oriented at the new db structure you proposed a structure oriented on models. Both ways will have some pros and cons and i do not care too much. Finally where shall we place them?
If I understand you right on one level lower in the "dataprocessing"-folder, and then how do you want to call the "non-clean-run area"?

**Comment by Ludee** [comment]
The top level should be cleaned in order to import it as a package!? @gplssm 
Only _dataprocessing_, _documentation_ and LICENSE, README.md and setip.py stay on the top level?
So we move all used "snippets" to the _dataprocessing_ folder. Then remove the duplicates.

I'm not sure about the definition of the "clean run". In my understanding it was the name for _ego data processing v0.1_
We opened a branch to connect all snippets and execute them in one sequence to "clean" unwanted dependencies. _ego data processing v0.2_ doesn't have a name yet. 
I tried to start the discussion about the outer structure of ego and this repository in this issue #24 
I realized that it would really help the work on v0.2 if the appearance of the ego-tool is already outlined.

**Comment by Ludee** [comment]
Was the organisation of the repos part of the last meeting?
A restructuring of the files and folders should be done after the merge of v0.2 in master.
Is this already issue?

**Comment by nesnoj** [comment]
> The top level should be cleaned in order to import it as a package!? @gplssm
> Only dataprocessing, documentation and LICENSE, README.md and setup.py stay on the top level?
> So we move all used "snippets" to the dataprocessing folder. Then remove the duplicates.

Exactly. Only the package dir, LICENSE, README.md, setup.py, doc dir and, if needed, an example dir. As long as this structure is not implemented, a pip install will fail... v0.3 sounds reasonable.

**Comment by IlkaCu** [comment]
While restructuring the DP repository the remaining top level folders which should be emptied and removed where temporarily moved to the new utilities folder. This new folder needs to be cleared up and obsolete folders/files need to be removed.
