### ISSUE TITLE
VACUUM cannot run inside a transaction block

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#150]
Our first bug in v0.3!

**Comment by IlkaCu** [comment]
Executing the script 'ego_dp_vacuum_full.sql' brings up the following bug: 
> InternalError: (psycopg2.InternalError) VACUUM cannot run inside a transaction block

@Ludee: Any ideas what the problem is and how to solve it?

**Comment by ulfmueller** [comment]
@MGlauer do you know how to perform a vacuum which works executed via the [python execution script](https://github.com/openego/data_processing/blob/release/v0.3/dataprocessing/eGo_data_processing.py)?

**Comment by IlkaCu** [comment]
For the moment I'll skip the script 'ego_dp_vacuum_full.sql' and continue with 'ego_dp_structure_input_verification.sql'.

**Comment by Ludee** [comment]
http://initd.org/psycopg/docs/connection.html#connection.autocommit

**Comment by Ludee** [comment]
Removed from eGoDP and included hint in documentation to run a VACUUM before and after a DP run.
