### ISSUE TITLE
invalid input syntax for type json

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#151]
Executing the script ['ego_dp_structure_input_verification.sql'](https://github.com/openego/data_processing/blob/release/v0.3/dataprocessing/sql_snippets/ego_dp_structure_input_verification.sql) reveals a bug: 

> 2017-07-11 04:35:24 Execute 'ego_dp_structure_input_verification.sql' ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: invalid input syntax for type json
DETAIL:  Token "Commercial" is invalid.
CONTEXT:  JSON data, line 1: Commercial...

@Ludee: Any ideas?

**Comment by IlkaCu** [comment]
I'll skip this script as well for now and continue with the substation part.

**Comment by Ludee** [comment]
Looks like an invalid JSON metadata. I will check all input data for the eGoPP next week.

**Comment by IlkaCu** [comment]
Is this issue still pending?

**Comment by IlkaCu** [comment]
@Ludee: Any news here?

**Comment by IlkaCu** [comment]
@Ludee: Did you find the time to take a closer look here? 
If not, I would skip this snippet in the v0.3 release.

**Comment by Ludee** [comment]
Tricky bug!

There is a comment on column in the table _economy.destatis_gva_per_district_:

`COMMENT ON COLUMN economy.destatis_gva_per_district.gva_tertiary_sector
    IS 'Commercial, trading, public buildings etc.';`

I removed the comment and the script is working again.
So the _input_verification_ did it's job to give an error when the input table structures (metadata) is not valid ;)

The input information is now stored in the table _model_draft.ego_scenario_input_ for each version.
