### ISSUE TITLE
Bug in 'ego_dp_powerflow_create_pp_mview.sql'

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#156]
When executing the sql-snippet 'ego_dp_powerflow_create_pp_mview.sql' the following bug occurs:

![bug](https://user-images.githubusercontent.com/16799094/29272154-2be003aa-80ff-11e7-99fe-86b1592515b5.png)

@wolfbunke: Any ideas what happened here and how to solve it?

**Comment by wolfbunke** [comment]
Ok, I was testing the [ego_dp_powerflow_create_pp_mview.sql](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_powerflow_create_pp_mview.sql) SQL script via SQL Console without any problem (run time 1:36 minutes).
As next step I take a look into the SQL/Python translation in [/eGo_data_processing.py](https://github.com/openego/data_processing/blob/dev/dataprocessing/eGo_data_processing.py)

**Comment by wolfbunke** [comment]
Ok, looks like SQLAlchemy was not able to handle this script:

> SQLAlchemy  cursor.execute(statement, parameters) 
> TypeError: 'dict' object does not support indexing

This article was really helpful:
-  https://stackoverflow.com/questions/38090730/typeerror-dict-object-does-not-support-indexing-thrown-on-second-instance-of 
 The hint was that you should not use Python string code like % -> removed comment ` -- ego 100%`  to `-- ego 100` an it works 
See also: http://initd.org/psycopg/docs/usage.html#the-problem-with-the-query-parameters 

@me do not use  `%` or `+` in a SQL Comment which will be execute by SQLAlchemy
