### ISSUE TITLE
Update to new weather data

### ISSUE THREAD

**Issue by lukasol** [openego/data_processing#158]
New weather data will be provided by @wolfbunke. This results in necessary adjustments of https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_powerflow_timeseries_generator.sql

Will be implemented after Release v0.3

**Comment by wolfbunke** [comment]
Following new tables can be found on the oedb:
* model_draft.ego_res_powerplant_costdat_gid (related to model_draft.ego_dp_supply_res_powerplant with column coastdat_gid ) 
* model_draft.ego_simple_feedin_full ( Table with hourly time series for solar, wind on- and offshore  for all substation ids, coastdat_gid and scenarios)
* model_draft.ego_weather_measurement_point ( Table includes data for gerneation type, scenario, installed capacity and substation coastdat_id in coumn name ->1117084_3432_coast_gid_subst_id ) 

Those tables are created with following scripts: 
* https://github.com/openego/data_processing/tree/dev/preprocessing/python_scripts/renpass_gis/simple_feedin
* https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_weather_points_per_scenario.sql
* https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_simple-feedin_per_scenario.sql

**Comment by wolfbunke** [comment]
Todo's:

- [ ]  change weather id (w_id)
- [ ]  add ego 100 scenario
- [ ]  create/update  renpassGIS ts in https://github.com/znes/FlEnS/tree/master/open_eGo

**Comment by wolfbunke** [comment]
add ego 100 scenario done in 89d4a36

**Comment by wolfbunke** [comment]
All new weather time series  are created and calculated with renpassG!S.
In calc_renpass_gis.renpass_gis_scenario you can find now the changed scenarios of:

|scenario_id|scneario_name|
|---|----|
|40|eGo 100|
|41|NEP 2035|
|43|Status Quo|

in https://github.com/znes/FlEnS/tree/features/ego-timeseries you can find the new input setting as csv.
