### ISSUE TITLE
Viewname sq_view vs. sp_mview

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#160]
Hi,
I just noticed that in the DP file ego_dp_powerflow_create_pp_mview.sq the Mview name sq_view instead of sq_mview is used. see: #109 

https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_powerflow_create_pp_mview.sql#L20-L23

I would like to change it to sq_mview like the other scenario views. Are you okay with it @IlkaCu ?

**Comment by IlkaCu** [comment]
With commit 9680dd52bc7595d014a6e9ba87bf71ed868d7b7e I already fixed this bug in the branch release/v0.3. I would suggest a cherry pick if those changes are needed in the dev branch right know.
