### ISSUE TITLE
ego_dp_powerflow_voronoi_weatherpoint.sql -This script is no longer needed

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#161]
The script ego_dp_powerflow_voronoi_weatherpoint.sql  is no longer needed since table climate.cosmoclmgrid is used.

old script:
https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_powerflow_voronoi_weatherpoint.sql

New implementation see:
https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_generator.sql#L217-L225

Can it removed from DP? @ulfmueller , @IlkaCu

**Comment by IlkaCu** [comment]
From my point of view this script can be removed from the dev branch.

**Comment by s3pp** [comment]
I checked, model_draft.renpassgis_economy_climatepoint_voronoi is created in sql_snippets/ego_dp_powerflow_voronoi_weatherpoint.sql but no longer used by any other script. Should be safe to remove.

This also means, that relation calc_renpass_gis.parameter_solar_feedin, calc_renpass_gis.parameter_wind_feedin can safely be removed from the database. I guess calc_renpass_gis.cosmoclmgrid and calc_renpass_gis.voronoi_weatherpoint can be removed as well, but I'm not completely sure. What do you think?

**Comment by s3pp** [comment]
Can this issue be closed?

**Comment by IlkaCu** [comment]
Yes, I already removed this script from the DP.
