### ISSUE TITLE
supply data - energymap not open!

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#164]
In the open_FRED project, the lawyer Dr. Jaeger has had a look at all input data and licenses. 
One finding is that we now know for sure that what and how we do eGoDP is ok!
The metadata is suitable to provide all necessary information.

Except for one thing: The "energymap" data is not open and cannot be redistributed legally. 
This means that the tables _supply.ego_renewable_powerplant_ and thus _supply.ego_dp_res_powerplant_ must not be online!

Here are some options:
1. We delete all data without an open license and need to find other open data (difficult. OPSD data should be OK, but we have a low spatial resolution.
2. We move unlicensed data to "private" schemas, that are not online (OEP). The data can be used by "our" software, but we do not redistribute.
3. We leave the data online and risk to be sued by the TSO (small risk). We do something we know is  wrong.

Please comment and discuss!

**Comment by lukasol** [comment]
According to my understanding we currently do the same thing as energymap: publishing data without an explicit open license. They don't seem to have too much trouble with it...

Generally, such a discussion should take place in redmine.

**Comment by Ludee** [comment]
Moved to open_eGo Redmine. #1870659806
