### ISSUE TITLE
Add connections between electrical neighbours 

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/data_processing#168]
Comparable to the lines between Germany and its electrical neighbours, the electrical neighbours will be connected between themselves. 

Up to now, I researched the number and voltage level of crossing lines using entsoe grid map. 
When I connected Germany to its electrical neighbours, I used a dissertation (Electricity without borders) to find the cross-border capacitys.  
The total capacity of all lines crossing a border in entsoe grid map is always higher than the cross border capacity in the dissertation. 
So I would add the lines from entsoe grid map, is that all right?

**Comment by ClaraBuettner** [comment]
I started writing a script which connects electrical neighbours automatically, including Germany and connections between other countries. 
For AC-lines it works well but there are DC-lines as well. 
The last time, I changed the 400kVDC connection to Sweden into a 380kVAC line. Now there are more DC-lines. Shall I change them too or add a link-table for them?

**Comment by wolfbunke** [comment]
Hi @ClaraBuettner,
do you mean status quo or future Powerline projects?
The official overview of the status quo grid can be seen here:
https://www.entsoe.eu/map/Pages/default.aspx 
Are those new DC lines part of the ENTSO-E Map?
@ulfmueller what do you think?

**Comment by ClaraBuettner** [comment]
I mean status quo, the entsoe grid shows for example a DC connection between Denmark and Sweden.

**Comment by ClaraBuettner** [comment]
The new script for electrical neighbours is uploaded in feature/electrical_neighbours branch.

**Comment by ClaraBuettner** [comment]
In the last script I cheated and added the Sweden connection as AC line, but it's actually DC. Now, I could do it right and it would also be a good opportinuity to test DC-lines.

**Comment by ClaraBuettner** [comment]
![nachbarlander_mit_dc](https://user-images.githubusercontent.com/22964326/31492642-4ccf55c2-af4c-11e7-86ac-54486be8c09e.png)
![nachbarlander_ac](https://user-images.githubusercontent.com/22964326/31492648-4f63cb7e-af4c-11e7-9bb6-90cc8784a024.png)
Now, both is possible, the pictures show line loading at the same snapshots.  But I havn't thought the differences were so remarkable.

**Comment by IlkaCu** [comment]
This feature needs to be included in the v0.3.1 version of the dataprocessing

**Comment by IlkaCu** [comment]
@ClaraBuettner: In which branch did you include these adjustments?

**Comment by ClaraBuettner** [comment]
It ist in feature/electrical_neigbours.  To run it, tables inculding data from entso-e a needed. Unfortunately, I lost them when my disk crashed. It needs some time to recreate them. When do you need this?

**Comment by IlkaCu** [comment]
We would like to include this in the next dp run, which is scheduled for beginning of February. Can you estimate how long it will take you to recreate that table?

**Comment by ClaraBuettner** [comment]
Hopefully I won't need more then a day. I'll try to do this as soon as possible. I imported the data from csv to tables the database. Is it possible to integrate this? It is just used as an input-table.
