### ISSUE TITLE
Plausibility check for DP results

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#170]
The DP debugging is done. Before the actual release the data in model_draft which has been created during the debugging needs to be checked.

**Comment by IlkaCu** [comment]
53 buses, of which 27 are connected to generators, are not connected to any line and therefore isolated from the remaining grid.

**Comment by ulfmueller** [comment]
when calculating a LOPF for the Status Quo scenario, this is a 'warning message':

ERROR:pypsa.io:Error, new components for Generator are not unique

**Comment by ulfmueller** [comment]
in the following the 'error message':

WARNING - Loading a SolverResults object with a warning status into model=Linear Optimal Power Flow; message from solver=Model was proven to be infeasible.
ERROR:pypsa.opf:Optimisation failed with status warning and terminal condition infeasible
/usr/local/lib/python3.5/dist-packages/matplotlib/colors.py:581: RuntimeWarning: invalid value encountered in less
  cbook._putmask(xa, xa < 0.0, -1)
Traceback (most recent call last):
  File "appl.py", line 179, in <module>
    plot_stacked_gen(network, resolution="MW")
  File "/usr/local/lib/python3.5/dist-packages/egopowerflow/tools/plot.py", line 129, in plot_stacked_gen
    [network.generators[network.generators.control!='Slack'].index], 
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2053, in __getitem__
    return self._getitem_array(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2097, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 1229, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "Index(['6', '9', '12', '15', '18', '21', '24', '27', '30', '33',\n       ...\n       '200055', '200056', '200057', '200058', '200059', '200060', '200061',\n       '200062', '200063', '200064'],\n      dtype='object', length=12396) not in index"
>>>

**Comment by ulfmueller** [comment]
for the NEP 2035 scenario, this is what I get:

WARNING:pypsa.io:The following Generator have buses which are not defined:
Index(['2', '5', '8', '11', '14', '17', '20', '23', '26', '29',
       ...
       '200087', '200088', '200089', '200090', '200091', '200092', '200093',
       '200094', '200095', '200096'],
      dtype='object', length=14555)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
ERROR:pypsa.io:Error, new components for Generator are not unique
WARNING:pypsa.pf:No generators in sub-network 0, better hope power is already balanced
INFO:pypsa.pf:Slack bus for sub-network 0 is 20363
INFO:pypsa.opf:Performed preliminary steps
INFO:pypsa.opf:Building pyomo model using `angles` formulation
Traceback (most recent call last):
  File "appl.py", line 171, in <module>
    network = etrago(args)
  File "appl.py", line 137, in etrago
    network.lopf(scenario.timeindex, solver_name=args['solver'], extra_functionality=extra_functionality)
  File "/usr/local/lib/python3.5/dist-packages/pypsa/opf.py", line 1053, in network_lopf
    define_nodal_balances(network,snapshots)
  File "/usr/local/lib/python3.5/dist-packages/pypsa/opf.py", line 689, in define_nodal_balances
    network._p_balance[bus,sn].variables.append((sign,network.model.generator_p[gen,sn]))
KeyError: ('23646.0', Timestamp('2011-04-07 06:00:00', freq='H'))
>>>

**Comment by ulfmueller** [comment]
and for the eGo 100:

WARNING:pypsa.io:The following Generator have buses which are not defined:
Index(['1', '4', '7', '10', '13', '16', '19', '22', '25', '28',
       ...
       '200124', '200125', '200126', '200127', '200128', '200129', '200130',
       '200131', '200132', '200133'],
      dtype='object', length=8200)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
ERROR:pypsa.io:Error, new components for Generator are not unique
WARNING:pypsa.pf:No generators in sub-network 0, better hope power is already balanced
INFO:pypsa.pf:Slack bus for sub-network 0 is 20363
INFO:pypsa.opf:Performed preliminary steps
INFO:pypsa.opf:Building pyomo model using `angles` formulation
Traceback (most recent call last):
  File "appl.py", line 171, in <module>
    network = etrago(args)
  File "appl.py", line 137, in etrago
    network.lopf(scenario.timeindex, solver_name=args['solver'], extra_functionality=extra_functionality)
  File "/usr/local/lib/python3.5/dist-packages/pypsa/opf.py", line 1053, in network_lopf
    define_nodal_balances(network,snapshots)
  File "/usr/local/lib/python3.5/dist-packages/pypsa/opf.py", line 689, in define_nodal_balances
    network._p_balance[bus,sn].variables.append((sign,network.model.generator_p[gen,sn]))
KeyError: ('23646.0', Timestamp('2011-04-07 06:00:00', freq='H'))
>>>

**Comment by mariusves** [comment]
For Status Quo I'm getting the following:

ERROR:pypsa.opf:Optimisation failed with status warning and terminal condition infeasible
WARNING - Loading a SolverResults object with a warning status into model=Linear Optimal Power Flow; message from solver=**Model was proven to be infeasible.**
Traceback (most recent call last):

  File "<ipython-input-1-a9f812191d24>", line 1, in <module>
    runfile('C:/GitHub/eTraGo/etrago/appl.py', wdir='C:/GitHub/eTraGo/etrago')

  File "C:\Users\Marius\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "C:\Users\Marius\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/GitHub/eTraGo/etrago/appl.py", line 179, in <module>
    plot_stacked_gen(network, resolution="MW")

  File "c:\github\ego.powerflow\egopowerflow\tools\plot.py", line 129, in plot_stacked_gen
    [network.generators[network.generators.control!='Slack'].index],

  File "C:\Users\Marius\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2053, in __getitem__
    return self._getitem_array(key)

  File "C:\Users\Marius\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2097, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)

  File "C:\Users\Marius\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1229, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])

KeyError: "Index(['6', '9', '12', '15', '18', '21', '24', '27', '30', '33',\n       ...\n       '200055', '200056', '200057', '200058', '200059', '200060', '200061',\n       '200062', '200063', '200064'],\n      dtype='object', length=12396) not in index"

C:\Users\Marius\Anaconda3\lib\site-packages\matplotlib\colors.py:581: RuntimeWarning: invalid value encountered in less
  cbook._putmask(xa, xa < 0.0, -1)

**Comment by ulfmueller** [comment]
Status Quo works fine for me. Did you chose the load shedding function?

for the future scenarios, the errors remain.

**Comment by ulfmueller** [comment]
This function in pypsa throws the warning: 
https://github.com/openego/PyPSA/blob/master/pypsa/io.py#L217-L223

**Comment by ulfmueller** [comment]
For some reason, in the future scenarios the network.generators.bus object are decimal values. Therefore all the generators are not connected to the buses. It is weird because the data comes from the exact same column in the database. It might be rather an io problem in ego.powerflow or in the pypsa import_components_from_dataframe function. @mariusves @s3pp Any ideas?

**Comment by ulfmueller** [comment]
Found it!
There is each one power plant which has a null value in the bus column. That causes the problem. To test it I deleted them. For the debugging, here are they:

"NEP 2035";34843;;"variable";"PQ";900;f;0;;0;1;1;13;0;;
"eGo 100";34846;;"variable";"PQ";900;f;0;;0;1;1;13;0;;

**Comment by ulfmueller** [comment]
the model_draft right now (after the bug fixes done so far) allows to realize lopf for all three scenarios!!! The results on the first sight look reasonable!!
@IlkaCu Nice! what do you think? How far away are we from a clean-run?

**Comment by nesnoj** [comment]
Do you mean a clean-run for entire dp v0.3?
(If so, I'd like to mention #181 :)

**Comment by ulfmueller** [comment]
yes, I meant the entire run. Thx for mentioning #181 
Are all todos in #181 a must-have for the clean-run v0.3. (or will there be a next release ;))?

at least (to mention s.th. positive at the end of the week ;)),
I am happy that eTraGo can apparently produce quite reasonable results with that dataset now. And that for the first time we can model powerflows for the eGo 100 scenario. So at least for the hv / eTraGo world it looks quite ok...

**Comment by nesnoj** [comment]
Sounds great! :tada:
I'm struggling with the geno import of future scenarios since there're too many bugs in the supply part. I'm afraid that they have to be fixed prior to the release..
