### ISSUE TITLE
Missing generator timeseries 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#174]
The latest data set we created reveals bugs in the assignment of generator time series. In the different scenarios only 27 - 32 generators have a p_max_pu time series. Note: All renewable generators should have one. Only to those renewable generators connected to buses abroad time series where assigned. 
@wolfbunke: Might this bug be caused by your adjustments concerning the weather data?

**Comment by ulfmueller** [comment]
@wolfbunke please give this a very high priority!
This bug is a mayor problem - only if we have solved this we can have a clean dp release v0.3.

**Comment by IlkaCu** [comment]
I also noticed that the dispatch for wind and pv plants wasn't set to 'variable' in this run. (I will fix this) 
@s3pp, @wolfbunke : Is this information essential to generate p_max_pu time series for those generators?

**Comment by IlkaCu** [comment]
It actually seems that the missing dispatch information causes the problem. 
See [here](https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_lopf_data.sql#L69).

**Comment by IlkaCu** [comment]
After updating the dispatch information and a rerun of the relevant scripts this problem is solved.

**Comment by wolfbunke** [comment]
ok, nice!
