### ISSUE TITLE
changing ids of conv generators in different scenarios

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#175]
The ids for same conventional power plants are different for different scenarios.

```
SELECT *
  FROM model_draft.ego_dp_supply_conv_powerplant
  WHERE subst_id=265;
```
shows the problem.

Or try
```
SELECT *
  FROM model_draft.ego_supply_conv_powerplant_sq_mview as sq,
       model_draft.ego_supply_conv_powerplant_nep2035_mview as nep
  WHERE sq.subst_id=265 AND sq.id = nep.id
  ORDER BY sq.id;
```
and you'll get an empty list..

As far as I can see we do not have this problem in the RES tables..

This bug makes it very hard to add new generators resp. to check if a generator exists..
Please fix asap in v0.3, thank you!

**Comment by nesnoj** [comment]
Is it possible to assign the same ids for the same plants? Or is this impeded by the "different counting of blocks and power plants in the NEP Power Plant list and BNetzA Powerplant list" (https://github.com/openego/data_processing/issues/178#issuecomment-331797343) ?

If not I've no idea which column I can use to compare the same plant in different scenarios (according to your statement above, the bnetza_id seems not to be qualified)... @wolfbunke

**Comment by wolfbunke** [comment]
The best way is to compare the scenarios is by using the subst_id values like:
```
SELECT 
*,
round((nep_cap - sq_cap)::numeric,3) as diff_cap -- in MW
FROM
(
SELECT sum(capacity) as sq_cap,  count(*) sq_count ,scenario
  FROM model_draft.ego_supply_conv_powerplant_sq_mview 
  WHERE subst_id=265 
  Group by scenario
) as  sq,
(SELECT sum(capacity) as nep_cap, count(*) nep_count, scenario
FROM  model_draft.ego_supply_conv_powerplant_nep2035_mview 
  WHERE subst_id=265 
  Group by scenario
) as nep;
```
Result of subst_id=265 : 

| sq_cap |sq_count |scenario| nep_cap|nep_count |scenario|diff_cap|
|-----|---|-------|------|----|--------|-----|
|98.2|3|Status Quo|101.1|3|NEP 2035|2.900|


The comparison of  single power plants can only be done by using the bnetza_id and a aggregation functions in order to sum up the different blocks. This works for 620 (of sq=834, nep = 889) plants
```
SELECT 
sq.*,
nep.*
FROM
(
SELECT
sq.bnetza_id AS SQ_BID,
sq.capacity SQ_CAP,
sq.scenario AS SQ_SCN
FROM model_draft.ego_supply_conv_powerplant_sq_mview sq,
	(
	 SELECT
	   array_agg(bnetza_id) ids
	 FROM  model_draft.ego_supply_conv_powerplant_nep2035_mview 
	 --WHERE subst_id=265
	) as bnetza_id
Where   sq.bnetza_id = ANY(bnetza_id.ids)
Group by sq.bnetza_id,sq.capacity,sq.scenario
) as sq
inner join
(SELECT
  nep.bnetza_id AS NEP_BID,
  nep.capacity AS NEP_CAP,
  nep.scenario AS NEP_SCN
FROM model_draft.ego_supply_conv_powerplant_nep2035_mview nep,
	(
	 SELECT
	   array_agg(bnetza_id) ids
	 FROM  model_draft.ego_supply_conv_powerplant_nep2035_mview 
	 --WHERE subst_id=265
	) as bnetza_id
Where   nep.bnetza_id = ANY(bnetza_id.ids)
Group by nep.bnetza_id,nep.capacity,nep.scenario
) as nep
on nep.NEP_BID = sq.SQ_BID
;
```
To find not matched power plants you can use this query:
```
SELECT
nep.*
FROM
(
SELECT array_agg(bnetza_id) ids
FROM  model_draft.ego_supply_conv_powerplant_sq_mview 
) as sq,
model_draft.ego_supply_conv_powerplant_nep2035_mview nep
Where NOT nep.bnetza_id = ANY(sq.ids)
```

**Comment by nesnoj** [comment]
Thanks for the queries, but is it possible for you to assign the same ids for the same plants?

1. This would be an easier and consequent way (as in RES) of using it... 
2. I could implement your query(ies) in SQLA but since I do not fully understand them (+there's no documentation), it's very likely that, if something will change in the future, I will be hardly able to understand or fix the bug...
3. Imagine someone else wants to determine the changes from SQ to NEP2035 using the OEP data - when it is not easy for me, how can we make him/her understand how it works :question: 

If it is not that easy, could you specify what's the problem and we may find a solution?

**Comment by wolfbunke** [comment]
I see your point. But the question is also as long new IDs are given by NEP lists and power plants are changing e.g. by changes of technology, capacity, fuel etc. how I make the decisions of merging those power plants together? Or do we have new Power plants / blocks? A matching could ends in missunderstanding by having unique id's, or? Another way for comparison could be to compare the regional changes by scenarios by using of the geometry in order to see the changes.  

How importent is a solution in time? Is it v0.3 relevant?

**Comment by nesnoj** [comment]
Further steps:

I'll try to find out if grid expansion costs are negligble compared to the costs for RES connection

- Yes: I will disconnect all conv. PP of SQ and treat the ones from NEP as new PP.
- No: Identify existing genos by using the geom

**Comment by IlkaCu** [comment]
@nesnoj: As I am trying to push the release v0.3 further, please let me know if this issue is absolutely necessary for v0.3 from your point of view. 
If yes, how far are we from a solution and is there anything I can do?

**Comment by nesnoj** [comment]
I need it asap and I'd prefer a dp-solution for the reasons stated above.
But I think I can solve it in eDisGo with the current PP data..
