### ISSUE TITLE
Some generators outside Germany without source

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#177]
In the eGo 100 scenario some generators assigned to buses abroad are lacking information about their source.
![grafik](https://user-images.githubusercontent.com/16799094/30750929-11791f06-9fb8-11e7-9ff0-aa771ff25133.png)

@s3pp, @wolfbunke: Any ideas how this can happen?

**Comment by wolfbunke** [comment]
Ok, I will check the sources and assignment of renpassGIS. My first guess was a bug in [powerflow_timeseries_generator.sql](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_powerflow_timeseries_generator.sql) but it seems the bug happens earlier in process.

**Comment by wolfbunke** [comment]
I checked the different results objects of renpassGIS and the eGo 100 scenario and couldn't find a bug or changes of the source.

```
Select obj_label
From calc_renpass_gis.renpass_gis_results
Where scenario_id = 40
And  obj_label NOT IN (Select obj_label
		      From calc_renpass_gis.renpass_gis_results
		       Where scenario_id = 39
			Group by obj_label
			Order by obj_label)
Group by obj_label
Order by obj_label 
```

Is this also happening in NEP 2035 scenario or only in eGo 100 @IlkaCu ?

**Comment by wolfbunke** [comment]
![gis_plot_](https://user-images.githubusercontent.com/14540685/30807807-ad99dc14-a1fb-11e7-8054-74a6388ef266.png)


```
Select
   ROW_NUMBER () OVER (ORDER BY gen.bus) as id,
  gen.*,
  line.geom
From model_draft.ego_grid_pf_hv_generator gen,
     model_draft.ego_grid_pf_hv_line  line
Where source IS NULL
And gen.bus = bus0  
And gen.scn_name = 'eGo 100';
```

**Comment by wolfbunke** [comment]
```
Select
*
From calc_renpass_gis.renpass_gis_source 
Where scenario_id = 40
and  nominal_value[1]::int in (18200,5676,1,8130,2,819,21383)
```
Ok, I found the missing seven sources by using the p_nom value: "AT_hydro", "AT_geothermal", "CH_hydro", "CZ_hydro", "FR_hydro", "FR_geothermal", "SE_hydro"

**Comment by wolfbunke** [comment]
I prepared a bug fix for this version:

```
Update  model_draft.ego_grid_pf_hv_generator 
set source = 10 -- reservoir
Where scenario_id = 40
And source IS NULL
And p_nom is in (18200,5676,8130,819,21383) 
```
and for geothermal here

```
Update  model_draft.ego_grid_pf_hv_generator 
set source = 14 -- geothermal
Where scenario_id = 40
And source IS NULL
And p_nom is in (1,2) 

```
I used the source numbering according to `model_draft.ego_grid_pf_hv_source`.
The eGo 100 Scenario set is changed [here](https://github.com/znes/FlEnS/commit/0697404e4d2f2fab69dd67bdd09c7d5d25803044)

If you agree I will use the bug fix without running all renpassGIS calculation again including new scenario number, etc.?

**Comment by wolfbunke** [comment]
renpassGIS lable fix:

```
Update  calc_renpass_gis.renpass_gis_source 
set label = left(label, 3) || 'reservoir',
    source = left(source, 3) || 'reservoir'
Where  label like '%%_hydro';


Update  calc_renpass_gis.renpass_gis_results 
set    obj_label = left(source, 3) || 'reservoir'
Where obj_label like '%%_hydro'
AND obj_label NOT like '%%_storage_pumped_hydro';


```

**Comment by wolfbunke** [comment]
@IlkaCu please check and close this issue

**Comment by IlkaCu** [comment]
What about the geothermal power plants?
And what do you want me to check? Your changes in renpassGIS or if it affects the overall results in the PF-data?

**Comment by IlkaCu** [comment]
What about the geothermal power plants?
And what do you want me to check? Your changes in renpassGIS or if it affects the overall results in the PF-data?

**Comment by wolfbunke** [comment]
Yes I changed all. By checking the data and code I couldn’t find a bug for geothermal in renpassGIS. I am not sure what happens.

**Comment by wolfbunke** [comment]
By checking i meant to test if the Data error is fixed and works for you.

**Comment by IlkaCu** [comment]
The renpassGIS label fix didn't solve the problem. I did some further debugging here 3ab34f48a9895240ceacd77a951b291dc7dab3ba
Before the clean run I need to check whether this solved the bug or not. Before executing the related snippets I wait for #185 to be solved.

**Comment by s3pp** [comment]
This could work! I looked it up, reservoir and geothermal powerplants are modelled as source components.
