### ISSUE TITLE
bug in v_level of generators

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#179]
In some (or all, I don't know) datasets of RES PP (`ego_dp_supply_res_powerplant`), `voltage level_var` is different from `voltage_level` (in all scenarios).
E.g. geno id=902876 says "07 (NS)" and "6"...
```
SELECT *
  FROM model_draft.ego_dp_supply_res_powerplant
  WHERE id = 902876;
```
How come?

**Comment by IlkaCu** [comment]
The column voltage_level_var is the 'original' data from BNetzA etc. and the entries in the column voltage_level are created according to our allocation table and the installed capacity of the specific power plant. 
One exception are offshore wind power plant which are generally assigned to voltage level 1.

**Comment by nesnoj** [comment]
Oh, I should know this...*cough*
Thanks for re-explaining
