### ISSUE TITLE
RES PP with capacity=0

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#182]
Some (173) RES PP of type biomass in NEP 2035 scenario have a capacity of 0. Is this a bug or a feature?
If the value is correct, shouldn't they be removed from the table?

Query:
```
SELECT *
  FROM model_draft.ego_supply_res_powerplant_nep2035_mview
  WHERE voltage_level in (4,5,6,7) AND version='tba' AND scenario='NEP 2035' AND electrical_capacity = 0;
```

Edit: This problem does not occur in EGO100 scenario.

**Comment by wolfbunke** [comment]
His problem is solved in  13583e5  by adding a filter to the mviews.

**Comment by nesnoj** [comment]
In your commit, you use `electrical_capacity >= 0` which includes PP with cap=0.
Shouldn't you use `electrical_capacity > 0` instead?

**Comment by wolfbunke** [comment]
yes of course, I was sending the wrong commit 0ac99c6, sorry.
