### ISSUE TITLE
population differs between MVGDs and LAs

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#183]
By accident, I discovered an inconsistency in dp numbers:

Population sum of all MVGD = 78.138.134
```
SELECT sum(zensus_sum)
  FROM grid.ego_dp_mv_griddistrict
  WHERE version = 'v0.2.10';
```

Population sum of all LA = 80.318.192
```
SELECT sum(zensus_sum)
  FROM demand.ego_dp_loadarea
  WHERE version = 'v0.2.10';
```
(same problem in the model draft version with slightly different numbers)

Ideas, somebody?

**Comment by nesnoj** [comment]
From my POV, this one is quite crucial and must be solved prior to v0.3.0 release.
Who is responsible for the scripts?

**Comment by IlkaCu** [comment]
@Ludee is the author of the LA scripts. Can you help here? 
Unfortunately I'm not familiar with these scripts.

**Comment by Ludee** [comment]
I will have a look at it now.

**Comment by Ludee** [comment]
Bei den MVGD war das "falsche" geom (nicht _geom_pnt_) gewählt.

**Comment by Ludee** [comment]
table, sum, count
'md mv_griddistrict','80319370','3177354'
'md loadarea','80318008','3177139'

Jetzt kommt der härte Teil: 215 Zensuspunkte werden in den LA nicht gezählt.

**Comment by nesnoj** [comment]
Uh, that's odd...
Why did you use UNION? Is there something wrong with the simple queries in my first post?

**Comment by IlkaCu** [comment]
Any news here?

**Comment by Ludee** [comment]
I could identify the bug between the osm landuse and LA geometries. the census points are too close to the edges (ca. 100m) and thus are not included. I don't know why the borders change, I guess due to a buffer and rebuffer.
I will fix it, either by finding the source of the border difference or by just solving it hard.
![2017-10-21_census_bug](https://user-images.githubusercontent.com/14353512/31851591-21f44b2c-b669-11e7-9b17-d491775ddcd2.png)

**Comment by Ludee** [comment]
A deeper look into the [ST_BUFFER functions](http://postgis.net/docs/ST_Buffer.html) gives two possibilities:
1. Increase the number of points to make the buffer "round" -> **quad_segs**=8 (default, green line) -> 16 (blue line)
This gives a "better" result and fixes this example, but still has a tiny gap. Also increases geom size and calculation time. so:
2. Change the **join style** to "mitre" and force to be correct! (red line)

This makes a difference of less then 1 metre and wasn't considered until now.
I will make a PR with changing all ST_BUFFER with this option and it should fix the bug and increases precision of all LA. I think "mitre" should be 
![2017-10-21_census_bug](https://user-images.githubusercontent.com/14353512/31852535-8ff6813e-b679-11e7-8e1a-bb5f43e7d3ec.png)


Of course only to the negative buffer ;)
![2017-10-21_census_bug](https://user-images.githubusercontent.com/14353512/31852599-9fb0b788-b67a-11e7-8998-961dc5d48f41.png)

**Comment by Ludee** [comment]
I did some more testing and saw that the solution doesn't work as desired. The concave geometries (and census squares) aren't "melted properly" resulting in ugly LA.
I will do some tests with solution 1 and compare the calculation time. Damn complicated bug!

**Comment by IlkaCu** [comment]
Could you please let me know when you are planning to further work on this bug? As I'd like to start the clean run tomorrow or Thursday, we need to decide whether we can include this bug fix in v0.3 or postpone it to v0.3.1.

**Comment by gplssm** [comment]
As far as I understood @Ludee he decreased difference significantly. He won't fix it entirely in v0.3. I shift it to v0.3.1

**Comment by IlkaCu** [comment]
Is a further bug fixing for v0.3.1 planned? Please note, that I'd like to start the debugging in beginning of February.

**Comment by Ludee** [comment]
I will try to crack that nut:

```SQL

SELECT 'Inside vg250',sum(population), count(population)
FROM model_draft.destatis_zensus_population_per_ha_invg_mview
UNION ALL
SELECT 'Outside vg250',sum(population), count(population)
FROM model_draft.destatis_zensus_population_per_ha_outvg_mview;
```
| Inside vg250 | 80321883 | 3177493 | 
| ------------- |:-------------:| -----:|
| Outside vg250 | 2399 | 230 | 

Theses 230 are "border census points". They are not counted because the centroid is outside vg250 and will be removed in eGoPP.

**Comment by Ludee** [comment]
The solution is avoiding the bug by leaving a 1m difference during the buffering. Buffer with +100m and Rebuffer with only -99m. It increases the areas of all LA.
I cannot test the bug right now because the oedb is too busy for the loadarea data.
