### ISSUE TITLE
Missing subst_id in commissioned RES

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#184]
In the newly commissioned wind and PV PP in NEP+EGO100 MVIEWs the substation id is missing..

Try
```
SELECT count(id), scenario, flag, generation_type, subst_id
  FROM model_draft.ego_supply_res_powerplant_nep2035_mview
  WHERE voltage_level in (4,5,6,7)
  GROUP BY scenario, flag, generation_type, subst_id
  ORDER BY scenario, flag, generation_type, subst_id;
```

**Comment by wolfbunke** [comment]
HI I was restarting the processing of all RES data the script for the subst_id's is still running.

**Comment by nesnoj** [comment]
ok, please leave a short message as soon as it will be finished..

**Comment by wolfbunke** [comment]
Update the script is still running :( I hope tomorrow it is done.

**Comment by nesnoj** [comment]
Ok.
Please announce when you plan to update the tables next time since it is pretty hard for me to test my code without data.. ;) thanks!

**Comment by wolfbunke** [comment]
I am sorry! It was not planed like this!

**Comment by wolfbunke** [comment]
Ok, the run is done.
