### ISSUE TITLE
Create power plant MViews for supply schema including version number

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#185]
Create MViews for 
- supply.ego_dp_res_powerplant
- supply.ego_dp_conv_powerplant

for each scenario and version

**Comment by nesnoj** [comment]
see #189

**Comment by nesnoj** [comment]
I'm creating these MVIEWs for my `v0.3.0pre1` pre-release (supply table changes see #189) using [this script](https://gist.github.com/nesnoj/5f490ecd7a43feed7f74bc0d666f3543) (adapted from [dp script](https://github.com/openego/data_processing/blob/ca37b99a2b3a454ce2491ed4187fec31d078adda/dataprocessing/sql_snippets/ego_dp_powerflow_create_pp_mview.sql)).
I hope I did it the right way. You may adapt it and add it to the DP scripts (**haven't done this yet!**).

2 questions @wolfbunke:
1. The SQ part of the script finished, but the NEP2035 part (haven't tried the ego100 yet) seems not to terminate (at least not after ~12h) - how long did it take the last time you ran it on model draft?
2. What is the `preversion` column used for? It is now contained in the new supply tables (+mviews) too..

**Comment by wolfbunke** [comment]
Hi @nesnoj ,

the creation of the MViews takes normally for SQ  1min, NEP ~60 min and ego100 ~ 120 min.  Maybe a vacuum analyze could help? 
The perversion column is the version number of the predata processing  of supply tables which are not part of the data processing.  

Thanks for your help!

**Comment by nesnoj** [comment]
I did a `VACUUM ANALYZE` and re-ran the script again, but stopped it at execution time >4h..

I only changed the table names and the version (uh, I just found that there's no version column in the MVIEWs, only a preversion). The only thing that might be a reason is the updated index (added `scenario` column, see https://github.com/openego/data_processing/issues/189#issuecomment-340739098). I created the index without btree or other fancy stuff..
Note: There're indices on the geom cols..

@wolfbunke Please review the NEP2035+ego100 parts of the [gist script](https://gist.github.com/nesnoj/5f490ecd7a43feed7f74bc0d666f3543#file-ego_dp_powerflow_create_pp_mview-sql-L121-L233).

**Comment by wolfbunke** [comment]
oh, now i See the `version` selection is missing. In suplly preversion and version is needed. I will change it in a second.

**Comment by wolfbunke** [comment]
I started the script to create the new MView of NEP 2035 with[ following changes. ](https://gist.github.com/wolfbunke/ed45a361a7b4e838a4e9c394351ca100#file-mview_supply_res_powerplants_nep2035-sql)

I hope that it will fix the time issues.

**Comment by nesnoj** [comment]
Hmm, no results yet..
May we ask @Ludee if he has got a hint on this?

**Comment by wolfbunke** [comment]
Strange it is still running > 10h. At the moment I see following possible reasons why the creation of this Mviews takes so long : 

- two gist index on different geom columns 
- database Version control of schema supply  vs. model_draft without control? @MGlauer

**Comment by IlkaCu** [comment]
@wolfbunke Do you have any idea how long this process will take? I would like to finish the DP release as soon as possible! 
Or is there a feasible plan B?

**Comment by Ludee** [comment]
My first comments and questions after looking at the GIST (no offence!)

* The SQL is WAY TO COMPLICATED!
* Using sub- and sub- SELECTS is an option, but not a good one -> use WITH

* What is the `id NOT IN SELECT` doing? I don't get it! It's just a list of all ID
* Why the UNION between the two queries? 

This shows three scenarios for the "pre" version. What's the problem directly selecting all plants with it?
`SELECT  version, scenario
FROM    supply.ego_dp_res_powerplant
WHERE version = 'v0.3.0pre1'
Group BY version, scenario;`

I must say don't get the scenario definition and application in that table.
Where can I find a description of the data model?

**Comment by wolfbunke** [comment]
model_daft script: https://github.com/openego/data_processing/blob/release/v0.3/dataprocessing/sql_snippets/ego_dp_powerflow_create_pp_mview.sql

**Comment by wolfbunke** [comment]
After discussing the problem we figured out that
* the mview is  working but the complexity is quite high
* using `having` and `group by` leads to long query run times  
* the use of hstore could fix the complexity and run-time
* using a further where clause could reduce the problem

**Comment by wolfbunke** [comment]
I started a new test by following changes: https://gist.github.com/wolfbunke/ed45a361a7b4e838a4e9c394351ca100

**Comment by wolfbunke** [comment]
ok NEP is done now in 34:35 minutes. I will start ego 100 at home in a hour

**Comment by IlkaCu** [comment]
In the v0.3.0 release all scripts to create power plant mviews were successfully executed.
