### ISSUE TITLE
missing scenario column in supply.ego_dp_res_powerplant

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#189]
@wolfbunke The `supply.ego_dp_res_powerplant` does currently not have a `scenario` column. I guess you have to add it prior to the v0.3 release not to loose this information?

I just added a new version `v0.3.0pre1` and saw that this info is missing..

Any other tables affected? conv PP?

**Comment by nesnoj** [comment]
I need this column now (prior to v0.3 run), can we just add it? Any other tables affected besides `supply.ego_dp_res_powerplant` and `supply.ego_dp_conv_powerplant`?

**Comment by IlkaCu** [comment]
What do you mean by scenario column? As far as I see the tables do have a version and a preversion column.

**Comment by nesnoj** [comment]
Have a look at `model_draft.ego_dp_supply_res_powerplant` which is the current unstable. @wolfbunke introduced the `scenario` col. which contains "Status Quo"/"NEP 2035"/"ego 100". He uses it in the MVIEWs to select the right plants..

**Comment by nesnoj** [comment]
Damn, another bug:
In the `ego_dp_versioning.sql` script, the old tables are copied! (`model_draft.ego_supply_res_powerplant` / `model_draft.ego_supply_conv_powerplant`)

Please adjust and re-check if any other source tables must be renamed..

**Comment by IlkaCu** [comment]
From my point of view you can add the missing scenario column in supply.ego_dp_res_powerplant and supply.ego_dp_conv_powerplant. 
Meanwhile I will check and adjust the versioning script.

**Comment by nesnoj** [comment]
@wolfbunke Objections?

**Comment by IlkaCu** [comment]
Wolfbunke is out of office this week. So it's up to us to decide.

**Comment by IlkaCu** [comment]
Table model_draft.ego_supply_conv_powerplant also includes a column 'la_id'. Should this one be included in the versioned table as well?

**Comment by nesnoj** [comment]
Ok. I can add the additional column without the NOT NULL flag..but this must be reviewed by @wolfbunke later on (+ do not forget to .

My primary concern is, that the change in those two table names (`ego_supply_res_powerplant` --> `ego_dp_supply_res_powerplant` + same in conv. table) might not be considered in the whole DP. Searching in the repo, I still find heaps of occurences of the old name in the code.. and I am pretty sure that there will be more issues after renaming :hankey:.

Are you gonna try to fix it?

**Comment by nesnoj** [comment]
> Table model_draft.ego_supply_conv_powerplant also includes the columns 'la_id', 'flag' and 'nuts'. Should they be included in the versioned table as well?

`model_draft.ego_supply_conv_powerplant` is the old one! You probably mean the new one as it contains these cols as well..
Yes, I assume they have to be added too (at least flag and la_id must be included).

**Comment by IlkaCu** [comment]
First I'll fix the versioning script and add the missing columns in the supply-tables, which you need for your backups, right? 
After that I will check how the renaming influences the DP.

**Comment by nesnoj** [comment]
I'm running out of time and gotta leave it for today. Could you please add the scenario cols as well?
Please notify when you finished and before you press release button :play_or_pause_button: .
Cheers!

**Comment by IlkaCu** [comment]
I added the missing columns in table supply.ego_dp_res_powerplant and supply.ego_dp_conv_powerplant and adjusted the versioning script accordingly.

**Comment by nesnoj** [comment]
I tried again to create a new version `v0.3.0pre1` and got:
```
ERROR:  duplicate key value violates unique constraint "ego_dp_res_powerplant_pkey"
DETAIL:  Key (version, id)=(v0.3.0pre1, 425350) already exists.
```
Since there can be multiple occurences of the same PP (due to the scenario), the `scenario` column has to be added to the pkey. But: To create it, `scenario` must not contain NULL values which occur in all datasets prior to v0.3.0. We yould set it to "-" or similar..

What do you think @IlkaCu ?

**Comment by nesnoj** [comment]
Ok, I changed the tables `supply.ego_dp_res_powerplant` and `supply.ego_dp_conv_powerplant`:
- changed the PKEY: column `scenario` added (new PKEY includes now `version`, `scenario`, `id`)
- set DEFAULT value to `'none'` (I updated all existing datasets to `'none'`)

I ran versioning for `v0.3.0pre1` successfully, looks good:
```
SELECT version, scenario, count(id)
  FROM supply.ego_dp_res_powerplant
  GROUP BY version, scenario;
```
It should work now for `v0.3.0` too..

If you @IlkaCu @wolfbunke accept this solution, please close.

**Comment by wolfbunke** [comment]
Hi @nesnoj, the solution looks fine for me. Thank you!
