### ISSUE TITLE
Fix version specification of ego.io

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#19]
setup.py has version specification to 0.0.1rc7 but pip is lying and says max ego.io0.0.1rc4 is available.

**Comment by lukasol** [comment]
@gplssm is this (and the other issue regarding Release v0.1, #32) still open? if yes, I suggest a move to Release v0.2 or -- maybe more realistic -- Release v0.3.

**Comment by Ludee** [comment]
I agree, let's close ms1

**Comment by nesnoj** [comment]
> setup.py has version specification to 0.0.1rc7 but pip is lying and says max ego.io0.0.1rc4 is available.

I do not copy, pip says 0.0.2 here
