### ISSUE TITLE
add GIST index to PF HV tables

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#194]
The tables
```
grid.otg_ehvhv_bus_data
grid.otg_ehvhv_branch_data
grid.otg_ehvhv_dcline_data
```
do not have a (GIST) index on `geom`. I'd like to do some PostGIS queries but it's terribly slow.
I tried to add it but couldn't find the place where these tables are created. Could you either tell me where this takes place or add the indices, please?

**Comment by IlkaCu** [comment]
These tables are input tables from osmtgmod and their creation it not included in the DP. 
Maybe @Lukasoldi can help.

**Comment by nesnoj** [comment]
Actually, I need lines, buses etc. to perform PF. But I just saw that I better use data from `grid.ego_pf_hv_*` tables..
Anyway, there're no GIST indices on these tables either. They would speed up [your queries](https://github.com/openego/data_processing/blob/release/v0.3/utilities/ego_scenario_SH_status_quo.sql#L13-L21) too..

**Comment by IlkaCu** [comment]
The mentioned tables `grid.ego_pf_hv_*` have been created with code documented in the script [ego_dp_versioning.sql](https://github.com/openego/data_processing/blob/release/v0.3/dataprocessing/sql_snippets/ego_dp_versioning.sql). You could add the GIST indices and add the code into this snippet (but you should comment it out, just like the `CREATE TABLE`- statements).
