### ISSUE TITLE
no module named 'oemof' 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#195]
The following error message occurs while executing the script ego_dp_powerflow_griddistrict_demand.py: 

![grafik](https://user-images.githubusercontent.com/16799094/33127966-f621d736-cf8a-11e7-914f-d04b1c947615.png)

@gplssm and @nesnoj: Any ideas how to solve this?

**Comment by ulfmueller** [comment]
maybe oemof.db is not installed on the server...

**Comment by ulfmueller** [comment]
well, pip freeze says that 'oemof.db==0.0.5' is installed...

**Comment by nesnoj** [comment]
If I'm not mislead, the package structure changed since 0.0.5.
Might be good to give it a try with the recent version.. ;)

**Comment by gplssm** [comment]
See [here](https://github.com/openego/eDisGo/issues/78) how I resolved the issue temporarily in eDisGo.

**Comment by IlkaCu** [comment]
Installing oemof.db==0.0.4 worked out.

**Comment by nesnoj** [comment]
Sorry, I mixed up oemof with oemof.db. Ignore my comment,,
