### ISSUE TITLE
Generators without buses

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#198]
As already described in issue #170 some generators (currently two) are not assigned to any bus. This leads to problems in the powerflow calculations. 
![grafik](https://user-images.githubusercontent.com/16799094/33611843-07fe7046-d9d0-11e7-9b32-9caf323c5a62.png)

I will version the current data set as v0.3.0 - including the described bug. Afterwards I am planning to delete those two power plants from the model_draft to queck if this solves the problems in the power flow calculations.

**Comment by IlkaCu** [comment]
This issue was caused by missing geometries of the mentioned power plants in the data set created by the preprocessing. 
For version v0.3.0 this problem was fixed manually. For the following release we should try to get to the bottom of this problem.

**Comment by IlkaCu** [comment]
Those two offshore generators are located outside the polygons used for the [assignment to the associated bus. ](https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_otgid.sql#L37-L53). The polygons need to be adjusted accordingly.
![grafik](https://user-images.githubusercontent.com/16799094/36840700-38cc2114-1d46-11e8-8501-256cbe14caf9.png)

**Comment by IlkaCu** [comment]
@ClaraBuettner: Could you adjust the polygons to make sure that also the mentioned offshore wind parks are automatically assigned to one of the designated substations?

**Comment by ClaraBuettner** [comment]
I updated the polygons in branch feature/adjust_offshore_polygones. All polygones in the Noth Sea are bigger and don't overlap anymore to avoid new problems.

**Comment by IlkaCu** [comment]
Great! Would you please create a pull request for this branch?
