### ISSUE TITLE
Control set in powerflow not complete

### ISSUE THREAD

**Issue by lukasoldi** [openego/data_processing#199]
In case of p_nom = 50 MW, no control is set to a generator. In the new data version this occurs 6 times.

https://github.com/openego/data_processing/blob/06c28ca09aa2242d1e6b0ecf294f6be72d4da3e3/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_generator.sql#L204-L210

**Comment by IlkaCu** [comment]
I can fix the bug in the model_draft data set temporarily and correct the code for the next release. Would that be okay for you?

**Comment by lukasoldi** [comment]
Absolutely, thank you!

**Comment by IlkaCu** [comment]
@IlkaCu: Bug fix needs to be implemented in the code for release v0.3.1

**Comment by IlkaCu** [comment]
I fixed this bug in the dev branch: 4e34b70a37fe0e8c99f3d533b06932bca79afbf2
