### ISSUE TITLE
Transform yEd diagrams to BPMN

### ISSUE THREAD

**Issue by tillmo** [openego/data_processing#2]
start with file Methodik_Verbrauchsverteilung_AP2.6_160222_RLI.graphml (see email from April 21, 14:34h).
Build a data-oriented ad-hoc process BPMN diagram, see p.63 of http://www.omg.org/news/meetings/workshops/soa-bpm-mda-2006/00-T4_White.pdf

**Comment by apoorva-ovgu** [comment]
converted files can be found in the draft_branch under data_processing/bpmn/
