### ISSUE TITLE
on which branch are we working now master  or refactor/oedb-restructuring_v0.2 ?

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#20]
I am confused on which branch we are working now. I like to work in /dataprocessing/sql_snippets/

**Comment by Ludee** [comment]
Depends on what you work on!
When you adjust to the "new" oedb structure you MUST use v0.2.
When you fix bugs in v0.1 you should make these HOTFIXES in both (Master and v0.2).
If you add new features use v0.2.

-> Master should always be stable and running!

**Comment by wolfbunke** [comment]
thanks ludwig for your quick reply! I close this ticket now.

**Comment by Ludee** [comment]
@jong42

**Comment by jong42** [comment]
The script for grid and ont generation ( process_eGo_lv_grid_multiple.py )  lies in the refactor/oedb-restructuring_v0.2 branch, the script for lv grid district generation

(process_eGo_lv_grid_districts.sql ) in the master branch... am I supposed to move both scripts in one branch?

 

 

Tel: 0152 33739616
Mail: jonasguetter@gmx.de

 
 

Gesendet: Montag, 30. Januar 2017 um 15:23 Uhr
Von: Ludee <notifications@github.com>
An: openego/data_processing <data_processing@noreply.github.com>
Cc: jong42 <jonasguetter@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [openego/data_processing] on which branch are we working now master or refactor/oedb-restructuring_v0.2 ? (#20)


@jong42

**Comment by Ludee** [comment]
Removed your personal info.
if it is working with the v0.2 structure (model_draft), it should be in the refactor branch.
so yes

**Comment by nesnoj** [comment]
@jong42 I added license headers for your scripts in the refactor branch (see https://github.com/openego/data_processing/issues/34#issuecomment-277446047), please include them resp. insert new ones when moving your scripts..
