### ISSUE TITLE
Existing storages differ in p_min_pu_fixed

### ISSUE THREAD

**Issue by lukasoldi** [openego/data_processing#200]
Existing storages in the new version have different values for p_min_pu_fixed. They should be (or default to) -1 and not 0. I queried like this:

`SELECT count(*) FROM grid.ego_pf_hv_storage WHERE scn_name = 'Status Quo' AND version = 'v0.3.0' AND p_min_pu_fixed = -1 AND source = 11;`

and found 42 storages with p_min_pu_fixed = 0 and 4 storages with p_min_pu_fixed = -1 (for SQ and NEP). In 'eGo 100', there are some storages added which results in 30 items with p_min_pu_fixed = -1.

**Comment by IlkaCu** [comment]
I will leave this issue open until I can verify if this bugfix solves the problem completely.
