### ISSUE TITLE
Orphaned and outdated branches 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#202]
Currently the DP repository includes 22 branches. As I'd like to clear the repository a bit, orphaned and outdated branches need to be identified and deleted. 
The following lists includes all branches which didn't show any activity recently and the last person updating it. If you are mentioned here, please have a look if the named branch is obsolete or not. Maybe some of those branches need to be merged into the dev. Mark the branch accordingly in this issue. Later on I will delete all obsolete branches. 

**draftBranch**  @apoorva-ovgu   
- [ ] obsolete 
- [ ] still needed
- [ ] needs to be merged (who is responsible?)

**features/rea_log** @wolfbunke @Ludee 
- [ ] obsolete 
- [ ] still needed
- [ ] needs to be merged (who is responsible?)

**features/fix_lvgd_peak_load_calculation** @gplssm  - this one is already merged 
- [ ] obsolete 
- [ ] still needed
- [ ] needs to be merged (who is responsible?)

**Comment by wolfbunke** [comment]
I checked my branches and all of them can be deleted because those changes are already implemented or obsolete.

**Comment by lukasoldi** [comment]
Me too, thanks for this, I like these clean-ups :)

**Comment by ulfmueller** [comment]
I am not sure what the branch bugfix-industry-load was about (The name sounds a bit like that it has to do with work from @IlkaCu). It is so old I would say it is obsolote.
