### ISSUE TITLE
Update values in demand.ego_demand_federalstate

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#204]
Some statistical offices updated their data on the electricity consumption per federal state. In case of Schleswig-Holstein significantly. 
Therefore I'd like to update our numbers in tables demand.ego_demand_federalstate.

**Comment by BartelsJ** [comment]
Further I recognized unit mistakes (TJ -> GWh) in demand.ego_demand_federalstate for the columns electrical consumption of households and the tertiary sector (industry is correct). See below the to-be-updated values in GWh for 2011. 

For some states the bundled information of households and tertiary sector is given. To separate these the percentage values of 12.5% (households) and ~15.278% (tertiary sector) are used. Can someone explain this assumption please? (literature?)

- Baden-Württemberg (Household: 4762; Tertiary: 5820)
- Bayern (H: 5947; T: 7268)
- Bremen (H: 276; T: 337)
- Hessen (H: 2928; T: 3578)
- Saarland (H: 463; 566)

**Comment by IlkaCu** [comment]
> Can someone explain this assumption please? (literature?)

In case the electricity consumption of households and tertiary sector are not declared separately we assumed that households account for 45% and tertiary sector for 55% of the accumulated demand. This values are based on an interview with an employee of the statistical office Bremen.

**Comment by BartelsJ** [comment]
Ah, ok. I didn't know this assumption and tried to calculate these percentage values myself (12.5% and ~15%). But since 45% and 55% divided by 3.6 (TJ to GWh) result in the mentioned percentage values of 12.5% and ~15% you already took the unit change into account. Sorry for that. No work to be done.
