### ISSUE TITLE
New table line expansion costs

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#209]
In the new created table [model_draft.ego_grid_line_expansion_costs](https://github.com/openego/data_processing/commit/cf4d56a772cb2d2adb59ceb1631cc7d3db71fda3) you can find our cost assumptions.

As an idea, by using component, voltage_level you get the cost parameter by source and unit.  For the PyPSA conform units the values needs to be calculated in MWkm and added as new entry source = 'NEP 2035' or 'eGo 100' with the new unit.  This calculation can easily added to the Python script of the preprocessing. With this DB structure the original and calculation is quite transparent.  

What is you opinion to this structure ? @ulfmueller @ClaraBuettner

**Comment by wolfbunke** [comment]
see also [Ticket #9](https://github.com/openego/eGo/issues/9) in eGo

**Comment by ClaraBuettner** [comment]
Did you implemented costs in €/km for lines and € for trafos? 
In my calculation, I assume an s_nom for the costs of lines in the NEP to have get the €/MVA/km. I would add a cloumn with this data, so there are assumed costs that can be easily used for pypsa. 
The transformers and links already have an s_nom in the estimated NEP costs, so I would use this.

**Comment by wolfbunke** [comment]
Yes the original data of [investment_costs_of_grid_ measures.csv](https://github.com/openego/eGo/blob/dev/ego/data/investment_costs_of_grid_%20measures.csv) are already implemented. 

> In my calculation, I assume an s_nom for the costs of lines in the NEP to have get the €/MVA/km. I would add a cloumn with this data, so there are assumed costs that can be easily used for pypsa.

Thats's nice thank you!

> The transformers and links already have an s_nom in the estimated NEP costs, so I would use this.

Could you add this data as well? Because the in this table the costs are only per item/unit (Mio. €/Stück). Or do you mean that?

**Comment by ClaraBuettner** [comment]
Yes, I can add both, data for lines and transformers per MVA. 
But I think I should make a difference between estimated (for lines, where s_nom was not given) and given costs per MVA. So maybe I would implement the given data directly to your table and the estimated costs imn an SQL-script when I use it in the NEP-lines. Is that ok?

**Comment by wolfbunke** [comment]
yes, thanks!

**Comment by IlkaCu** [comment]
@wolfbunke: What's the status here? Does anything more need to be implemented or merged for v0.3.1?

**Comment by wolfbunke** [comment]
The table  model_draft.ego_grid_line_expansion_costs is updated and the data are stored. I can merge the changes tomorrow into the dev branch in the pre-processing folder .  

@ClaraBuettner do you have pushed your changes in one of our branches? If not, I can update my first scripts. 

As todo the table  model_draft.ego_grid_line_expansion_costs should be added to the versioning.

**Comment by wolfbunke** [comment]
I created a pull request in #228 with an update of the table structure and calculated data of @ClaraBuettner. I think this ticked can be closed after the merge and the adding to the [versioning script](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_versioning.sql).

**Comment by IlkaCu** [comment]
> the adding to the versioning script.

@wolfbunke: Is this already implemented? If not, who is responsible?

**Comment by wolfbunke** [comment]
no, its not. I thought it is on you list? If not, I can do it tomorrow, like you wish?
