### ISSUE TITLE
Do missing table name replacements

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#21]
Some replacements couldn't be done due to missing information
- [x] scenario.eGo_data_processing_clean_run in all files
- [x] [orig_destatis.ego_deu_loads_zensus](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/setup_zensus_population_per_ha.sql#L38) and more occurrences in this file
- [x] [orig_destatis.ego_deu_loads_zensus_cluster](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/setup_zensus_population_per_ha.sql#L123) and more occurrences in this file. Furthermore in:
  - [x] process_eGo_loads_melted.sql
- [x] [calc_ego_loads.ego_deu_loads_collect](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/process_eGo_osm_loads.sql#L10) and more occurrences in this file
- [x] [calc_ego_loads.ego_deu_loads_melted](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/process_eGo_loads_melted.sql#L318)
- [x] [orig_ego.ego_deu_loads_melted](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/process_eGo_loads_per_grid_district.sql#L37)
- [x] [i.e. orig_consumption_znes.temp_table](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/process_eGo_loads_per_grid_district.sql#L629-#L773) is not available in translation table and many other table names used in this commented section. Adapt table names or delete it.

**Comment by IlkaCu** [comment]
The highlighted code in [i.e. orig_consumption_znes.temp_table](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/process_eGo_loads_per_grid_district.sql#L629-#L773) seems to be a doubling to this:  [process_eGo_consumption.sql](https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/process_eGo_consumption.sql#L36-L157)

**Comment by Ludee** [comment]
I copied the code there to include the consumption in the MVGD table. I posted it at some point but nobody saw it. Delete it or use it to join scripts. I would prefer we reduce the number of tables and scripts.

_orig_destatis.ego_deu_loads_zensus_ is the census part of the MVLA. Could be renamed to somethig like _model_draft.ego_social_zensus_loads_ and ..._cluster.

One of the two _ego_deu_loads_melted_ is an old one. Not sure which one. It's a temporal table to create MVLA. Most of these tables are just for validation and can be dropped in the end of the process.

**Comment by IlkaCu** [comment]
> I copied the code there to include the consumption in the MVGD table. I posted it at some point but nobody saw it. Delete it or use it to join scripts. I would prefer we reduce the number of tables and scripts.

For now I would suggest to comment this part of the code out.

**Comment by gplssm** [comment]
Thanks for input!
But there are still some questions left in order to be able to start v0.2. I'll be more precise

- [ ] could you provide a schema/table name for orig_consumption_znes.temp_table? @IlkaCu 
- [ ] Please give me names for the following tables for v0.2 @Ludee 
 - [ ] [orig_ego.ego_deu_loads_melted](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/process_eGo_loads_per_grid_district.sql#L37)
 - [ ] [calc_ego_loads.ego_deu_loads_collect](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/process_eGo_osm_loads.sql#L10)
 - [ ] [calc_ego_loads.ego_deu_loads_melted](https://github.com/openego/data_processing/blob/3e7d2f86684296911bc955427ffa683f72d79064/dataprocessing/sql_snippets/process_eGo_loads_melted.sql#L318)
- [ ] scenario.eGo_data_processing_clean_run shall we keep this table to log progress of _data processing_? @Ludee @MGlauer

**Comment by Ludee** [comment]
calc_ego_loads.ego_deu_loads_collect -> model_draft.ego_demand_load_collect
orig_ego.ego_deu_loads_melted + calc_ego_loads.ego_deu_loads_melted
-> model_draft.ego_demand_load_melt
It looks like there are two different versions of this table. This is a major bug in the calculation.

**Comment by Ludee** [comment]
Checklist shows that we have finished all but the implementation of the scenario log. As far as I see it is used a lot and can also be simplified by calling the function #37.
