### ISSUE TITLE
solar and wind p_max_pu seem too low [eGo 100 scenario, v0.3.0]

### ISSUE THREAD

**Issue by ulfmueller** [openego/data_processing#215]
I reckonized that the new 100% scenario has very low solar and wind potentials. Is that plausible?
Please check the p_max_pu of wind and solar and compare it with the p_nom.
See here:
[curtailment_solar.pdf](https://github.com/openego/data_processing/files/1706509/curtailment_solar.pdf)
[curtailment_wind.pdf](https://github.com/openego/data_processing/files/1706510/curtailment_wind.pdf)

Due to refactoring of timeseries creation by @MarlonSchlemminger this might be solved anyhow.

Anyhow for the ongoing calculations it would be good to know how 'reliable' that eGo 100 scenario is concerning wind and solar potential.

**Comment by MarlonSchlemminger** [comment]
I am currently executing the new calculation and will be able to give information if this changes this afternoon or tomorrow.

**Comment by ulfmueller** [comment]
@MarlonSchlemminger Did you check if this problem is solved? I would check it but if you have done it already I would be interested in the results!

**Comment by MarlonSchlemminger** [comment]
Yeah I've checked that and it is solved. I checked it with the following code:
`SELECT b.scn_name, sum(b.feedin)/c.p_nom AS p_max_pu
FROM (
	SELECT a.scn_name, sum(a.feedin) AS feedin 
	FROM (
		SELECT 
		scn_name,
		rn,
		elem*p_nom AS feedin
		FROM 
			(SELECT 
			gen.scn_name,
			p_nom,
			p_max_pu 
			FROM grid.ego_pf_hv_generator_pq_set AS ts,
			model_draft.ego_grid_pf_hv_generator AS gen
			WHERE gen.generator_id = ts.generator_id
			AND gen.generator_id < 200000
			AND source = 12
			AND version = 'v0.4.2'
			) t,
			unnest(t.p_max_pu) WITH ORDINALITY x(elem, rn)
		) a
	GROUP BY scn_name, rn
	ORDER BY scn_name, rn
	) b,
	(
	SELECT 
	scn_name,
	sum(p_nom) AS p_nom
	FROM grid.ego_pf_hv_generator
	WHERE source = 12
	AND generator_id < 200000
	AND version = 'v0.4.2'
	GROUP BY scn_name
	) c
WHERE b.scn_name = c.scn_name
AND b.scn_name IN ('Status Quo', 'NEP 2035', 'eGo 100')
GROUP BY b.scn_name, c.p_nom;`

and then change source to 12, 13 or 17 for solar, wind onshore and wind offshore (attention: you have to change the source id TWICE in the code).

**Comment by MarlonSchlemminger** [comment]
And here are the results.
Solar:
![flh_solar](https://user-images.githubusercontent.com/22960010/42885104-61dea668-8aa0-11e8-94b4-127888ca71eb.PNG)

Wind Onshore:
![flh_onshore](https://user-images.githubusercontent.com/22960010/42885167-8ef5c7a8-8aa0-11e8-88da-1f798e05b17c.PNG)

Wind Offshore
![flh_offshore](https://user-images.githubusercontent.com/22960010/42885207-a7cd8e28-8aa0-11e8-8d5c-d7d73d4801d1.PNG)

**Comment by ulfmueller** [comment]
Nice job! Thx!!
