### ISSUE TITLE
Assignment of otg_id for wind offshore plants

### ISSUE THREAD

**Issue by lukasoldi** [openego/data_processing#223]
I am trying to identify certain offshore generators in the hv powerflow data through the otg_id, but cannot really succeed. I found this part here where otg_id is manually assigned to OWP, but only for the Status Quo scenario. Does this in the end also apply for other scenarios? 

https://github.com/openego/data_processing/blob/2dd6276f84efa84817ab2dca99e068e8a4ed3945/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_otgid.sql#L37

**Comment by IlkaCu** [comment]
The method of 'manually' assigning the otg_id to OWP applies for all three scenarios as the table model_draft.ego_dp_supply_res_powerplant contains all RE generators of all scenarios.

**Comment by lukasoldi** [comment]
Alright, thanks - I got it :)
