### ISSUE TITLE
Metadata feedback

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#23]
There is good feedback on the metadata from the openmod BoG:

Adjust metadata template with:

- [x] Divide **Spatial resolution** into **Spatial** with **Resolution** and **Extend**
- [x] Divide **Licence** into **Name** and **URL**
- [x] Rename **ToDo** into **Notes**
- [x] Compare with metadata from OPSD and other sources like OKFN

**Comment by Ludee** [comment]
Feedback pushed in refactor branch. Please update metadata using the template [here](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/data_documentation/documentaion_on_table_example.sql).

Last checkpoint should be done by ZNES (@wolfbunke).

**Comment by wolfbunke** [comment]
Ok, I am working on the workshop on Tuesday. After that, I will do it.

**Comment by Ludee** [comment]
Compared our system with [OPSD](http://data.open-power-system-data.org/renewable_power_plants/2016-10-21/datapackage.json) and [OKFN (Frictionless / Data Packagee)](http://specs.frictionlessdata.io/data-packages/) and a [CKAN](https://github.com/fraunhoferfokus/ogd-metadata/blob/master/OGPD_JSON_Schema.html) metadata.

[see comparision](https://docs.google.com/spreadsheets/d/1vAYEIqhf4_q4mZ7J2KomSCfOTDsb0mHozxK-LT0FQjU/edit#gid=1863602509)

In order to harmonize the metadata with OPSD and other databases we should follow the guidelines.
While working with the metadata in the data processing I also added my experience to minimize the entries to avoid boring work!
So I removed some entries, renamed some entries and did some restructuring.

I would suggest to use this new metadata template for v0.2 of the data processing and new tables but leave the old tables as there are because of time issues.
 
Feel free to give feedback about the new version

**Comment by lukasol** [comment]
Metadata will be updated according to new version in release 0.3.

**Comment by Ludee** [comment]
I came across the point of removing "real names" and email in GitHub.
This is part of the metadata in _changes_.

How we adapt these opposing guidelines and examples?
Of course there is the freedom of choice for everybody, but I would like to have some fitting working examples.

Considering:
openmod-wiki **username** = OEP **username** and **real name**
GitHub **username**
oedb metadata **name** and **email**

**Comment by Ludee** [comment]
The lawyer suggested to add the license to the sources in the metadata.
see commit f38e327b1bf8dd6461c7ef1a2d01deda6b63573d

The question of using names is in a new issue  #65

**Comment by Ludee** [comment]
we forgot the copyright in source and license. New version v1.3

**Comment by wolfbunke** [comment]
ok, thanks
