### ISSUE TITLE
Implausible values for energy sums using timeseries (wind)

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#230]
I'm using the timeseries from `grid.ego_pf_hv_generator_pq_set ts` (dp v0.3.0, same results with current model_draft tables). For a nominal power of a WEC of X MW I expect an annual energy sum of roughly X MW*1500 h.

I get very different results using
```
  SELECT
    typ.name AS generation_type,
    gen.p_nom AS p_nom_MW,
    gen.p_nom * 1500 AS p_nom_1500_MWh,
    (SELECT SUM(p) FROM UNNEST(ts.p_set) as p) AS p_set_sum_MWh,
    (SELECT COUNT(p) FROM UNNEST(ts.p_set) as p) AS p_set_count,
    (SELECT SUM(p) FROM UNNEST(ts.p_set) as p) / (gen.p_nom * 1500) AS p_nom_p_set_ratio
  FROM  grid.ego_pf_hv_generator gen,
        grid.ego_pf_hv_generator_pq_set ts,
        grid.ego_pf_hv_source typ
  WHERE gen.generator_id = ts.generator_id::bigint
	AND ts.scn_name = gen.scn_name
	AND gen.scn_name = 'Status Quo'
	AND gen.source = typ.source_id
	AND typ.name = 'wind'
	AND gen.version = 'v0.3.0' AND typ.version = 'v0.3.0' AND ts.version = 'v0.3.0'
  ORDER BY gen.bus
  LIMIT 10;
```

generation_type|p_nom_mw|p_nom_1500_mwh|p_set_sum_mwh|p_set_count|p_nom_p_set_ratio
--|--|--|--|--|--
wind|5.06|7590|19649.6364633811|8760|2.58888490953638
wind|0.003|4.5|11.6499820929137|8760|2.58888490953637
wind|0.0143|21.45|55.5315813095577|8760|2.58888490953649
wind|4.3|6450|16698.3076665096|8760|2.58888490953638
wind|3.6|5400|13979.9785114965|8760|2.58888490953638
wind|8.486|12729|32953.9160134896|8760|2.58888490953646
wind|1.6|2400|6213.32378288752|8760|2.58888490953647
wind|4.6|6900|17863.3058758015|8760|2.58888490953645
wind|3|4500|11649.982092914|8760|2.58888490953644
wind|96.91|145365|376333.254874759|8760|2.5888849095364

**Interestingly, there seems to be a constant ratio of 2.58888 between the two energy sums! (cf. column `p_nom_p_set_ratio`)**

How come?
(note that it is obviously not related to #220)

For solar the results seem to be plausible.

By the way: Why is column `generator_id` of `grid.ego_pf_hv_generator_pq_set` a varchar and not a bigint as in `grid.ego_pf_hv_generator`?

**Comment by MarlonSchlemminger** [comment]
I mentioned in #225 that full load hours for wind are too high on average and I am currently working on it to bring them down a little bit (going to open a ticket soon). I assume that the generator(s) you looked at is an offshore turbine, which is why you have 3600 full load hours (2.588*1500). If you don't limit your query to 10 generators you should find different ratios. From what I remember we are currently in a range between 500 FLH up to 6000 FLH for some offshore turbines.

**Comment by IlkaCu** [comment]
> By the way: Why is column generator_id of grid.ego_pf_hv_generator_pq_set a varchar and not a bigint as in grid.ego_pf_hv_generator? 
I mentioned this in issue #211 and will fix in release v0.3.1

**Comment by nesnoj** [comment]
> I mentioned in #225 that full load hours for wind are too high on average and I am currently working on it to bring them down a little bit (going to open a ticket soon). I assume that the generator(s) you looked at is an offshore turbine, which is why you have 3600 full load hours (2.588*1500). If you don't limit your query to 10 generators you should find different ratios. From what I remember we are currently in a range between 500 FLH up to 6000 FLH for some offshore turbines.

Thanks for your answers!
@MarlonSchlemminger When I use turbines for 3 Landkreise in Saxony-Anhalt, I get the same ratio of 2.588.. for all generators using
```
  SELECT
    typ.name AS generation_type,
    gen.p_nom AS p_nom_MW,
    gen.p_nom * 1500 AS p_nom_1500_MWh,
    (SELECT SUM(p) FROM UNNEST(ts.p_set) as p) AS p_set_sum_MWh,
    (SELECT COUNT(p) FROM UNNEST(ts.p_set) as p) AS p_set_count,
    (SELECT SUM(p) FROM UNNEST(ts.p_set) as p) / (gen.p_nom * 1500) AS p_nom_p_set_ratio,
    ts.p_set
  FROM  grid.ego_pf_hv_generator gen,
        grid.ego_pf_hv_generator_pq_set ts,
        grid.ego_pf_hv_source typ
  WHERE gen.generator_id = ts.generator_id::bigint
	AND ts.scn_name = gen.scn_name
	AND gen.scn_name = 'Status Quo'
	AND gen.source = typ.source_id
	AND typ.name = 'wind'
	AND gen.version = 'v0.3.0' AND typ.version = 'v0.3.0' AND ts.version = 'v0.3.0'
	AND gen.bus IN (SELECT bus_id FROM model_draft.wn_abw_ego_pf_hv_bus)
  ORDER BY gen.bus;
```
(`model_draft.wn_abw_ego_pf_hv_bus` holds the 29 buses of the region)

The total of annually generated energies of all WECs with 1500 FLH `p_nom_1500_MWh` fits quite well with related publications. As the installed capacity are in line with those publications too, 1500 FLH seem to be appropriate.
In the original generator MVIEW `supply.ego_dp_res_powerplant_sq_mview` the WECs are tagged as "wind_onshore".

This might be a bug in the feedin calculation part?

I see you're working on this in #231 and #225, that's great! But for me it would be very helpful to quickly get an idea of what's wrong here. For my purposes I could simply adjust the values to get in line with statistical values but it's worth to check whether it's a DP bug or not..

**Comment by MarlonSchlemminger** [comment]
There were some changes made to the feedin which I thought would be included in v0.3.0 but it doesn't look like they went through. @IlkaCu can you call me back at 0461/79509480 as soon as you read this?

**Comment by IlkaCu** [comment]
I'm in a meeting for the whole day. Can we talk next week? I'm pretty sure that the v0.3.0 release will still take a little while.

**Comment by MarlonSchlemminger** [comment]
Ah this isn't the relase yet which is on the oedb. Sorry, I don't really know how this process with releases works. 
@nesnoj This means there will be changes to the feedin coming soon. You can take a look at #206 in the meantime. Just a quick explanation: The p_set which is currently on the oedb is the **national average** for all wind turbines both on- and offshore. It is the same for all German wind turbines, which is is why it is so high.

**Comment by nesnoj** [comment]
Ok thank you!
