### ISSUE TITLE
Parameters to adjust timeseries for wind generation

### ISSUE THREAD

**Issue by MarlonSchlemminger** [openego/data_processing#231]
Our numbers for wind generation from both on- and offshore are currently too high. Onshore sits at 2600 FLH and offshore at 4300. According to the Fraunhofer Institut, onshore should be around 1700 and offshore around 3500 FLH. We are already working with correction factors to calculate the feedin and the simplest method would be to change the correction factor until we get realistic FLH. We have three other parameters we could change:

- turbine type: I find it interesting to use two different turbine types depending on the wind speed, like Schwachwindanlagen and Starkwindanlagen. Currently we only use a Starkwindanlage. but I found a generator in the generatorlist of the windlib which is classified as a Schwachwindanlage by the producer. I do think that in the context of the whole project to determine grid extension measures, the wind production should be as realistic as possible, because it has a big influence on the grid. Using Schwachwindanlagen would generally increase the production in southern Germany and therefore decrease the pressure on the grid. We could implement it by setting a certain threshold for the average wind speed. If the wind speed is above the threshold we use Starkwindanlagen, if the wind speed is below the threshold we use Schwachwindanlagen. 

- hub height: We currently use the same hub height and rotor diamater for every scenario. There are multiple studies on how both parameters are expected to develop in the future (e.g. [https://books.google.de/books?id=m35gCgAAQBAJ&pg=PA110&lpg=PA110&dq=entwicklung+des+rotordurchmessers+nabenh%C3%B6he&source=bl&ots=B6X2ohZ-fC&sig=QW-KRKijW1N40msJFcYmFTxKef4&hl=de&sa=X&ved=0ahUKEwiLvIK_o9nLAhVElw8KHeg9B9oQ6AEITDAI#v=onepage&q=entwicklung%20des%20rotordurchmessers%20nabenh%C3%B6he&f=false](url) ) and we could use this information to make our future scenarios more realistic by changing hub height and rotor diameter depending on the scenario. 

- rotor diameter: same as hub height

What are your opinions?

**Comment by MarlonSchlemminger** [comment]
I took a different approach and implemented something similar to what Mario Kropshofer did a while ago. This only affects onshore turbines, offshore turbines remain untouched. All wind turbines in the model are grouped into one of seven power classes with a lower and upper limit for the capacity. For each power class, the most used turbine (based on model_draft.ego_supply_renewable_bnetza_full_attribute) is identified and later used as a reference turbine. The information about the power classes and the turbines used in each class is stored in model_draft.ego_power_class. To simplify the process, wind_offshore and solar are assigned to power class 0, which has no meaning, as there is only one power class for solar and wind_offshore. 

For each weather cell, the feedin timeseries is calculated seven times, once for each power class, which means it is calculated with seven different wind turbines, and saved into ego_renewable_feedin. Each renewable generator in model_draft.ego_supply_pf_generator_single is assigned to one power class as well and timeseries are assigned to each generator based on power class and w_id (compared to only based on w_id before).

The evaluation showed that generation in southern Germany increased, whereas generation in all other parts of Germany slightly decreased.

On top of that, an onshore correction factor of 0.6 (!) was introduced. This means that wind onshore generation was almost halved!

**Comment by nesnoj** [comment]
Did you verify the cumulative feedin for 2011 with other sources? (e.g. [here](https://www.foederal-erneuerbar.de/landesinfo/bundesland/D/kategorie/wind/auswahl/176-stromerzeugung_aus_w/versatz/2/#goto_176))

**Comment by MarlonSchlemminger** [comment]
What I evaluated was the difference in full load hours for each federal state between the new method and the old one and then adjust the correction factor to get realistic full load hours for whole Germany (http://windmonitor.iee.fraunhofer.de/windmonitor_de/3_Onshore/5_betriebsergebnisse/1_volllaststunden/). We didnt't have time to compare each federal state with real numbers.

**Comment by nesnoj** [comment]
ok.
There's no such table `model_draft.ego_power_class`

**Comment by MarlonSchlemminger** [comment]
The name might have changed slightly, @wolfbunke ?, I can't connect myself to the oedb currently.

**Comment by wolfbunke** [comment]
The table ` model_draft.ego_power_class` online.
