### ISSUE TITLE
Info: update of new database tables model_draft.ego_renewable_feedin

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#235]
The new table model_draft.ego_renewable_feedin includes the renewable time series for solar, wind_offshore and wind_onshore for the weather year 2011 and the defined weather point of the open_Ego scenarios.

![coastdat2](https://user-images.githubusercontent.com/14540685/37403129-10cab17e-278e-11e8-9e7d-c7e5a89d0188.png)

The script can be found under: https://github.com/openego/data_processing/tree/dev/preprocessing/python_scripts/renpass_gis/simple_feedin and https://github.com/openego/data_processing/blob/f66204e6a4a8831bb0f5a5098d7bf5026bdee06d/preprocessing/sql_snippets/ego_simple-feedin_per_scenario.sql

**Comment by MarlonSchlemminger** [comment]
Table ego_renewable_feedin slightly changes once again with the new release of the DP. 
A new column named "power_class" was added with numbers between 0 and 7. For wind_offshore and solar, power class is always 0 (which has no definition, because power classes only affect wind_onshore). For wind_onshore, each w_id has 7 entries, one for each power_class between 1 and 7. For further information, please read into #231 .

**Comment by wolfbunke** [comment]
We updated the table ` model_draft.ego_renewable_feedin` the new structure and table can be found under: `model_draft.ego_renewable_feedin_v031`. Please have a look and give your comments. After your approval I will delete the old model_draft.ego_renewable_feedin and rename model_draft.ego_renewable_feedin_v031 back before the data process run reaches the generator timeseries scripts. 

An further description can be found unter: 
sftp
open_eGo/Netzplanungsinstrument_eGo/Erzeugung/Wind.pdf

**Comment by nesnoj** [comment]
Could u please adjust the permissions? Thanks

**Comment by wolfbunke** [comment]
done

**Comment by wolfbunke** [comment]
The table  ego_renewable_feedin is has now a version number and can be found in the schema supply.

- supply.ego_renewable_feedin
- supply.ego_power_class (parameter of wind)

**Comment by wolfbunke** [comment]
I will close this issue.
