### ISSUE TITLE
data_processing repo discussion

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#24]
We started with the focus of data preparation but reached the level of calling it a "real model".
Following questions have to been answered:

- [x] Is the name of the repository still suitable?
- [x] Is it part of the **ego-tool** that is written in the proposal?
- [x] Do we still want to use this particular name?
- [x] If so, is the "data_processing" part of it?

Now my opinion:
Data_processing was a working title. We are publishing papers about it and it's great collaborative work.
The geo-coding is the foundation of the grid optimization and therefore part of it!
Let's start calling it **ego** or something similar and also rename the repo. Then restructure the folders to different parts of it: TP, GD, LA, DEA, DINGO and others.

**Comment by lukasol** [comment]
I consider data-processing as a part of the ego tool. We could thus rename the whole thing to something ego-related, but generally data-processing seems to be a fitting name.

Another restructuring of the repo and its folders should be avoided or at least shifted to some nice-to-have time in the future: I would really like to finish this whole data-processing topic and proceed with grid optimization, i.e. the **application** of all what has been developed so far.

**Comment by Ludee** [comment]
Thanks for your feedback @lukasol 
I agree with you that a restructure of the repo is not urgent and the development of the grid optimization is more important. I just want to start the discussion about the design and content of the ego-tool already now:
data processing is so general that it fits everything. Until now it is all connected to consumption allocation and the existing grid components (substations). That's a little bit more specific.

I don't have the overview to see all parts of the ego-tool planed in open_eGo. Does it exist in one of the presentations? It could help to structure the repo and database.

**Comment by ulfmueller** [comment]
Late, but here are some answer from my side:

- Is the name of the repository still suitable?
Yes, i think so.
- Is it part of the ego-tool that is written in the proposal?
it characterizes the work of work package 2, so the setting up all exogenic parameters. It sets up the data base in order to test the ego tools as well as making it possible to generate results for certain scenario settings
- Do we still want to use this particular name?
yes. if you would name it "ego" you would have to restructure the entire group and not just the repo itself. I think now would not be the time to do so.

Definitely there will be changes going towards the development of an big integrated ego tool. But i dont see that right now and not within this repo.

**Comment by Ludee** [comment]
> Definitely there will be changes going towards the development of an big integrated ego tool. 

This is why I started this issue because I think so too. The so called "data processing" was not defined anywhere yet. As I understand it it is only data preprocessing for the ego-tool(s). It will be a separate python lib and therefore should have a name that fits. This is the topic of this issue!

> But i dont see that right now and not within this repo.

The structure of the ego-tool will affect this issue and then there will be even less time and people to adapt things. 
Because I put a lot of my time and efforts into this repo I like to look ahead. Perhaps there is no time to decide and adapt the structure now but why do you both react in such a passive way about the discussion?

**Comment by Ludee** [comment]
As decided today the repo restructuring will be part of a release v0.3.

On part of it will be the renaming of snippet scripts.
It follows the ego naming convention and looks something like this:

<program>_<main schema>_<main function>
ego_scenario_log_setup.sql
