### ISSUE TITLE
Multiple generators without rea_geom_new 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#242]
Analyzing data from table supply.ego_dp_res_powerplant and model_draft_ego_dp_supply_res_powerplant shows that 154718 generators are lacking information on rea_geom_new. 
This applies to generators from all sources and all voltage levels which are spread evenly all over Germany. 

![grafik](https://user-images.githubusercontent.com/16799094/37898113-3e3d2430-30e8-11e8-8dd1-811b7acee97f.png)

@Ludee: Any ideas why this happens and how to fix this bug?

**Comment by Ludee** [comment]
I will have a look later this day. But the timing is bad, I will be on holiday for 2 weeks starting tomorrow. I can not promise to fix it today, my workload is too big atm.
But this def. falls into my purview ;)

**Comment by IlkaCu** [comment]
As I didn't hear anything from Ludee I assume he didn't manage to have a closer look. @wolfbunke Do you have any ideas how to fix this bug? 
If not I would suggest as a hotfix to fill all empty cells of 'rea_geom_new' with entries from column 'geom'.

**Comment by wolfbunke** [comment]
Due to saving time to the release I agree with your fix. Let's use the column comment to add the information that the rea_geom _new  is from geom.
Like:
```
Update table..
   set rea_geom_new = geom,
   comment = comment || 'add original geom to rea_geom_new' 
Where rea_geom_new is null;
```
And  create a ticket for a revision of the rea allocation.

**Comment by wolfbunke** [comment]
Between `'rea/ego_dp_rea_results.sql'` and `ego_dp_powerflow_assignment_otgid.sql` maybe at the beginning of the `ego_dp_powerflow_assignment_otgid.sql` file in order to save a additional file ?

**Comment by nesnoj** [comment]
You gonna start the run today?
If not, I'd like to give @IlkaCu idea a quick review..

**Comment by IlkaCu** [comment]
I won't start the run before tomorrow - more likely Thursday.

**Comment by IlkaCu** [comment]
> If not, I'd like to give @IlkaCu idea a quick review..

@nesnoj : Feel free to share your thoughts and comments. ;-)

**Comment by nesnoj** [comment]
It reveals that in `Status Quo` only 2.7% of the RES genos are affected but 39.5% (37.5GW) of entire RES capacity. Without EHV/HV level (only v_level 5..7 where geoms are crucial), this results in 13.7% (13 GW) This is quite a lot.

This one 
```
SELECT scenario, generation_type, generation_subtype, rea_flag, count(*), round(sum(electrical_capacity)/1000) as cap_MW
  FROM supply.ego_dp_res_powerplant
  WHERE rea_geom_new is NULL AND version='v0.3.0' AND voltage_level in (5,6,7)
  GROUP BY scenario, generation_type, generation_subtype, rea_flag
  ORDER BY scenario, generation_type, generation_subtype, rea_flag;
```
reveals that a large share of the affected datasets could not be allocated in their original allocation methods (`rea_flag`) (e.g. M1-1) and also the fallback (e.g. M4_rest) did not work...right @wolfbunke @Ludee?

The allocation method [bpmn](https://github.com/openego/data_processing/blob/dev/bpmn/archiv/ego_rea.graphml):
![rea_alloc_methods](https://user-images.githubusercontent.com/15910173/37989836-ca1d51ba-3204-11e8-8424-30ab28bf69de.png)

**I know this is really annoying and takes some time to fix but not to fix means we have many REA which remains at their original (energymap's) position.
For the EHV/HV this might be acceptable but might a serious problem for the distribution grids.**
@boltbeard @gplssm
-> WEC, PV(ground mounted) and PV(roof mounted) remain located at the same position within on MVGD..

I'm wondering whether this is a new bug (didn't you update the REA genos recently, @wolfbunke?) or has it been there all the time? @Ludee

**Comment by wolfbunke** [comment]
I think one reason could be the additional ego 100 scenario which affects the rea script. @IlkaCu and me took a look into the versions and it happens earlier with about 35K as well.

**Comment by IlkaCu** [comment]
@nesnoj: Thanks for your comments and I definitely see your point. Unfortunately we neither have the capacity nor are we familiar enough with the REA scripts to find and fix this bug within a reasonable period of time. Ludee won't be available for the next two weeks. @nesnoj, @gplssm: Is there someone else at RLI familiar with the REA scripts? 
If not I see three different options: 

- Option 1: We postpone the DP debugging and clean run until Ludee fixed the bug. This would postpone the release for at least 3 weeks. 

- Option 2: We continue with the DP release including my suggested hotfix which fills empty rea_geom_new with the original geom. We document this in the release notes and a corresponding github issue for the following release. 

- Option 3: I start the release process with debugging and as we know by experience this will take a while. So it might be possible to include fixes for the described bug in a later state of the process. 

I would favor option 3 as I would not like to stop the whole release process for a couple of weeks from now on. What do you think?

**Comment by wolfbunke** [comment]
I would also favor option 3

**Comment by nesnoj** [comment]
Yes, I totally agree. Except @Ludee, none of us at RLI got the required in-depth knowledge to fix this. I favor option 3 as well.
In DINGO & eDisGo, `geom` is the fallback if `rea_geom_new` is missing ([eDisGo code](https://github.com/openego/eDisGo/blob/4c8902ea70c9ffe9cdcbfad8acaad6b56b778eaf/edisgo/data/import_data.py#L1612)). Hence, from eDisGo's perspective we do not need the hotfix.

**Go ahead with the release!**

Note: I'm wondering why this happens. If I'm not mistaken, there should be always be a spot to place RES in the fallback method if the first method fails.. If all spots (which are e.g. defined by the 500x500m grid) are "filled" with RES, the allocation should start over again from the first spot.. I guess we need help from @Ludee here..

**Comment by nesnoj** [comment]
@Ludee Any news here?

**Comment by IlkaCu** [comment]
@Ludee: As the DP debugging is going to reach the REA part soon, some new information corresponding this issue would be great.

**Comment by Ludee** [comment]
I did some simple checks to evaluate the dea without rea_geom_new.

Some (57792) of them were not considered because we didn't had methods for them (like hydro). new = old!

M4 has a BUG! [It is allocated to the wrong layer (out -> wpa)](https://github.com/openego/data_processing/blob/release/v0.4.0/dataprocessing/sql_snippets/rea/ego_dp_rea_m4.sql#L133). I will try to hotfix! 

Some (M5_rest) exist because there are more power plants than "free spots".
An Example MVGD:

`SELECT scenario, count(*)
  FROM supply.ego_dp_res_powerplant
  WHERE version='v0.3.0' AND subst_id = '1238'
  GROUP BY scenario
  UNION ALL 
  SELECT 'LATTICE OPTIONS', count(*)
FROM model_draft.ego_lattice_50m_la_mview
WHERE subst_id = '1238';
`
-> 3800 possible points in 50m lattice but 2550+3209+1020 powerplants!

**Comment by IlkaCu** [comment]
The DP reached the REA part. As I would like to continue the debugging, I'll continue with the REA scripts until M4. Meanwhile bugfixes for M5 could be implemented. Any objections?

**Comment by Ludee** [comment]
That is a difficult question. This is not a real bug but rather a limit of our method.
If there are more generators (PV) than roofs (free spots), the assumptions for e.g. "eGo 100" are too high and exceeds the potential. We can do a "bugfix" and simply increase the potential, but that should be discussed!?

**Comment by IlkaCu** [comment]
> We can do a "bugfix" and simply increase the potential, but that should be discussed!?

For us the simple hotfix which sets geom_new = geom for those generators which were not moved would be fine. But this might not apply for Dingo and eDisGo. From my point of view the RLI needs to decide whether to work on a further "bugfix" or not. I will continue with the release process of DP v0.4.0 nevertheless.

**Comment by Ludee** [comment]
I discussed a feasible solution with @gplssm 
We will copy the M5 method and have 2 generators per location.
I'm not sure if this can happen in this version.
Will there be a recent 0.4.1?

**Comment by nesnoj** [comment]
> M4 has a BUG!

Is this one fixed now?

> Some (M5_rest) exist because there are more power plants than "free spots".

We need a solution here - even a redistribution of "left over" RES to already "filled" spots is better than leaving them where they are!

I guess the DP has passed the REA part by now? Is it possible to add these adjustments afterwards and update the columns? (`rea_geom_new`, '`la_id` where necessary, ..)

@gplssm and @boltbeard, please also be aware of this issue as it strongly affects the DGs..

**Comment by nesnoj** [comment]
EDIT: Didn't see @Ludee's answer before.. thanks for taking care

**Comment by IlkaCu** [comment]
> Will there be a recent 0.4.1?

We did not terminate the v0.4.1 release yet. So it would be good to integrate a solution for this bug in the v0.4.0 run. The DP reached the M5 script of the REA part already. For me it would be okay to integrate the bugfix after the debugging and before our clean run. But in that case you have to make sure that your bugfix works and does not harm the cleanrun.

**Comment by Ludee** [comment]
The bug can be fixed hard by putting multiple generators on one "available grid point".
But this is how the result looks like. This example is Berlin and subst_id 885 has a major issue:
There are 16 807 generators on about 2 km².

The real problem is somewhere else! There should be distribution to other MVGD in the first place (Status Quo), then the error gets bigger for the additional capacities.

![2018-05-04_ego-dp_rea_m5_bug](https://user-images.githubusercontent.com/14353512/39630711-74f32c4a-4fb0-11e8-9daa-de4e89513fbd.png)

**Comment by Ludee** [comment]
No comments on this?

**Comment by ulfmueller** [comment]
That definitely looks suspicious.

I have no insight knowledge on the implementation of this assignment generation procedure. My idea to this is that there are many power pants within the original power plant list which are located within this grid district. Probably a problem of the original data set. I could imagine that this happens primarly in big urban areas such as Berlin. That there are many renewables just tagged to the middle of the city...
Or what is your explanation? 
If this primarly would happen within cities, is it a inaccuracy which bothers you at the current modelling of ding0?
@IlkaCu @wolfbunke what are your explanations for this?

**Comment by wolfbunke** [comment]
Hey, I am back in office.
Regarding to the licensing question you can see the status on /redmine/issues/1870660101

**Comment by IlkaCu** [comment]
> The real problem is somewhere else! There should be distribution to other MVGD in the first place (Status Quo), then the error gets bigger for the additional capacities.

As the original issue of this ticket is solved I'll close it. Concerning problems with the distribution of RES generators between MVGD I would like to ask @Ludee to create a separate ticket.
