### ISSUE TITLE
456 generators in Atlantic ocean

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#243]
In table model_draft.ego_dp_supply_res_powerplant 456 offshore windturbines are located in the Atlantic ocean close to Cape Verde. Any ideas where this bug comes from and how to fix it? I think we already dealt with such a bug, but I cannot find the corresponding issue. 
![grafik](https://user-images.githubusercontent.com/16799094/37904951-91eb3fe4-30fd-11e8-94a0-a479a95007e5.png)

**Comment by wolfbunke** [comment]
Looks like the geometry of lon and lat are transposed. I will take a look.

**Comment by IlkaCu** [comment]
I had a look in the preprocessing script and it seems to be a problem with the SRID here: 
https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_dp_preprocessing_res_powerplant.sql#L287-L292

**Comment by IlkaCu** [comment]
Pull request #244 fixes this problem.
