### ISSUE TITLE
Allocated industry demand is too high 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#25]
The allocated industry demand is overrated by 16%. This seems to be caused by the calculation of the industrial area. 
In [process_eGo_osm_loads.sql](https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/process_eGo_osm_loads.sql#L5-L6) polygons of industrial large scale consumers are excluded from the creation of load areas. But for the calculation of `sector_area_industrial ` in [process_eGo_loads_per_grid_district.sql](https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/process_eGo_loads_per_grid_district.sql#L418-L433) all industrial polygons, including large scale consumers, are considered. 
@Ludee: Do you have any capacities to fix this?

**Comment by Ludee** [comment]
I'm back in Berlin from travelling and holidays and can have a look at this bug.
Do we have to push it in v0.1 (Master) or can I focus on v0.2?
I prefer v0.2 because I have some other features in mind as well.
If we correct v0.1 we will have to run the whole data_processing again. What do you mean @IllkaCu

**Comment by IlkaCu** [comment]
We should push it in v0.1 as well, as we are not sure when we will be able to execute v0.2 (due to some license issues).

**Comment by Ludee** [comment]
What is the difference between v0.1 and v0.2 regarding the licence? v0.1 doesn't have a licence (most parts of it) but both are on GitHub and "free". The main difference is the path of the database tables to model_draft. But this a Data Licence issue and not Software Licence.

When I fixed the bug in v0.2 I can push a hotfix in the master branch as well.
Just started with the debugging and will see when I reach it.

**Comment by IlkaCu** [comment]
It's about the data license, we don't want to publish data, which we would do in v0.2, without specifying a proper license.

**Comment by ulfmueller** [comment]
@IlkaCu : I created a new branch for the bugfix of the industry load "double allocation", which you can use for that... see: https://github.com/openego/data_processing/tree/bugfix-industry-loads

**Comment by IlkaCu** [comment]
@Ludee: Is this bug fixed in v0.2?

**Comment by Ludee** [comment]
Done, should be checked after processing.
There is some confusion because of the naming and order of the IDs (osm_id, gid, polygon_id, id).

**Comment by IlkaCu** [comment]
> Done, should be checked after processing.

Great! 

>  There is some confusion because of the naming and order of the IDs (osm_id, gid, polygon_id, id).

Do any tasks derive from this confusion? If yes, can you specify the problem?

**Comment by Ludee** [comment]
_openstreetmap.osm_deu_polygon_urban_sector_3_industrial_mview_
contains all industry polygons; has (original) **osm_id** that can't be PK and **gid** as PK
-> 61,291 entries

_model_draft.ego_demand_hv_largescaleconsumer_
contains EHV industry; doesn't have **osm_id**, **polygon_id** == **gid**
-> 295 entries

_openstreetmap.osm_deu_polygon_urban_sector_3_industrial_nolargescale_mview_
contains industry polygons without largescale; has (original) **osm_id** and **gid** as PK again
-> 60,990 entries (! should be 60.996 entries, possible bug!)

**Comment by IlkaCu** [comment]
As this addresses a different problem than the original issue, I would ask you to open a new one and specify the problem. I think I still didn't get what to do about the problems you described.

**Comment by Ludee** [comment]
It is one (the main) aspect of the high industry demand bug.
There are 61,291 OSM industry polygons. You identified 295 in EHV. But there is a difference (6 polygons) after removing these!

As you take a look of how they are removed you see different **column names** and **PK** in these tables. 
It's not only confusing to have different names for the same ID, it can be the reason of the mentioned difference/error.

Please compare the mentioned tables and the code:

[osm_deu_polygon_urban_sector_3_industrial_mview](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/sql_snippets/setup_osm_landuse.sql#L416-L437)

[ego_demand_hv_largescaleconsumer](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/sql_snippets/process_eGo_osm_loads_industry.sql#L362-L373)

[osm_deu_polygon_urban_sector_3_industrial_nolargescale_mview](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/sql_snippets/process_eGo_loads_per_grid_district.sql#L326-L346)

My suggestion is to check and rename the **polygon_id** to close this issue.
