### ISSUE TITLE
'Order by' statement

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#250]
The 'Order by' statement which was added two month ago by @Ludee to many of the loadarea scripts leads to bugs in the dataprocessing. 
While debugging the DP scripts I commented many of the Order By statements out (c14569551f472fa19ba52cd87746c20c5e58f680). 
Please check whether this is the right way to fix the bug or not.

**Comment by Ludee** [comment]
The order by were added to take out the salt of each run.
Don't know why they give an error. Is it syntax or something else?

**Comment by s3pp** [comment]
imho the gid is not part of the result set, so it cannot be ordered, e.g.: https://github.com/openego/data_processing/blob/c14569551f472fa19ba52cd87746c20c5e58f680/dataprocessing/sql_snippets/ego_dp_loadarea_census.sql#L93-L97

**Comment by IlkaCu** [comment]
@Ludee What was your concrete intention to add the 'order by' statement? Would it be okay to delete it without substitution? If not, please provide a bugfix.

**Comment by nesnoj** [comment]
If I'm not mislead, this was subject of my ticket #171 which has not been finished..

**Comment by IlkaCu** [comment]
This still doesn't answer my question whether deleting the 'Order by' is okay or not. @Ludee: Please comment here.

**Comment by Ludee** [comment]
The removal is ok. It only changes the _ids_ but should not affect the data.

I'm wondering why the order by gave an error. Perhaps there was a typo (order by _id /nid_ which does not exist) or something else?

**Comment by IlkaCu** [comment]
As s3pp wrote, the statement does not select any id/gid/nid - so it cannot order it. 
But as long as you are okay with removing it, I will close this issue.
