### ISSUE TITLE
ego_dp_powerflow_hv_setup.sql blocked by another process

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#257]
When executing sql-snippet ego_dp_powerflow_hv_setup.sql
 the following bug occurs. Can someone help? 
```
OperationalError: (psycopg2.extensions.TransactionRollbackError) deadlock detected
DETAIL:  Process 10577 waits for AccessExclusiveLock on relation 2417679 of database 16435; blocked by process 10893.
Process 10893 waits for AccessShareLock on relation 2417652 of database 16435; blocked by process 10577.
HINT:  See server log for query details.
```

**Comment by nesnoj** [comment]
I ran the cutting script yesterday on ego_pf_hv_* tables but it finished successfully without warnings..
What does the Server Status in pgAdmin say? (I cannot use it due to mobile connection)

**Comment by IlkaCu** [comment]
In the meantime I run the script manually and step by step with pgAdmin and found two minor bugs in the script. Afterwards I used the eGo_data_processing.py to run it again - without any problems.
