### ISSUE TITLE
Loadareas assigned to EHV buses 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#258]
When trying to solve a bug which occurred while executing script ego_dp_powerflow_assignment_load.sql, I recognized that some HVMV substations are listed as substations with v_nom >110 kV in table _model_draft.ego_grid_pf_hv_bus_. 

The following query returns 215 buses per scenario which are listed in table _model_draft.ego_grid_hvmv_substation_ as HVMV substations but in  model_draft.ego_grid_pf_hv_bus as EHV substations: 
`SELECT * FROM model_draft.ego_grid_pf_hv_bus WHERE v_nom >110 AND bus_id IN (SELECT otg_id FROM model_draft.ego_grid_hvmv_substation); ` 

As the load areas are assigned to substations based on table [model_draft.ego_grid_mv_griddistrict](https://github.com/openego/data_processing/blob/release/v0.4.0/dataprocessing/sql_snippets/ego_dp_loadarea_loadcut_griddistrict.sql#L590-L600) (which itself is derived from _model_draft.ego_grid_hvmv_substation_) it leads to the problem that load areas, which where supposed to be assigned to a 110 kV substation, are mistakenly assigned to EHV buses in the final model. 

I'm confused and would be glad about some ideas and suggestion where this comes from and how we could possibly solve the issue.

**Comment by IlkaCu** [comment]
https://github.com/openego/data_processing/blob/fix/buses_removed/dataprocessing/sql_snippets/ego_dp_substation_otg.sql#L22-L26
Do we need an additional where statement here include only 110 kV buses?

**Comment by IlkaCu** [comment]
I tried to fix this bug with the following commit d9222abd4b4e6ba9fff7716973ff84144a189e9d. Rerunning the affected scripts revealed that 17 substations from table _model_draft.ego_grid_hvmv_substation_ and 11 substations from table _model_draft.ego_grid_ehv_substation_ remain without an otg_id. 

Checking this with QGIS shows that those substations do not have a corresponding item of the same voltage level in the PF table (_model_draft.ego_grid_pf_hv_bus_). We find a hvmv substation in table _model_draft.ego_grid_hvmv_substation_ and a corresponding mv_griddistrict, but at the same spot no 110 kV bus in model_draft.ego_grid_pf_hv_bus. 

The same happens for 11 ehv substations, where we only find 110 kV buses at spots where table _model_draft.ego_grid_ehv_substation_ lists ehv substations.

**Comment by IlkaCu** [comment]
In commit 6d861726a97cb646e88a05fced37396cfccbbe5e I tried to solve this problem by deleting all substations without an counterpart in the osmTGmod dataset (those without an otg_id in _model_draft.ego_grid_hvmv_substation_ and _model_draft.ego_grid_ehv_substation_). In the following DP this would result in a modified number of mv griddistricts and ehv voronoi cells. @gplssm: Would that be okay for you?

**Comment by gplssm** [comment]
In general, this is fine for us, but makes life sometime harder. If we want to compare results basing on DP v0.3.0 with results basing on DP v0.4.0 it requires to build a mapping of mv_griddistrict_ids between these two versions.
If it really helps you, go for it! If it does not solve your problem, I would like not to have new mv_griddistrict_ids.
