### ISSUE TITLE
Suggestion for release work flow 'creating a minor release before starting a major one'

### ISSUE THREAD

**Issue by ulfmueller** [openego/data_processing#262]
For future clean-releases, I would suggest to have always a minor release right before the debugging process which just executes the versioning script (similar to the 0.3.0pre1 release done by @nesnoj ) just to version the last status of the model_draft before it is being 'emptied out'. Of course this kind of release might not be clean or consistent. So it can only used with additional care.

Or should we name these instable release in a different way (s.th. like 0.3.0pre1 (that naming btw has produced some misinterpretations as well 'is it pre 0.3.1 or pre 0.3.0?')

What do you think?

This was raised in the context of #261

**Comment by Ludee** [comment]
I think the idea to create minor versions is quite good and would improve data availability.
But I never really understood the "preversion" stuff.
Why not just use a "real" version and give it a good name and explanation (and set release = false).

Therefore we have the [eGo scenario list](https://github.com/openego/data_processing/blob/51f0a25008c8f531e47bc937138c6a1642299655/preprocessing/sql_snippets/ego_dp_structure_scenariolog.sql#L27-L41)

**Comment by IlkaCu** [comment]
> For future clean-releases, I would suggest to have always a minor release right before the debugging process which just executes the versioning script (similar to the 0.3.0pre1 release done by @nesnoj ) just to version the last status of the model_draft before it is being 'emptied out'.

I support that idea and could include this procedure in the 'how-to-release' tutorial I am going to write. Any objections? 

@Ludee: I can't find the script to create the [eGo scenario list](https://github.com/openego/data_processing/blob/51f0a25008c8f531e47bc937138c6a1642299655/preprocessing/sql_snippets/ego_dp_structure_scenariolog.sql#L27-L41) in the current dev branch. And does the script need to be adjusted after implementing the multiproject scenario_log in #226.

**Comment by Ludee** [comment]
Somehow it is not in the dev branch. I found the script by search. 
Can we merge it?

The multiproject scenario_log should be fine with it. I already removed the foreign key to prevent errors with a new version.

**Comment by IlkaCu** [comment]
> Somehow it is not in the dev branch. I found the script by search.
Can we merge it?

Feel free to create a PR for branch release/v0.4.0 to include the script.

**Comment by Ludee** [comment]
The scenario list is [here](https://github.com/openego/data_processing/blob/release/v0.4.0/preprocessing/scenario_log/ego_pp_scenario.sql#L55)

I added the new versions v0.4.0 and v0.4.1
So the next run should be v0.4.1!

**Comment by IlkaCu** [comment]
I changed the description of v0.4.0, as this is the version used for debugging. I'm planning to release the actual data set created in the clean-run under version v0.4.1.

**Comment by IlkaCu** [comment]
@Ludee: Btw please use branches and Pull Request when implementing changes in the dev or release branch. We agreed on this procedure already quite a long time ago and it helps to keep track of all changes during the release process.

**Comment by IlkaCu** [comment]
I documented the suggested work flow in the release guide.
