### ISSUE TITLE
Bug in 'ego_dp_powerflow_assignment_storage.sql'

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#264]
`ProgrammingError: (psycopg2.ProgrammingError) column "id" does not exist
LINE 410:    where id <= 27
                   ^
HINT:  There is a column named "id" in table "a", but it cannot be referenced from this part of the query.
`
@ClaraBuettner  @s3pp: Can you help? 

Did someone change the code in  ego_dp_powerflow_assignment_storage.sql or table model_draft.ego_grid_hv_electrical_neighbours_bus? 
The electrical_neighbours_bus table includes a bus_id, which contains values much higher than 27. So I guess this would not be the right column to be referenced here.

**Comment by ClaraBuettner** [comment]
Yes, I needed to change model_draft.ego_grid_hv_electrical_neighbours_bus to add connections between electrical neighbors. I thought I change it everywhere but it seems I havn't found this line. 
You need to change "where id <= 27" to "where central_bus = True", that has to work.
