### ISSUE TITLE
Bug related to 'power_class' in ego_dp_powerflow_timeseries_generator.sql

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#266]
The following error occurs when executing the script ego_dp_powerflow_timeseries_generator.sql

```
ProgrammingError: (psycopg2.ProgrammingError) column "power_class" does not exist
LINE 88:  power_class,
          ^
HINT:  There is a column named "power_class" in table "gen", but it cannot be referenced from this part of the query.
```

@MarlonSchlemminger: Can you help here?

**Comment by MarlonSchlemminger** [comment]
Yeah, the table model_draft.ego_renewable_feedin is the old version. Did this script run properly before? https://github.com/openego/data_processing/blob/release/v0.4.0/preprocessing/python_scripts/renpass_gis/simple_feedin/simple_feedin.py

**Comment by IlkaCu** [comment]
Thanks for your quick respond. I didn't know about that script and the necessity to execute it before the release.

**Comment by MarlonSchlemminger** [comment]
Oh weird, I didn't create the script, I just changed it, so I thought it has always been part of the dp.

**Comment by IlkaCu** [comment]
In the preprocessing the script will only be created once and is not included in the 'normal' DP run. Is that in line with the changes you made?

**Comment by MarlonSchlemminger** [comment]
This is fine as long as the data in model_draft.ego_supply_renewable_bnetza_full_attribute and the weather data don't change. 
If the weather data changes, this script has to run prior to simple_feedin.py. I think Wolf ran it manually a few weeks ago.
https://github.com/openego/data_processing/blob/release/v0.4.0/preprocessing/sql_snippets/ego_simple-feedin_per_scenario.sql

**Comment by wolfbunke** [comment]
Hi, I just started to run simple_feedin.py and it will be followed by ego_simple-feedin_per_scenario.sql as far the first script is done. So far the script is running well.

**Comment by MarlonSchlemminger** [comment]
It should be the other way around, ego_simple-feedin_per_scenario.sql first and simple_feedin.py second. But as I said, I think you already ran ego_simple-feedin_per_scenario a couple of weeks ago, so it shouldn't matter.

**Comment by IlkaCu** [comment]
> I just started to run simple_feedin.py

Did the script finish in the meantime?

**Comment by MarlonSchlemminger** [comment]
I think so, the column power_class exists now.

**Comment by wolfbunke** [comment]
You are talking about the model_draft.ego_supply_pf_generator_single table right?
Do we create the  power_class  column with the  `ego_simple-feedin_per_scenario.sql` or `simple_feedin.py ` -  No or?  Strange , should be an other script creating this column as those I started to run. ...

**Comment by IlkaCu** [comment]
As far as I know, its table model_draft.ego_renewable_feedin which needed to be updated.
model_draft.ego_supply_pf_generator_single is created in the assignment_generator script. 

https://github.com/openego/data_processing/blob/release/v0.4.0/dataprocessing/sql_snippets/ego_dp_powerflow_timeseries_generator.sql#L86-L95

**Comment by MarlonSchlemminger** [comment]
The power_class column for model_draft.ego_renewable_feedin is produced in simple_feedin.py. The power_class column in model_draft.ego_supply_pf_generator_single is produced here https://github.com/openego/data_processing/blob/release/v0.4.0/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_generator.sql#L243.

**Comment by wolfbunke** [comment]
ok, data are updated now.

**Comment by wolfbunke** [comment]
The backup files can be found on ftp /open_eGo/OpenEnergy_Plattform/Datenbank/backups-dumps

**Comment by MarlonSchlemminger** [comment]
As visualization of the whole process.
![grafik](https://user-images.githubusercontent.com/22960010/40657531-7fb4ca5c-6348-11e8-8c27-80598f6ed821.png)

**Comment by IlkaCu** [comment]
The script executed properly in the DP Debugging.
