### ISSUE TITLE
[oedb] license system

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#27]
Ich mache mal einen Aufschlag zum Thema Lizenzen. Das wird immer schön hin- und hergeschoben aber ohne erkenntliche Fortschritte.
Auf dem OPSD-Workshop gab es dazu nochmal Impulse und ich hänge beim Datenbankkonzept an dieser Stelle.
Zudem ist dies ein notwendiger Baustein für die (weitere) Arbeit und Ausführung von ego (v0.2).

Da das Redmine nicht da ist habe ich hier den aktuellen Stand zusammengefasst:

- Wir verwenden als Inputs ausschließlich „freie“ Daten, müssen aber deren Lizenzen oder Terms beachten
- Wir benötigen passende Lizenzen für unseren Code, erzeugte Daten und erstelltes Artwork (Diagramme, Bilder, Karten)
- Das Konzept muss mit den Projektanträgen/Kooperationsverträgen juristisch vereinbar sein und von der Community (open_eGo/oemof/openmod) praktikabel anwendbar sein
- Wir sollten uns auf eine Autorenschaft verständigen, siehe https://github.com/oemof/organisation/issues/9
- Es gibt in open_eGo ein Budget für einen externen Experten

Hier ist mein Vorschlag für das open_eGo/ open_FRED/ oedb/ oemof(?) Lizenz-Konzept und dessen Anwendung:

Code unter GLP-3 auf Github
Daten unter ODbL in der eodb mit Metadaten (in der ODbL inkludiert)
Erzeugte Werke unter CC (z.B. CC-BY-NC-SA-4.0)

Meine offenen Fragen:

- Müssen alle Copyright-Autoren (BKG, OSM) „durchgeschleift“ werden?
- Wenn JA wie weit? (Technische Möglichkeit in den Metadaten vorhanden.)
- Welchen Autor wählen wir für unseren Code und für erzeugte Daten? Ebenfalls „oemof group“ oder „ego group“? Hat das Konsequenzen (Projektende)?
- Wie und wo sammeln wir die weiteren Lizenzfragen?
- Wie gehen wir bei der Einbindung des „Experten“ vor?

**Comment by Ludee** [comment]
Also see https://github.com/oemof/organisation/issues/9

**Comment by lukasol** [comment]
@Ludee, danke für die Initiative.  @IlkaCu hatte in der vergangenen Woche auch zu einer Terminabstimmung für eine Telko eingeladen. Lasst uns diese Punkte doch dabei besprechen. Zu einigen deiner Fragen habe ich eine eindeutige Antwort bzw. Einschätzung, anderer sind glaube ich abstimmungsintensiv.

**Comment by Ludee** [comment]
Den Termin zur Abstimmung habe ich wohl nicht bekommen. @IlkaCu gerne nochmal an mich.

Dann stelle ich diese Frage mit Ergänzung mal an den Anfang:
Wie und wo sammeln wir Lizenzfragen und die Antworten darauf?

Möglichkeiten: Redmine (wenn wieder online), Github, openmod-wiki
I bevorzuge das letztere.

**Comment by Ludee** [comment]
Teilnehmer: Ludwig, Lukas, Ronny, Günni, Ulf, Wolf
Moderator: Ludwig

Da das Redmine nicht da ist habe ich hier den aktuellen Stand zusammengefasst:
•	Wir verwenden als Inputs ausschließlich „freie“ Daten, müssen aber deren Lizenzen oder Terms beachten
•	Wir benötigen passende Lizenzen für unseren Code, erzeugte Daten und erstelltes Artwork (Diagramme, Bilder, Karten)
•	Das Konzept muss mit den Projektanträgen/Kooperationsverträgen juristisch vereinbar sein und von der Community (open_eGo/oemof/openmod) praktikabel anwendbar sein
•	Wir sollten uns auf eine Autorenschaft verständigen, siehe https://github.com/oemof/organisation/issues/9

Hier ist mein Vorschlag für das open_eGo/ open_FRED/ oedb/ oemof(?) Lizenz-Konzept und dessen Anwendung:
Code unter {LGPL-3/2, (A)GPL-3/2, MIT, BSD3, (Apache, Eclipse, ...)} auf Github
Daten unter ODbL in der eodb mit Metadaten (in der ODbL inkludiert)
Erzeugte Werke unter CC (z.B. CC-BY-NC-SA-4.0)

Offene Fragen:

•	Müssen alle Copyright-Autoren (BKG, OSM) „durchgeschleift“ werden?
•	Wenn JA wie weit? (Technische Möglichkeit in den Metadaten vorhanden.)
•	Welchen Autor wählen wir für unseren Code und für erzeugte Daten? Ebenfalls „oemof group“ oder „ego group“? Hat das Konsequenzen (Projektende)?
  https://opensource.org/faq#contributor-agreements
•	Wie und wo sammeln wir die weiteren Lizenzfragen?
•	Wie gehen wir bei der Einbindung des „Experten“ vor?


h1. Protokoll

h2. 3 wesentliche Bereiche bezüglich Lizenzen

* Code
* Daten
* Artwork aka Texte, erzeugte Karten etc

h3. Code

* Wie wird die Blanko-Lizenz gefüllt?
** Autorenschaft 
*** einheitlich oder uneinheitlich?
*** unklar: was bedeutet es, unterschiedliche Autoren zu nennen
*** ist der git-commit maßgeblich für die Autorenschaft? vs. der Angaben in der Lizenz
*** Contributions an Gruppe abtreten-

** Frage nach der Lizenz  "GPL v3 oder doch was anderes?"
*** ist uns GPL-3 zu ristriktiv im Bezug auf eine zukünftige kommerzielle Nutzung
*** sind wir gezwungen GPL3 zu nehmen, wenn wir Module einbinden, die unter GPL3 stehen? theoretisch ja, praktisch Experten-gemäß
*** Link: http://ifross.org/lizenz-center#term-214

h3. Daten

* siehe auch Graphik von Ludwig
* LW: Kompatibilität der Daten. Unterschiedliche Inputs mit unterschiedliche Lizenzen, die die Weiterverwendung der Lizenz jeweils vorschreiben
Dann schaffen wir halt Werke! versus Schaffung einer abgeleiteten DB

h3. Artwork aka Texte, erzeugte Karten etc 
Irgendwelche Probleme mit Creative Commons Lizenz?

h3. oedb Website inkl. Disclaimer inkl. Haftungsausschus

Nächster Termin:

12.12. 13.00 Uhr
Todos bis dahin:

• Autorenschaft vs. Kooperationsvertrag vs. Institutsvorschriften (Ulf, Lukas) 
• Welche CC für unser Artwork (Ronny) 
• Datenverwendung aus verschiedenen Quellen und neues Werk (Ludwig) 
• Disclaimer für Website und OEP (Wolf) 
• Genaue Umsetzung (Beispiel/Vorlage) der Teilaspekte (Alle)

**Comment by Ludee** [comment]
Hab grad mal einen Blick in unseren (RLI) Arbeitsvertrag geschaut. Zum Thema Autorenschaft steht da natürlich nichts. Es gibt einen Absatz über [Diensterfindungen](https://de.wikipedia.org/wiki/Arbeitnehmererfindung), aber da wir werden ja keine Patente beantragen.
Es kann und darf halt auch mal einfach sein ;)

**Comment by Ludee** [comment]
OSM sagt auf einer nicht rechtlich bindenden [FAQ](http://wiki.openstreetmap.org/wiki/Open_Data_License/Use_Cases#Extracting_road_centre-line_data_for_bus_routes_from_OSM_data_based_on_lists_of_bus_stops) folgendes zu der Abletung von Geodaten:

> Extracting road centre-line data for bus routes from OSM data based on lists of bus stops?
> -> Attribution notice covered by section 4.3

[ODbL](http://opendatacommons.org/licenses/odbl/1.0/)

> 
> 4.3 Notice for using output (Contents). Creating and Using a Produced
> Work does not require the notice in Section 4.2. However, if you
> Publicly Use a Produced Work, You must include a notice associated with
> the Produced Work reasonably calculated to make any Person that uses,
> views, accesses, interacts with, or is otherwise exposed to the Produced
> Work aware that Content was obtained from the Database, Derivative
> Database, or the Database as part of a Collective Database, and that it
> is available under this License.
>       a. Example notice. The following text will satisfy notice under Section 4.3:
>     **Contains information from DATABASE NAME, which is made available
>     here under the Open Database License (ODbL).**

**Comment by Ludee** [comment]
Hier ist es mal einigermaßen Verständlich:

[Case 4: I want to publish something based on OSM and some data I obtained elswhere](http://wiki.openstreetmap.org/wiki/License/Use_Cases#Case_4:_I_want_to_publish_something_based_on_OSM_and_some_data_I_obtained_elswhere)
> **License requirements:** you will need to credit OSM in any produced works (such as maps). If you create a derivative database, you will need to make it available. You must ensure that the license requirements of the third party data do not conflict with the license conditions of ODbL, for example the requirement to make the derivative database available free. Data with licenses that are "incompatible" with ODbL in this way cannot be used with OSM if the use involves publishing or conveying a derivative database. Many licenses, including the Creative Commons SA licenses, are compatible. 

[Definition of produced work](http://wiki.osmfoundation.org/wiki/Licence/Community_Guidelines/Produced_Work_-_Guideline)

> We can clearly define things that are USUALLY Produced Works: .PNG, JPG, .PDF, SVG images and any raster image; a map in a physically printed work.
Database dumps are usually not Produced Works, e.g a Planet dump.

**Comment by Ludee** [comment]
Zusammenstellung der zugrunde liegenden Lizenzen von bisher verwendeten Daten (ZNES):

renpass_gis Szenariendaten:
* u.a. Literaturwerte für bspw. variable Kosten
* Solar & Windzeitreihen - CC BY-NC 4.0
* ENTSOE - Daten, Scenariodaten und Lastzeitreihen (teilweise in OPSD)

Renewable Power Plants:
* Gemischte Quellen aus EnergyMap und BNetzA
* EnergyMap:  "Das Urheberrecht
Das EEG verpflichtet die Netzbetreiber zur Veröffentlichung der Daten. Nach unserem Verständnis der gesetzlichen Grundlage handelt es sich somit um "freie, öffentliche Daten". Da wir diese Daten nur zusammenführen und auf Plausibilität testen erheben wir von unserer Seite ebenfalls keinen Anspruch auf ein "Urheberrecht", auch wenn dies für einige Aspekte der Datenbasis berechtigt sein könnte.
Status: Ok für Veröffentlichung

Da der Prozess dennoch mit viel Arbeit verbunden ist, würden wir uns jedoch freuen, wenn alle, die unsere aufbereiteten Daten verwenden, unser Projekt im Sinn der "Fairness" auch auf die eine oder andere Art unterstützen würde. Dies könnte z.B. der Beitritt zu einem der Trägervereine sein, eine Spende oder die Nennung und der Verweis auf die "EnergyMap" als Quelle des Datenbestandes."
* Zugrunde liegende Datenrechte der TSO's durch OPSD Abgedeckt: 
* OPSD Lizenz  - momentan: "Attribution should be given as follows: "Data provided by Open Power System Data, http://open-power-system-data.org/, Data Package Renewable power plants, version 2016-10-21. Primary data from BNetzA, BNetzA_PV, TransnetBW, TenneT, Amprion, 50Hertz, Netztransparenz.de, Postleitzahlen Deutschland, Energinet.dk, Energistyrelsen, GeoNames, French Ministery of the Environment, Energy and the Sea, OpenDataSoft, Urzad Regulacji Energetyki (URE)""
Status: Ok für Veröffentlichung

Power Plants:
OPSD Lizenz: Attribution should be given as follows: "Data provided by Open Power System Data, http://open-power-system-data.org/, Data Package Conventional power plants, version 2016-10-27. Primary data from BNetzA Kraftwerksliste, Umweltbundesamt Datenbank Kraftwerke in Deutschland, ELIA Generation facilities (BE), TenneT Available capacity 2015 (NL), RTE List of production units with more than 100MW (FR), GPI List of generation units (PL), CEPS Available capacity (CZ), BFE Statistik der Wasserkraftanlagen der Schweiz (CH), BFE Nuclear Energy (CH)"

NEP Kraftwerksliste:
* 50Hertz Transmission GmbH, Amprion GmbH, TenneT TSO GmbH TransnetBW GmbH
Datenschutzhinweis: https://www.netzentwicklungsplan.de/de/datenschutzhinweise
Quelle: https://www.netzentwicklungsplan.de/sites/default/files/paragraphs-files/nep_2015_kraftwerksliste_entwurf_140430.pdf
Status: UNKLAR für Veröffentlichung
Vor Veröffentlichung: Lion Hirth, abklären bzw. Anschreiben / Erlaubnis an die TSOs für NEP Daten einholen

**Comment by Ludee** [comment]
Webco eGo Lizenzen von Daten und Modellen Teil 2
Teilnehmer: Ulf, Wolf, Lukas, Ludwig, Martin G., Ronny, Günni, 

Aufgaben:
•       Autorenschaft vs. Kooperationsvertrag vs. Institutsvorschriften (Ulf, Lukas)
1. oemof artige solution -> eine dev group
Pro:

Cons:

2. einzelne Institute
Pro:

Cons:
50-50 siehe Abstimmung 

•       Welche CC für unser Artwork (Ronny)
•       Datenverwendung aus verschiedenen Quellen und neues Werk (Ludwig)
Tendenziell odbl,
aber Kärung der Inkompatibilitäten wichtig
ist eine Frage für den RLI-Berater
Haftung? Ronny sagt, das scheint bei odbl nicht so prägnant verankert zu sein
Ludwig: doch, steht in Paragraph 7 und 8

•       Disclaimer für Website und OEP (Wolf)
läuft ist aber noch nicht fertig
•       Genaue Umsetzung (Beispiel/Vorlage) der Teilaspekte (Alle)
Autorenschaft muss geklärt werden. Weiteres Vorgehen -> auch Vorbereiten (Mail und Issue) 
odbl für die Daten. Mail und gh Issue (-> Ulf)
vorbereiten und auf PT entscheiden.
Einsatz des Beraters vom RLI

**Comment by lukasol** [comment]
Ich möchte gern den Punkt "Einsatz des Beraters vom RLI" noch einmal verstärken. Es wäre doch gut, wenn wir hier bis zum Treffen im Januar bereits mehr wissen bzw. ggf. sogar Sicherheit haben. Fragen haben wir ja bereits eine Menge, würdet ihr (RLI) die Auswahl und Ansprache anleiern?

**Comment by Ludee** [comment]
Offene Fragen:

**Code - Header**
- Braucht jedes Script einen Header oder reicht die LICENSE?
- Wenn ja, braucht der Header ein Link auf die License im Repo?
- Wenn kein Header dann wird ein author/copyright owner in der LICENSE benötigt?

**Data - Metadata**
- Autorenschaft von Daten, wer ist Autor?
- Autorenschaft und Lizenzinhaber?
- Wie bekommt der Autor den "credit" für seine Arbeit?
- Wann ist ein neues Werk geschaffen?
- Durchschleifen von Quellen bis zum bitteren Ende?
- Müssen die verwendeten Programme (Scripte) angegeben werden

@beritRLI kümmert sich um die Beauftragung des "Experten"

@openego/data_processing

**Comment by Ludee** [comment]
Weitere Quellen:
http://www.ratswd.de/publikationen/european-data-watch
www.ifross.org 
http://auffinden-zitieren-dokumentieren.de/

**Comment by wolfbunke** [comment]
Hier nochmal alle Tickets zur Übersicht:

https://github.com/openego/oeplatform/issues/158#issuecomment-262465594 (Licences)
https://github.com/openego/oeplatform/issues/157#event-822455524 (Database: Open data only. )
https://github.com/openego/oeplatform/issues/174 (Impressum and legal hedging )
https://github.com/openego/data_processing/issues/27 (Datenverwendung aus verschiedenen Quellen)

Ich schaffe es heute nicht mehr alles durchzulesen und  zu kommentieren und melde mich daher am Donnerstag zurück.

**Comment by Ludee** [comment]
Issue #1178 has been updated by Lukas Wienholt. 
Wolf-Dieter Bunke wrote:
ich glaub eine Trennung der Themen Lizensen könnte Sinn ergeben. Wir habe momentan zwei-drei Fragen / Arbeitsstellungen die Sich um Lizenzen drehen.
Da stimme ich zu. Ich wäre auch für eine baldige Bearbeitung der Fragen.
1.) Lizenzen von Daten die wir verwenden. Dies betrifft insbesondere solche die in neuer / gemischter Datenstruktur vorkommen. Bsp.: Ilkas statistische Daten zur Lastverteilung, die als kompletter Datensatz eine restriktive Lizenz haben, aber nur drei Werte aus der PDF/ Datentabelle entnommen wurden. Oder die ENTSO-E Lastzeitreihen für die nur einige Länder eine offene Lizenz aufweisen ( Zwischenergebnis von OPSD - Belgien dürfte gerade nicht verwendet werden)
Das Problem lässt sich nach meiner Einschätzung juristisch nicht lösen, höchstens erläutern. Das heißt, dass wir bei Veröffentlichung gegen die (teilweise nicht vorhandenen) Lizenzauflagen verstoßen würden: der default ist laut Urheberrecht, dass Daten ohne Lizenz nicht weitergegeben werden dürfen. Solche Entscheidungen sollten wir gemeinsam treffen und dokumentieren.
2.) Lizenzen eigener Daten und Ergebnisse. OSM Daten müssen laut OSM Lizenz unter selbige wieder veröffentlicht werden. Wie sieht dies mit Mischdatensätzen aus z.B. OSM + Zensus-Daten -> Zwei offene Lizenzen. Kann ego eine eigene Lizenz (z.B. offenere) nach der Bearbeitung und Berechnung der Modelle verwenden und welche?
Nein, es muss in jedem Fall die ODbL verwendet werden, sofern es sich um aus OSM abgeleitete Datenbanken handelt - und das ist bei uns ja recht eindeutig der Fall. Dazu die Erläuterung vom OSM-FAQ:
Die OpenStreetMap-Datenbank wird seit dem 12. September 2012 unter der Lizenz „Open Database Licence (ODbL) 1.0" verteilt, die einzelnen Objekte in der Datenbank stehen unter "Database Contents License (DbCL) 1.0". Die Lizenz besagt, dass jegliche Art der Nutzung von OSM-Daten, auch gewerblich, zulässig ist, solange die Lizenzbedingungen eingehalten werden. Die ODbL unterscheidet hierbei zwischen der Nutzung der Daten als Datenbank und der Herstellung eines Werkes ("Produced Work") aus den Daten, z.B einer auf Papier gedruckten Karte. Abgeleitete Datenbanken dürfen hierbei nur unter der ODbL weiter verteilt werden, bei "Produced Works" wird nur vorgeschrieben, dass ein entsprechender Quellenhinweis angebracht wird und gegebenenfalls eine zur Herstellung verwendete abgeleitete Datenbank in einer geeigneten Form zur Verfügung gestellt wird.
Man muss hier eigentlich jeden Fall durchgehen und die Kompatibilität der Lizenzen prüfen, ich fürchte aber, dass das in den meisten Fällen nicht der Fall sein wird.
3.) Auswahl der eigenen Software Lizenz läuft gerade auf GPL 3 (oemof Lizenz) hinaus, welches jedoch den Nachteil hat, dass Unternehmen das Tool Aufgrund dieser Lizenz eher nicht nutzen werden, da alle ihre Änderung unter der gleichen Lizenz veröffentlicht werden müssen. -> Absprache mit Ptj vielleicht nötig???
Auch das sollten wir zeitnah diskutieren und beschließen. Meine Präferenz ist relativ eindeutig gegen die GPL3, sondern eher für eine non-copyleft Lizenz, wie Apache oder MIT, die mehr Spielraum zur (kommerziellen) Nutzung hat.
Außerdem halte ich eine Auseinandersetzung mit dem Thema Lizenzen im Hinblick auf den Code auf Github für erforderlich. Also welche Angaben sollten in jeder Datei enthalten sein, etc.
Ich bin zur weiteren Abstimmung für eine Telko und auf jeden Fall Beschäftigung auf dem Projekttreffen.

**Comment by lukasol** [comment]
Ergänzend zu den Fragen von @Ludee hier noch ein paar Dinge, die aus meiner Sicht von einem Experten bearbeitet / beantwortet werden sollten:

- Prüfung der Kompatibilität der Eingangsdaten: Aus meiner Sicht wäre es sinnvoll, wenn sich ein Experte einmal anhand unserer konkreten Beispiele anschaut, ob die Lizenzen kompatibel sind. Etwa die Lizenz der openstreetmap-Daten (ODbL) und die der Zensus-Daten. Ideal wäre natürlich alle offenen Kompatibilitätsfragen zu klären, machbar wäre es aber auch, wenn wir das anhand einiger repräsentativer Beispiele klären lassen.
- Handelt es sich bei den von uns erstellten und auf die oedb gestellten Daten um produced work oder eine abgeleitete Datenbank? Dies ist entscheidend für die Bewertung der Nutzung der ODbL

**Comment by beritRLI** [comment]
Hier noch Fragen und Antworten aus der openmod mailingliste:
Tim Tröndle:
There is this one question when dealing with data that is not entirely open (public but with restricted access) or closed (proprietary) for which I never found a satisfying general answer: in which form am I allowed to republish the data? Especially when aiming at an open, reproducible workflow this question is not only relevant for the publication of a final report, but also affects publication of other artefacts: analyses results, scripts, notebooks, tools,… 

Now with “in which form" I am thinking of questions like:
•	At which aggregation level can the data be published?
•	Can sample entries be published? Do they need to be anonymised? How?
•	Can metadata be published if it is not originally published openly?
•	One could even go far and ask the question: Can I publish results of a simulation model that was calibrated with this kind of data? Given open models, in many cases one can derive findings on the input if not even inferring the entire source data set.
	
Especially the last point might be slightly theoretical, but shows my confusion: I would like to have clear rules about what is possible and what is not. Where can one find an answer to this question? In the license? What if the license does not state anything about that? Or remains vague? How are you dealing with this issue?

Robbie Morrisson:
This question was discussed at the Open Power System Data (OPSD) project workshop on 21 November 2016. I posted a short report to this list on the workshop on 22 Nov 2016 10:10:05 +0100.
The presentation by intellectual property lawyer Lina Boecker, JBB Rechtsanwaelte, covers some of what you ask. In relation to the 2013 directive on energy data transparency from the European Commission under European transparency regulation 543/2013. Boecker noted that (slide 14):
"It [the directive] is only an obligation to publish, not an obligation to license."
A more recent 2016 amendment to the German Energy Industry Act (Energiewirtschaftsgesetz or EnWG) section §111d contains a similar transparency provision for Germany.
So what can you do with data published under transparency regulations? Not much beyond inspecting it.
My guess is that aggregating such data would produce a derived work and is thus not permitted. Republishing sample entries is similarly not permitted, unless seen to be acceptable under fair use provisions. Fair use is a primarily a US legal doctrine and is less relevant and less supported in Europe. Anonymizing the data does not specifically help, beyond making it less likely that your breach of copyright will be detected. I am not sure what you mean by metadata in this case? Can one reverse engineer metadata from the original data? I think not.
Regarding the use of such data by in-house models to produce new results. That is tricky. I don’t know the legal position. But even if acceptable, the problem still arises that you cannot publish your model inputs for others to scrutinize. And that in itself is a significant drawback.
The other issue you did not traverse is that of database protection under the 1996 European database directive 96/9/EC and now embodied, in part, in the German Copyright Act (Urheberrechtsgesetz or UrhG). This protects any substantial investment required when assembling and presenting large amounts of data, irrespective of the copyright status of the contained data. This means that significant parts of a database cannot be simply downloaded and republished, even if the data itself is unencumbered.
If there is no explicit license, the default is all rights reserved copyright. Under the Berne Convention copyright exists the moment a work is “fixed”, that is, written or recorded on some physical medium. Modern copyright law does not require the copyright holder to seek registration.
The question of vague licensing is also interesting, but not something you are likely to encounter with regard to the datasets you are considering. In relation to code, Morin et al (2012, p1) say that the absence of an open license agreement creates a state of legal uncertainty whereby potential users cannot know which limitations the owner may want to enforce in the future. GNU are more relaxed about informal licenses, which might say something like “do whatever you like with this” or “you can redistribute this code and change it”. GNU believes that US courts will interpret informal licenses based on what the author seemed to intend. But GNU adds that other countries (meaning Europe?) have a more rigid approach to copyright licensing and may take the opposite view. Not much of this has been tested in court.
Non-open energy data is a serious problem and one which needs advocacy from organizations like the Free Software Foundation Europe (FSFE) and even the openmod initiative.
Perhaps Lion Hirth or someone else from the OPSD project might be able to offer a more experienced view than mine?

**Comment by beritRLI** [comment]
Ich habe den Rechtsanwalt Till Jäger angefragt
melde mich wenn ich antwort habe

**Comment by lukasol** [comment]
@beritRLI sind die Fragen auch schon übermittelt worden, sodass wir auch zeitnah (bis zum Projekttreffen?) mit einer Antwort rechnen dürfen?

**Comment by beritRLI** [comment]
Um keine Überschneidungen bei der Befragung von Rechtsexperten zu haben (und damit Mehrkosten) haben wir (Absprache Lukas, Berit, Editha) die Befragung von Herrn Jäger verschoben, bis die Antworten von den Juristen des Forschungszentrums Geesthacht zurück sind. Dann werden wir mit den noch offenen Punkten auf Herrn Jäger zugehen.

**Comment by beritRLI** [comment]
Da ich immer noch versuche alle Punkte in einem Dokument zusammenzuhalten kopiere ich hier noch die Punkte aus dem pdf von Lukas hin (sind aber wahrscheinlich oben schon drin). Wir (ich/Ludwig) gehen nächste Woche nochmal alles durch und machen daraus eine Fragetabelle (bzw ergänzen die, die von Geesthacht bearbeitet wird).
Aus pdf:
Offene Fragen an Rechtsexperten:
* Prüfung der Kompatibiliäat einiger häufig genutzter Lizenzen aus Sicht eines Rechtsexperten.
* Handelt es sich bei den von uns erstellten und auf die OEP gestellten Daten um produced work oder eine abgeleitete Datenbank? Dies ist entscheidend für die Bewertung der Nutzung der ODbL.
* Kann der Lizenzgeber auf konkrete Anfragen hin Ausnahmen an der Lizenz zulassen?
* Ist bei Veröffentlichung von osm-Daten in einer unter ODbL lizensierten Datenbank auch das Copyright bei osm-contributors oder beim Veröffentlicher der Datenbank?

**Comment by EdithaK** [comment]
Um die Arbeit am HZG voranzubringen, würden die gerne in die open-eGo GVB einsehen. Es geht darum zu verstehen was die oedb ist und wie die Verantwortlichkeiten definiert werden (können). 
@lukasol @wolfbunke @ulfmueller @MGlauer : Ich würde Personenmonate und Alle finanziellen Punkte herausnehmen und die GVB weiterleiten. Seit ihr damit einverstanden?

**Comment by ulfmueller** [comment]
Aus meiner Sicht, kein Problem!

**Comment by lukasol** [comment]
Reicht es nicht aus, einfach die entsprechenden Punkte aus dem Arbeitsplan zu nehmen? Dann brauchst du nicht so viel löschen...

Grundsätzlich möchte ich mich dafür aussprechen, die Diskussion wieder ins redmine zu verlagern. Schlage Ticket #1178 vor.

**Comment by lukasol** [comment]
General licensing guidelines have been developed and confirmed at a meeting in January. The open questions to the expert will be discussed during a workshop in March.
