### ISSUE TITLE
Include w_id in Generators table in supply

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#272]
Versioned data and model_draft data of v0.4.0 is not identical!

Versioned in supply misses the `w_id`. This affects
- supply.ego_dp_res_powerplant
- supply.ego_dp_res_powerplant_sq_mview
- supply.ego_dp_res_powerplant_nep2035_mview
- supply.ego_dp_res_powerplant_ego100_mview

**Comment by wolfbunke** [comment]
Thanks for checking the error is coursed in the version script. I will check the all columns and add w_id to the supply schema.

**Comment by wolfbunke** [comment]
Fix it in https://github.com/openego/data_processing/pull/273

**Comment by gplssm** [comment]
Thanks :+1:
