### ISSUE TITLE
Storage assignment to eGo 100

### ISSUE THREAD

**Issue by lukasoldi** [openego/data_processing#275]
In #265 we adjusted the storage parameters to be equal for all storages. This is not a problem if all existing storages are of the same technology (pumped hydro in this case). 

In the 'eGo 100' scenario @wolfbunke introduced several new technologies to be part of the system, meaning that neighbouring countries will have hydrogen, battery or compressed air storages. In contrast, these technologies are not introduced to the German system since we want to address this by the extendable storages.

Question: do we want to consider new storage technologies for the 'eGo 100' scenario in neighbouring countries?

If the answer is yes, the script https://github.com/openego/data_processing/dev/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_storage.sql#L345 would have to be changed accordingly. I could come up with a PR in that case.

Please state your opinion!

**Comment by BartelsJ** [comment]
That's a good one. So the new technologies are introduced as options but not regarded yet? As a first opinion I would choose the same technologies like in the other scenarios to ensure comparability. The assumption to use two storage types as equivalents for the variety of storage technologies is also transferable in this case I guess.

**Comment by wolfbunke** [comment]
Hey @lukasoldi,

historically as fare I as I can remember we discussed this issue and end up with using different storage for the market calculation (make it solvable without changing other capacities/ the given scenario) but not using them for the grid optimization. 

In order of having different use cases and a complete list of technologies, I think it would be a good idea to add them.

Documentation: https://github.com/znes/FlEnS/tree/features/ego-timeseries/open_eGo/eGo100
File of Scenario: https://github.com/znes/FlEnS/blob/features/ego-timeseries/open_eGo/eGo100/eGo100.csv

**Comment by ulfmueller** [comment]
Just to be sure I get this right, the eGo 100 new storage technologies are already part of the renpassgis data but are not transferred to the eTraGo power flow input data?

If we have decided that we only want to optimize the storage expansion within Germany and therefore take the planned storage expansion for the future scenarios in the neighboring countries as exogenous assumptions being then fixed and 'god-given', then I would say it would be just logic and consistent to include also these 'other' planned storages for the eGo 100 scenario.

The only downside could be that these storages might be more competitive than the extendable ones inside Germany. @lukasoldi Do you think this would be a problem?

Apart from that everything should be as consistent and correct as possible I would prefer the easiest solution since v0.4.1 is already in the process and future releases within the open_eGo project lifetime are rather unlikely.

@lukasoldi Do you have a preferred solution in mind?

**Comment by ulfmueller** [comment]
> historically as fare I as I can remember we discussed this issue and end up with using different storage for the market calculation (make it solvable without changing other capacities/ the given scenario) but not using them for the grid optimization.

@wolfbunke Is it possible that you are mixing something up? If we do not optimize the storage expansion in the neighboring countries we do have to include their entire energy system exogenously. I think you are thinking about the method we use for the buses within Germany. But those are not of interest in this discussion.

The other option would be to just consider the status quo storages and assume extendable storages for the neighboring countries as well. Then your sentence would make sense.
But this, I think was not what we decided on. correct? We have to document this nicely. In a quick search I could not find it in our documentation (e.g. redmine wiki 'Szenariorahmen'). Maybe one could find it in a protocol. Well, implicitly it is documented by the fact that in the AP3 method the neighboring countries for the extendable storages are not mentioned...

**Comment by IlkaCu** [comment]
> Apart from that everything should be as consistent and correct as possible I would prefer the easiest solution since v0.4.1 is already in the process and future releases within the open_eGo project lifetime are rather unlikely.

Please let me know if you want to include any changes regarding this issue in the v0.4.1 run. I stopped the current run right before the assignment-storage script to include adjustments concerning this issue and #274

**Comment by wolfbunke** [comment]
Ok, it looks like that the storage_id is coursing the problem.

```
SELECT
min(storage_id),
max(storage_id)
FROM model_draft.ego_supply_pf_storage_single;
```
**Results**
|min| max|
|----|-----|
|4267363|4268076|

You can find the code here:
https://github.com/openego/data_processing/blob/release/v0.4.1/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_storage.sql#L345-L348

later more

**Comment by wolfbunke** [comment]
Where we create the storage_id? @IlkaCu @lukasoldi ???

**Comment by IlkaCu** [comment]
The storage_id in model_draft.ego_supply_pf_storage_single is equivalent to the un_id from the powerplant mviews, as you can for example see here: https://github.com/openego/data_processing/blob/release/v0.4.1/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_storage.sql#L152-L155

**Comment by lukasoldi** [comment]
should now be resolved by #284 but remains open until tested.

**Comment by wolfbunke** [comment]
Did you test it?

**Comment by lukasoldi** [comment]
Yes, works fine.
