### ISSUE TITLE
Line 6933 has buses which are not defined

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#288]
In the current data model the 380kV-line '6933' has a bus which is not listed in the bus table (bus_id = 25562) arpound 'Umspannwerk Plattling'. At the corresponding position a 380 kV bus is missing. 

![grafik](https://user-images.githubusercontent.com/16799094/41540680-f623d606-7310-11e8-8218-11b0ddf28704.png)

@ClaraBuettner: You already dealt with a problem in the area of this substation and documented it [here](https://github.com/openego/osmTGmod/issues/10#issue-224491321). Might this bug be related to changes you implemented?

**Comment by IlkaCu** [comment]
It might be a bug somewhere here: https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_fix_ehv_subnetworks.sql#L120-L166

**Comment by ClaraBuettner** [comment]
The line should have been deleted, it was replaced with two other lines which have been created. I'll take a look why that hasn't worked.
