### ISSUE TITLE
control not always set dependend on p_nom?

### ISSUE THREAD

**Issue by jankaeh** [openego/data_processing#293]
I just saw coincidentally, that the control strategy of generators is not consistently PV if p_nom is >= 50 MW and PQ if p_nom is < 50 MW.
I work with v.0.3.2 and there are 6 generators with PV control and p_nom <50 and 300 generators with PQ control despite p_nom >=50

Might this be a bug, or is this planned?

**Comment by ulfmueller** [comment]
Renewables are always PQ. Are the 300 gens big REs?

**Comment by ulfmueller** [comment]
For the 6 below I do not have an idea. @IlkaCu Do you know about this?

**Comment by ulfmueller** [comment]
btw: @jankaeh do you apply non-linear power flow methods on our data model? For the linear power flow methods this is not relevant. This method has been our primary focus...

**Comment by jankaeh** [comment]
And there are some REs with control PV, but as the names are all 2000XY, I guess they are foreign and therefore PV-controlled?

**Comment by ulfmueller** [comment]
yes, that makes sense. We assume that those neighboring countries nodes are PV nodes avoiding big cross-border Q-flows. So from my point of view I would say it is nothing to bother about...

**Comment by IlkaCu** [comment]
I'll check our data model for this bug later today. 
This is where we set the control for generators in Germany: https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_generator.sql#L228-L234

**Comment by IlkaCu** [comment]
As you already mentioned the 6 generators with p_nom < 50 MW and control = 'PV' are generators at the foreign buses. 
The 300 PQ-controlled generators with a p_nom >=50 MW are aggregates of small renewable or conventional power plants. Each of these power plants has an installed capacity <50 MW, but the aggregate may exceed the 50 MW limit. The control is set according to the installed capacity of the single power plant.
