### ISSUE TITLE
Why is id changed to gid?

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#299]
Table `supply.ego_dp_res_powerplant` was formerly equipped with a column `id`. This has now changed for this table and derived mviews in versioned data schemas. It is incompatible with model_draft. Is there a particular reason for this change? @IlkaCu or @wolfbunke

**Comment by wolfbunke** [comment]
No idea why it is now `gid`? From the main script it should be still  ` id`. https://github.com/openego/data_processing/blame/release/v0.4.2/preprocessing/sql_snippets/ego_dp_preprocessing_res_powerplant.sql#L20

**Comment by wolfbunke** [comment]
Also for the MView I can see changes: https://github.com/openego/data_processing/blame/release/v0.4.2/dataprocessing/sql_snippets/ego_dp_versioning_mviews.sql#L109 as well by checking the mview it self.
* supply.ego_dp_res_powerplant_ego100_mview
* supply.ego_dp_res_powerplant_nep2035_mview
*  supply.ego_dp_res_powerplant_sq_mview 
For the conventional power plants it was always called `gid`.

**Comment by gplssm** [comment]
I'm sorry for misleading issue description! It was about the conv tables/mviews. Thanks to @IlkaCu for quickly solving this :+1:
