### ISSUE TITLE
represent the graph of a yEd graphml file in Python

### ISSUE THREAD

**Issue by tillmo** [openego/data_processing#3]
filter for `<graph>`,  `<node>` and `<edge>`.
Create corresponding Python classes: Graph, Node, Edge. Also classes  Pool, Lane (Lane is a subclass of Graph, and basically, Graph and Lane can be considered to be the same).
For each graph, create a Python Graph, for each node, create a Python Node etc.

For each node type, create Python subclass of class Node (e.g. Activity and Event).
How to recognize node types?
for events, look for `com.yworks.yfiles.bpmn.view.EventCharEnum`
for activities, look for `com.yworks.yfiles.bpmn.view.ActivityTypeEnum` 
for data objects, look for `com.yworks.yfiles.bpmn.view.DataObjectTypeEnum`
Generally, look for `com.yworks.yfiles.bpmn.view.*`
Maybe also the `configuration` attributes are useful.

Each activity node (i.e. object of class Activity) should contain a pool attribute, which is either `None` or a pool object (the latter containing in turn lanes, which may contain in turn nodes).

**Comment by apoorva-ovgu** [comment]
python files are uploaded in the draftBranch i.e. at data_processing/bpmn/
name: gmlparser.zip

**Comment by apoorva-ovgu** [comment]
starting point: MakeObjects.py

mutually recursive functions makeGraph and MakeNode in turn call all other functions, apart from each other.
Levels are now maintained and they are no longer flat results.

in order to view all results:
go to <Element>Class.py and uncomment the call to display method

**Comment by MGlauer** [comment]
Please, **do not** upload zip files to a git repository. Git is a text based version control system. It stores the line-wise differences between different versions, i.e. if you add a new line to a file, git stores just that you added this particular line. It does not store the whole new version in order to save memory. 
Changing a single line can lead to huge changes in the corresponding zip-archive. Thus, the git history becomes totally unreadable and git has to a lot of useless information. 

Please remove the zip repository and add your unpacked files.

**Comment by apoorva-ovgu** [comment]
The zip is deleted.
All files are now under openego/data_processing/graphml-parsing/

**Comment by MGlauer** [comment]
Currently, nodes and edges are stored in global node and edge lists - completely independent from their containing graph. This should not be the case. Instead you should store the nodes and edges in the corresponding graph attribute. I.e. extend the `__init__` of `Graph` by a node and a edge list.

I can not find any classes that inherit from Node. The whole purpose of this class is to capture the common structure activities, data objects, and so on.  I.e. Activity and DataObject should inherit from Node and their corresponding `__init__` should call the `super`-function. 
http://www.python-course.eu/python3_inheritance.php

Generally, your objects seem feature quite similar structures and functionalities. This is a huge hint that you should use inheritance. As a general programming advice: If you are writing the same lines of code more than once, you modelled something wrong.

**Comment by MGlauer** [comment]
I tried to draw a UML class diagram for a possible data structure. Maybe this helps you to get a better overview on what we expect.
It is just from the top of my head, so do not expect it to be 100% perfect and feel fre to discuss different design choices. Especially the (Gateway-, Event-, and Connection-) types as enums are not necessarily good and you might have to replace them be separate classes that inherit either from Gateway or Event or Connection if they should feature different functionalities or attributes.

![bpnm](https://cloud.githubusercontent.com/assets/7835111/16192338/f79da5a4-36e8-11e6-8507-bd319f816bcd.png)

**Comment by apoorva-ovgu** [comment]
objects of each type made
