### ISSUE TITLE
Wrong output on nested parallel gateways

### ISSUE THREAD

**Issue by MGlauer** [openego/data_processing#30]
Parallel gateways can be nested arbitrarily. If I execute your program with this [file](https://github.com/openego/data_processing/blob/draftBranch/gmlparsing/double_parallel.graphml) added in 2049a4b I get:

>\>\>\> from gmlparsing.RunTool import run
gmlparsing.RunTool
\>\>\> run()
Executed Successfully!
My file Name------------> /home/martin/Dokumente/Development/open_eGo/data_processing/gmlparsing/double_parallel.graphml

>Event:  EVENT_CHARACTERISTIC_START
Task :  Init
Gateway:  start of Parallel Execution:
Task :  ParallelUpA
Gateway:  end of Parallel Execution
Task :  ParallelDownA
Task :  ParallelDownB
Gateway:  end of Parallel Execution
Task :  Finish
Event:  EVENT_CHARACTERISTIC_END
\>\>\> 

The whole nesting seems to be cropped out.
![double_parallel](https://cloud.githubusercontent.com/assets/7835111/20661076/112677a2-b54d-11e6-9bf2-0d734d41b85f.png)

**Comment by apoorva-ovgu** [comment]
I need some help with the idea here:
How does BPMN distinguish between the start and end parallel Symbol? I mean on a technical leavel, if it was a different symbol, it would be quite obvious but since it is the same it is a little confusing on how to proceed. Both Gateways have incoming as wekk as outgoing edges so that is also not an Option. Do you have any suggestions on how this can be done?

**Comment by MGlauer** [comment]
There is no real "Start" or "End" in a parallel processing. These gateway are just notations for how activations are transferred to the next state. Specifically, a parallel gateway can trigger only if all its inputs are active. If it does, all outgoing edges trigger and all following states becomes active.

From the [BPNM standard](http://www.omg.org/spec/BPMN/2.0/PDF/) p. 294
> A Parallel Gateway creates parallel paths without checking any conditions; each outgoing Sequence Flow receives a
token upon execution of this Gateway. For incoming flows, the Parallel Gateway will wait for all incoming flows
before triggering the flow through its outgoing Sequence Flows.

In a sense they work like combined forks and joins in UML activity diagrams.

**Comment by apoorva-ovgu** [comment]
Closing because nesting is taken care of, and
the possible paths issue covered under the initial 'parallel'  bug.
