### ISSUE TITLE
Only latest version in supply RES mviews

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#302]
The mviews
* supply.ego_dp_res_powerplant_sq_mview
* supply.ego_dp_res_powerplant_nep2035_mview
* supply.ego_dp_res_powerplant_ego100_mview
* supply.ego_dp_conv_powerplant_sq_mview
* supply.ego_dp_conv_powerplant_nep2035_mview
* supply.ego_dp_conv_powerplant_ego100_mview

only contain the latest DP version. This does not allow for long-term reproducibility of ding0/eDisGo data.
As we're querying explicitly one particular version of this data from ding0 and eDisGo, it would be helpful to keep all versions in these mviews.
@wolfbunke and @IlkaCu do you think this would cause any problems?

**Comment by IlkaCu** [comment]
@wolfbunke What do you think? Could you adjust the mviews in the supply schema accordingly?

**Comment by wolfbunke** [comment]
Yes we can remove the  `where version = xxx` query and query this later in the scripts? Or create single views per version? Like: supply.ego_dp_res_powerplant_sq_mview_v0.3.0. 

It is up to you because I don't now if you have everywhere where statements in the DP if using the mviews.

**Comment by wolfbunke** [comment]
changes are done in  #309. Now you have to use a version filter ` where version = xxx `.
The MViews includes the version:

|version|
|--------|
|v0.4.2|
|v0.4.0|
|v0.3.0|
|v0.4.1|
|v0.3.0pre1|

**Comment by wolfbunke** [comment]
The scripts are running now. The MViews` supply.ego_dp_res_powerplant_nep2035_mview ` and  `supply.ego_dp_res_powerplant_ego100_mview` will need view time (20h).

**Comment by wolfbunke** [comment]
This affect the generator import of eDisGo @gplssm @birgits @maltesc

**Comment by wolfbunke** [comment]
I got view connection problems with NEP and eGo Mview creation. At the moments I rolled back to the old version of  ` v0.4.2`. After the eGo release I will start this query  over the week again.

**Comment by IlkaCu** [comment]
@wolfbunke: Please implement the described changes in the current release branch release/v0.4.4. 
Then we can check if it works or not, when executing it as part of the regular DP run.

**Comment by wolfbunke** [comment]
You find the changes in the pull request #313
