### ISSUE TITLE
Fossil capacities in NEP 2035, version 0.4.x

### ISSUE THREAD

**Issue by MarlonSchlemminger** [openego/data_processing#314]
What happened to the conventional generation capacities in Germany in the NEP 2035 scenario from 0.4.0 onwards? This is what is in the dataset:
![cap](https://user-images.githubusercontent.com/22960010/43315786-63f5ee86-9197-11e8-9f5c-42d4a40e8c01.PNG)
Shouldn't there be something like 30 GW of gas and 10 GW of lignite and coal each? At least this is what I find in the NEP itself and in versions earlier than 0.4.0. Is this a (pretty huge) bug?

**Comment by ulfmueller** [comment]
seems to be fixed in 0.4.4
