### ISSUE TITLE
Workalendar

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#32]
The python (pip) package workalendar induces two issues

1. It's missing due to missing entry in `install_requires`
2. Leads to errors during installation on MS Windows machines (tested on Ludwig's computer)

**Comment by Ludee** [comment]
I could solve the workalendar bug on windows.

Update/install current **.NET Framework**, install **visual studio c++** and then update package **setuptools**. Then it has the wheels for workalendar.
