### ISSUE TITLE
ego_scenario_log seems not to exists anymore

### ISSUE THREAD

**Issue by OriolRaventos** [openego/data_processing#324]
The SQL function **ego_scenario_log** is used by 'ego_pre_slp_parameters.sql' (after being called from eGo_preprocessing.py):

https://github.com/openego/data_processing/blob/137f4c1815d8ce7f1987cd0ff01c53c4661e3118/preprocessing/sql_snippets/ego_pre_slp_parameters.sql#L75

Should it be replaces by **scenario_log**?

**Comment by nesnoj** [comment]
I think it was renamed, but @Ludee should be able to answer this.

BTW, there're some usages of [`ego_scenario_log`](https://github.com/openego/data_processing/search?q=ego_scenario_log) ...

**Comment by gplssm** [comment]
True, this function was renamed to `scenario_log()` and its parameters changed slightly. This happened while we were working on the actual data processing without touching the preprocessing again since.
I've fixed it (will fix it for remaining occurrences) in #339
