### ISSUE TITLE
obj_description seems not to be defined

### ISSUE THREAD

**Issue by OriolRaventos** [openego/data_processing#325]
The following SQL function by preprocesing.py  in the ego_pre_slp_parameters.sql:

https://github.com/openego/data_processing/blob/d0c2da7464e02af63edcab627dad934f757038c3/preprocessing/sql_snippets/ego_pre_slp_parameters.sql#L71

seems not to be defined in any part of the module. It is not clear what it should be doing.

**Comment by nesnoj** [comment]
PostgreSQL docs say [`obj_description`](https://www.postgresql.org/docs/9.5/functions-info.html) reads the comment of a table. So it's metadata-related, I think it converts the string comment to json format.
It's used in many (if not all) table creation scripts..

**Comment by OriolRaventos** [comment]
Yes, you are right. I overlooked that.
