### ISSUE TITLE
fix osm import to oedb

### ISSUE THREAD

**Issue by lukasol** [openego/data_processing#33]
import of osm to oedb via osm2pgsql seems to be incomplete. 
Re-check log files and possibly debug necessary.

@Ludee do you have any new insights on this topic, i.e. via openmod-meeting?

see  [data_processing/dataprocessing/tools/osm2pgsql/](url)

**Comment by Ludee** [comment]
did not find anything new about this topic.
I still think its about the style file.

For open_FRED we will need a osm_europe file and can spend a day on it again.
should be before the run of ego v0.2. I put it on my list but cannot promise it.

**Comment by jong42** [comment]
I created a small osm-sample and loaded it into oedb for analysing possible reasons for the incompleteness. When imported into the db via osm2pgsql, some geometries are counted as lines and others as polygons.  Maybe either polygons or lines were not accounted for in later examinations, therefore the data seemed to be incomplete. Does the incompleteness only affect polygons and lines? If so, this could be the reason. @lukasol @Ludee

**Comment by Ludee** [comment]
As far as I understand this is not part of the style file.

**Comment by lukasol** [comment]
Okay, but is it anything we could have an influence on? 
Otherwise, I could try to extend our scripts to also considering substations accounted as lines and see if this brings the full story (but I would like to avoid that since it increases the computational efforts).

**Comment by Ludee** [comment]
An (theoretical) alternative is a modification of the osm2pgsql source code. I don't see that.

What increase of time do you expect? The substation scripts are quite fast (~10min).

**Comment by lukasol** [comment]
I don't see that either. I will try and expand the existing scripts to also considering lines and report on that here.

**Comment by lukasol** [comment]
ways with polygon geometries: 32320
ways with line geometries: 7

The 7 line geometries are not part of the dataset as of now, but at least 5 of them seem to be relevant to us. I thus propose to fix the code (which is a quick thing to do) so that we also include the lines and to re-run the data_processing v.02 with the updated dataset.

**Comment by lukasol** [comment]
resolved by https://github.com/openego/data_processing/commit/0658df96684a3ea0443df1d533d3ed2b072bd5bb
