### ISSUE TITLE
update BPMN about structure (script order) of the preprocessing

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#336]
In #327 the workflow of the preprocessing started to be described by `ego_dp-pre_bpmn_sections.graphml`.
Add sections created in #329 #331 #333 #335 .

Make dependencies of sections clear (i.e. cosmoclmgrid > supply).

Allow parallel branches in the workflow if parts are independent.

**Comment by gplssm** [comment]
It's almost finished. See `/home/guido/rli-lokal/294_eGon/Aufbereitung Data Processing Dokumentation/tmp_BPMN_example/ego_dp-pre_bpmn_sections.graphml`

**TODOs**

- [x] Replace dashed arrow by solid arrow

**Comment by IlkaCu** [comment]
I replaced the dashed arrow by a solid one, pushed this change and will convert the related draft to a proper PR.

**Comment by IlkaCu** [comment]
PR #363 fixed this issue.
