### ISSUE TITLE
header and license

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#34]
On the [oemof developer meeting - Berlin, December 6, 2016 #218](https://github.com/oemof/oemof/issues/218) we decided on a standardised header for code and scripts.

Until now we only have a template for python and sql but should be easy to adapt to other languages.
I suggest to use and implement it in v0.2.

Any additions and comments?

**Comment by lukasol** [comment]
We decided on applying the standard header to all scripts in version 0.2. Each author is responsible for filling his/her script. This can be a default (for license and copyright) in the first place, at least author should be filled (with github user name or clear name).

**Comment by Ludee** [comment]
The template is in the [wiki](https://github.com/openego/data_processing/wiki/Header-and-License)

**Comment by nesnoj** [comment]
Taken from #35:

> Um die Header leichter anzupassen hat Guido was gebaut: https://gist.github.com/gplssm/95e703bf4afc64c7d276bc755951ec17
> Thx to @gplssm!

Do we use the header for data processing only or for all of our packages? In data proc it is quite reasonable due to the heaps of developers. In other repos like dingo I'd propose to keep it optional..

**Comment by ulfmueller** [comment]
Good question. As far as I understand it, we have only decided on it concerning the data proc. When we decide on the license issue at the project meeting this question will be probably consequently tackled as well (right @lukasol ?).

**Comment by lukasol** [comment]
As discussed at the project meeting last week, the data_processing is now licensed under AGPLv3. I updated the license file and would now ask all authors to update the headers of their scripts (see [wiki](https://github.com/openego/data_processing/wiki/Header-and-License))

- [ ] @Ludee 
- [ ] @nesnoj 
- [ ] @ulfmueller 
- [ ] @IlkaCu 
- [ ] @wolfbunke 
- [ ] @s3pp 
- [ ] @gplssm 
- [ ] @lukasol

Since we decided to release v0.2 soon, it should be sufficient to insert headers in the branch refactor/oedb-restructuring_v0.2

**Comment by Ludee** [comment]
I have some comments on the license: I like the decision and I go with AGPL.

Here my comment from Redmine in German:

Gibt es auch eine Entscheidung zur CLA?
Die Lizenz empfiehlt sowas am Ende
Es wäre schön da eine übergreifende Lösung zu haben und nicht je eine per Institut.
Das würde eine zukünftige Mitarbeit anderer erschweren.

Zudem schlage ich eine kleine Anpassung des Headers vor:
```sql
__license__ = "GNU Affero General Public License Version 3 (AGPL-3.0)" 
__url__ = "https://github.com/openego/data_processing/blob/master/LICENSE" 
```
Anpassung der Groß/Kleinschreibung und Auslagerung des Links in url.

**Comment by Ludee** [comment]
I adjusted the "template in the wiki":https://github.com/openego/data_processing/wiki/Header-and-License

**Comment by s3pp** [comment]
Updated the Wiki, removed whitespace.

**Comment by Ludee** [comment]
thanks

**Comment by Ludee** [comment]
@nesnoj
@ulfmueller
@IlkaCu
@wolfbunke
@s3pp
@gplssm

**Comment by wolfbunke** [comment]
work in progress

**Comment by nesnoj** [comment]
Alright, I've added some license headers for @gplssm and @jong42 (I surely missed some).

Useful hint: If you want to check which files a user has contributed to within the repo, you can use
```
git log --no-merges --author="<USER>" --name-only --pretty=format:"" | sort -u
```
Just replace the git \<USER>. Of course, this includes all modifications (e.g. "fix typo" ;)

**Comment by IlkaCu** [comment]
There are four sql scripts without a header left in the snippets-directory in the oedb-restructuring_v0.2 branch. 
- [ ] analyse_grid_district_data.sql
- [ ] analyse_osm_landuse.sql
- [ ] calc_renpass_gis.pf_pp_by_source_aggr_id_mview_backup.sql
- [ ] setup_openstreetmap.sql

@Ludee: Are you the author of these scripts? If yes, please add the header.

**Comment by s3pp** [comment]
calc_renpass... seems to be a part of renpass_gis_ResultsTOPF.sql with minor changes.

@Ludee Should I integrate these changes in the main script?

**Comment by Ludee** [comment]
@IlkaCu Yes, all mine. sorry.

@s3pp The Backup was made because I had to change some code during the execution of the dp.
If you don't need the backup anymore, just delete it. I suggest to not merge the backup in the updated/improved part.

I will add the header and licenses after I pulled the restructured repo. Can't do it right now because the peak loads are running.

**Comment by Ludee** [comment]
analyse_grid_district_data.sql -> moved all mvgd results to **ego_mv_griddistrict_results**
analyse_osm_landuse.sql -> integrated
calc_renpass_gis.pf_pp_by_source_aggr_id_mview_backup.sql -> deleted
setup_openstreetmap.sql -> add license and move to import
