### ISSUE TITLE
there is no DP preprocessing BPMN documentation about renpassG!S tables

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#345]
Please add a BPMN explaining how the tables

* calc_renpass_gis.renpass_gis_storage
* calc_renpass_gis.renpass_gis_linear_transformer
* calc_renpass_gis.renpass_gis_source
* calc_renpass_gis.renpass_gis_results

are created.

**Comment by IlkaCu** [comment]
There is another renpassGIS related table without any documentation: model_draft.renpass_gis_parameter_region

**Comment by gplssm** [comment]
Resolved by #370
