### ISSUE TITLE
there is no DP preprocessing BPMN documentation about wind potential table

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#347]
Please add a BPMN explaining how the table

* supply.soethe_wind_potential_area

gets created.

**Comment by IlkaCu** [comment]
I guess you refer to this table: supply.vernetzen_wind_potential_area

**Comment by IlkaCu** [comment]
The table supply.vernetzen_wind_potential_area was created in the project VerNetzen. Therefore we can treat it as an input table in our dataprocessing and in the corresponding BPMN documentation.

**Comment by gplssm** [comment]
> The table supply.vernetzen_wind_potential_area was created in the project VerNetzen. Therefore we can treat it as an input table in our dataprocessing and in the corresponding BPMN documentation.

True. But, i'd like to be able to run the pre-processing from scratch, see #339. Therefore, it would be great to realized one of these options:

1. Run the vernetzen code as part of the DP pre-processing
2. Save the supply.vernetzen_wind_potential_area data permanently somewhere else (i.e. Zenodo) and download and import via script from there

What do you think? Is (1) far from possible? Would option 2 be legally ok?

**Comment by IlkaCu** [comment]
As we already discussed in one of our last web conferences (26 March 2020) I would propose making use of 'external' OEP tables as input data for the preprocessing.

**Comment by gplssm** [comment]
:ok_hand: just as a safety measure and for easing the automization of the DP-pre, I saved the table as `.shp`  (d33f8444365078cf3ebc6cb3fc7a7f1792920003) and provided it downloadably. Furthermore, it was added to the DP-pre from scratch script (c80c3e4f511b731a715d02091265ea3edfe3369b).
