### ISSUE TITLE
direct use of mview

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#36]
a duplicate mview is created. remove mview and directly use political_boundary.bkg_vg250_1_sta_union_mview

https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/sql_snippets/get_substations.sql#L170-L178

**Comment by lukasol** [comment]
resolved by: https://github.com/openego/data_processing/commit/9babc74b10f9b9d259f2551ccba2713718fa3886
