### ISSUE TITLE
osm loads industry

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#38]
demand.ego_demand_federalstate
economic.destatis_gva_per_district

https://github.com/openego/data_processing/blob/284ef8edd2c774db30625e670eb0d8fb638c8b7c/dataprocessing/sql_snippets/process_eGo_osm_loads_industry.sql#L41-L42

Die beiden Tabellen existieren nicht. Die Übersetzungstabelle zeigt die beiden alten Tabellen:
orig_ego_consumption.destatis_gva_per_district
orig_ego_consumption.lak_consumption_per_federalstate
Habe die in die richtigen schema verschoben und die namen im Skript angepasst.

-> Tabellen umbenennen und im Skript anpassen

**Comment by Ludee** [comment]
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "supply.ego_conv_powerplant" does not exist. LINE 454: FROM supply.ego_conv_powerplant;

https://github.com/openego/data_processing/blob/284ef8edd2c774db30625e670eb0d8fb638c8b7c/dataprocessing/sql_snippets/process_eGo_osm_loads_industry.sql#L478

Ohne Übersetzungstabelle könnte ich die Bugs nicht so schnell lösen. Das hat sich gelohnt.
-> supply.opsd_power_plants_germany

**Comment by Ludee** [comment]
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) missing FROM-clause entry for table "proc_power_plant_germany" LINE 461:   proc_power_plant_germany.gid AS powerplant_id,

Ich gehe davon aus, dass das ebenfalls die opsd Kraftwerke sind!?

**Comment by Ludee** [comment]
`DROP TABLE IF EXISTS model_draft.ego_demand_hv_largescaleconsumer CASCADE;
CREATE TABLE model_draft.ego_demand_hv_largescaleconsumer AS
	(
	SELECT	osm_deu_polygon_urban_sector_3_industrial_mview.gid AS polygon_id,
		osm_deu_polygon_urban_sector_3_industrial_mview.area_ha AS area_ha,
		proc_power_plant_germany.gid AS powerplant_id,
		proc_power_plant_germany.voltage_level AS voltage_level
	FROM 	supply.opsd_power_plants_germany, 
		openstreetmap.osm_deu_polygon_urban_sector_3_industrial_mview
	WHERE	(voltage_level='3' OR voltage_level='2'OR voltage_level='1')
	AND 	ST_Intersects (proc_power_plant_germany.geom, (ST_transform (osm_deu_polygon_urban_sector_3_industrial_mview.geom,4326))));`

**Comment by Ludee** [comment]
scenario log:
196;0.2.1;input;demand;lak_consumption_per_federalstate;process_eGo_osm_loads_industry.sql;17;OK
197;0.2.1;input;economic;destatis_gva_per_districts;process_eGo_osm_loads_industry.sql;446;OK
198;0.2.1;output;model_draft;ego_demand_per_gva;process_eGo_osm_loads_industry.sql;17;OK
199;0.2.1;input;political_boundary;bkg_vg250_4_krs_mview;process_eGo_osm_loads_industry.sql;432;OK
200;0.2.1;output;model_draft;ego_landuse_industry;process_eGo_osm_loads_industry.sql;61291;OK
201;0.2.1;input;orig_geo_powerplants;proc_power_plant_germany;process_eGo_osm_loads_industry.sql;900;OK
202;0.2.1;input;calc_ego_substation;ego_deu_voronoi_ehv;process_eGo_osm_loads_industry.sql;435;OK
203;0.2.1;input;model_draft;ego_grid_hvmv_substation;process_eGo_osm_loads_industry.sql;3606;OK
204;0.2.1;output;model_draft;ego_demand_hv_largescaleconsumer;process_eGo_osm_loads_industry.sql;189;OK

**Comment by ulfmueller** [comment]
I think @IlkaCu (plus maybe a consultation to @wolfbunke) can help here the best.

**Comment by Ludee** [comment]
Bitte bis 22.12 14:00 klären!

**Comment by IlkaCu** [comment]
I'll try to fix this bug today!

**Comment by IlkaCu** [comment]
We forgot to move the input tables from the old to the v0.2 db-structure. Therefore some input tables were missing. I renamed the input tables in the script to the names mentioned in the translation document '2016-12-15_Umstrukturierung_oedb.ods'. To be able to execute the script the following tables need to be moved to the the new db-structure: 

orig_geo_powerplants.proc_power_plant_germany --> supply.ego_conv_powerplant
orig_ego_consumption.destatis_gva_per_district --> economic.destatis_gva_per_district

@wolfbunke: Could you copy these to tables to the new db-structure?

**Comment by Ludee** [comment]
**economic.destatis_gva_per_district** ist schon da, der PK kann noch angepasst werden (CONSTRAINT verbrauch_pkey PRIMARY KEY (eu_code))

wie geht es weiter? Ich warte auf @wolfbunke?
was ist mit dem zweiten Teil? Wer macht da den Debug?

**Comment by lukasol** [comment]
soweit ich weiß ist @wolfbunke dieses jahr nicht mehr im hause. kann das nicht jemand anderes übernehmen?

**Comment by Ludee** [comment]
wird per E-Mail diskutiert. Noch offen

**Comment by lukasol** [comment]
@Ludee @IlkaCu @ulfmueller  
is this still open?
(I'm preparing for the meeting...)

**Comment by Ludee** [comment]
Im eGoDP wurden die angepasst. Es fehlen aber noch die Lizenz in den Metadaten und die Ergänzung im BPMN für das License-Flow.

**Comment by Ludee** [comment]
economic.destatis_gva_per_district  -> "Licence": ["unspecified licence"],
demand.ego_demand_federalstate  -> "ToDo": ["Add licence"],
@IlkaCu @ulfmueller

**Comment by Ludee** [comment]
I think this is necessary for v0.2

**Comment by IlkaCu** [comment]
I added the licence information to the named tables.

**Comment by IlkaCu** [comment]
In the following SQL snippets I found some references to tables in the old db schema: 
[process_eGo_lv_streets.sql](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/process_eGo_lv_streets.sql#L18-L19) @Ludee @jong42 
[LOPF_data.sql](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/LOPF_data.sql#L84) @s3pp 

Please check whether this is a bug or intended.

**Comment by nesnoj** [comment]
Thanks for digging :).
There's some unused LV stuff I'll clean up until the 10th.

**Comment by Ludee** [comment]
Status?
