### ISSUE TITLE
given BPMN representation, execute it 

### ISSUE THREAD

**Issue by tillmo** [openego/data_processing#4]
* successively print the activities' names on the screen
* recursively process subgraphs
* for decisions, decide arbitrarily

**Comment by apoorva-ovgu** [comment]
This is the problem we are facing:
When graphml code is created, the node numbers(for eg. n0::n1) assigned to each object(events, data objects etc) are in the order they were created in the graphml file. So there is no way to track which object is before or after what. The only way is by using style-position information.

This is something we could think of but is too naive:
1. we have horizontal swimlanes: so separate objects w.r.t. y axis
2. gather all objects within a swimlane (at this point we do not have an order of objects)
3. Sort them according to the edge source and destinations (as per prototype: file createLink.py in draftbranch)

Please let us know if an easier way exists to do this.

**Comment by MGlauer** [comment]
> So there is no way to track which object is before or after what.

I do not really get what you are trying to do here. Why are you trying to sort the nodes? 

You already parsed the edges with their corresponing source and target attributes.
From my point of view the execution should start at the topmost start event and afterwards iterates throug a single series of possible state configurations.

**Comment by apoorva-ovgu** [comment]
Yes, I used this concept in the above file and it worked, now we simply have to use it on our file.
But when you see the diagram as a whole, say there are 5 start and end nodes, how can you decide which sequence to display first. For that, I thought, the sorting would be required. If this sequence doesn't matter then we'll continue this itself.

**Comment by MGlauer** [comment]
You can not start an execution at any arbitrary activity as you can not start a program at a random line of source code. A BPMN diagram is always started by an event. For starters, you can assume that this diagram is a designated start event that is denoted by "EVENT_CHARACTERISTIC_START" as seen here: https://github.com/openego/data_processing/blob/draftBranch/gmlparsing/ego_deu_loads_per_grid_district.graphml#L234

**Comment by apoorva-ovgu** [comment]
Perhaps I wrote it in a misleading way.
In this file, we have a total of 8 EVENT_CHARACTERISTIC_STARTs and their respective intermediate ends: EVENT_CHARACTERISTIC_INTERMEDIATE_CATCHING.
2 of these are within other nodes.
As for the other 6 EVENT_CHARACTERISTIC_START, and ends, can they be arbitrarily executed?

**Comment by MGlauer** [comment]
The current example contains six lanes, which should be ignored for now. Thus, several initial states should be handled by selecting one at random.

**Comment by apoorva-ovgu** [comment]
Okay, that's what I wanted to know. Thanks.

**Comment by tillmo** [comment]
Please note that there are sub processes with seperate start (and end) nodes. These should not be randomly chosen as start nodes, but should be processed when a node calls the sub process.

**Comment by apoorva-ovgu** [comment]
sub processes are now a part of the main process
