### ISSUE TITLE
MV Grid District with no consumption

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#41]
There is (only) one mvgd with no consumption. It is because all LA are really small.
It is subst_id 506

![grafik](https://cloud.githubusercontent.com/assets/14353512/22255578/0e7511fc-e258-11e6-8cc0-9230187b321e.png)

**Comment by nesnoj** [comment]
Uh, odd...for dingo.
Is there a threshold for the min. consumption of a load area? That's the only explanation since all LA are supposed to have a consumption..

**Comment by IlkaCu** [comment]
I'm pretty surprised that this happened. There is no threshold implemented, so every load area should have a consumption in the end no matter how little. I'll try to fix this bug starting tomorrow.

**Comment by Ludee** [comment]
My guess is a rounding error. I already had some issues with _decimal_ data type which is not suited for small fractions (<10*-5). Since it's GWh it might be it. Instead try the _double precision_. 
Can't find the source I got this from, some Stack question. Hope it helps and can be fixed quick.

**Comment by Ludee** [comment]
Did you find the bug?

**Comment by IlkaCu** [comment]
The data type _numerical_  in table model_draft.ego_demand_loadarea seems to cause the problem. As a view uses this table I do not have the permission to simply change the data type and rerun the script. @Ludee: Is it okay for you, if I delete the table once completely?

**Comment by Ludee** [comment]
Since this script(s) may take a while I suggest to just update the code and make a new run after merging with a new version number.

**Comment by nesnoj** [comment]
There're actually quite a lot LA with no consumption and hence no peak load (in almost every GD).
So this one will be fixed during next run?!

**Comment by IlkaCu** [comment]
I changed the data types of the sector_consumption_ columns [here](https://github.com/openego/data_processing/blob/67df9434e27926d347e396b8ab7736721c6268b5/dataprocessing/sql_snippets/process_eGo_loads_per_grid_district.sql#L44-L48). With the next run of this and all depending scripts the bug should be fixed - at least I hope so.

**Comment by nesnoj** [comment]
We got quite a lot grid districts where load areas are quite small and scattered, e.g. id=744:

![mvgd_peak_load_scatter](https://cloud.githubusercontent.com/assets/15910173/23157316/f7769466-f81a-11e6-9313-e07bb7dbdf6d.jpg)

I'm curious whether all of them will be fixed..

**Comment by IlkaCu** [comment]
After re-running the demand allocation I found 93142 loadareas without any assigned consumption. 
I checked the data and noticed that these loadareas do not have a population neither they have entries for _sector_area_retail_, _sector_area_industrial_ or _sector_area_agricultural_ - which is essential to achieve a consumption > 0 for these load areas.

**Comment by Ludee** [comment]
Very interesting analyse! Thanks

So we have OSM landuse residential but no registered population from census 2011 in it.
Did you do some sample checks with satellite images?

Guesses:
There are too many LA to be only new houses built after 2011 (Neubaugebiete).

**Comment by IlkaCu** [comment]
It seems to be a bug in the generation of load areas. For the yellow load areas with sector_consumption_sum = 0 in table _model_draft.ego_demand_loadarea_ zensus_sum is NULL, but the view _social.destatis_zensus_population_per_ha_mview_ reveals a population >0 for the same area. Any suggestions how this happened? 
![bildschirmfoto vom 2017-03-20 13 09 58](https://cloud.githubusercontent.com/assets/16799094/24099370/194cb91c-0d6f-11e7-8af4-3e5441370442.png)

**Comment by IlkaCu** [comment]
An addition: 
sum(zensus_sum) in _model_draft.ego_demand_loadarea_: 65,297,049
sum(population) in  _social.destatis_zensus_population_per_ha_mview_: 80,324,282

**Comment by Ludee** [comment]
Did you run the consumption part again? @IlkaCu

**Comment by IlkaCu** [comment]
After your bugfix two days ago I didn't run the consumption part again. Was that the answer to your question?

**Comment by Ludee** [comment]
OK, then it will be executed on the new run tomorrow.
