### ISSUE TITLE
REA allocation issues

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#45]
I got some issues on REA allocation:

- [x] Bug: The column voltage_level in orig. table `supply.ego_res_powerplant` is of type smallint but after allocation (table `model_draft.ego_supply_rea`) it is character varying. Furthermore, in all scripts concerning the allocation a string containing a number is used for comparison (luckily, postgreSQL is very gracious here) - I recommend to change this nevertheless.
- [x] Bug: In the REA aggregation part of [ego_rea_results.sql](https://github.com/openego/data_processing/blob/7e794cd5cbde9468c244e5bd73a246c707db7103/dataprocessing/renewable_energy_allocation/ego_rea_results.sql#L107) an outdated voltage_level string is used for comparison - this leads to a faulty result on HV level.
- [x] The [BPMN](https://github.com/openego/data_processing/blob/1a3945956a0a27a2807580abafa6a4c3ab5f28b7/bpmn/ego_data_processing.graphml) currently lacks a description of the output table(s) as done in the substation part (green symbols).

I'll take care of 1+2

**Comment by nesnoj** [comment]
1. done in 0d1b27d233d38411e0105fa707af73c94038bd08
2. done in b8eea7fb850e912adec206c9550596f4fdfa92b2

Due to those bugs the whole alloc has to be re-run..

**Comment by Ludee** [comment]
I will do 3.

**Comment by nesnoj** [comment]
@Ludee, can I re-run the alloc [starting from `ego_rea_setup.sql`](https://github.com/openego/data_processing/blob/a1744b86b77de5931ac5940cabd8c31416db5085/dataprocessing/ego_renewable_energy_allocation.py#L43) by the end of the day?
@IlkaCu @lukasol @wolfbunke Please notify if there're any objections..

**Comment by Ludee** [comment]
Of course you can. Did it work?

**Comment by nesnoj** [comment]
I started it yesterday and it ran successfully until `ego_rea_m4.sql` (see scenario_log) but `ego_rea_m5.sql` didn't finish - I guess this is related to timeout (python stating "SSL SYSCALL error: EOF detected"). If it doesn't bother you too much I'd be happy if you could run it again starting from `ego_rea_m5.sql`...

**Comment by Ludee** [comment]
just finished m5 and results from dev

**Comment by nesnoj** [comment]
Cheers mate!

**Comment by Ludee** [comment]
BPMN of the REA has been updated in _dev_
