### ISSUE TITLE
Wanted: Hints on DATA MODIFICATIONS

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#46]
I'm using datasets from dp v0.1 since there's still missing data in v0.2 (peak load #44 and MV/LV substations) - I'm fine with 0.1 for testing DINGO's algorithms.

Unfortunately the old load areas (`calc_ego_loads.ego_deu_load_area`) & peak loads (`calc_ego_loads.calc_ego_peak_load`) suddenly contain a lot of NULLs in consumption/peak_load - what happened here? Did somebody run an old v0.1 script?

**Comment by Ludee** [comment]
I didn't run any v0.1 for a long time.
Perhaps there was something in the peak load I tried to run. But it failed all the time.
Otherwise I have no clue?
