### ISSUE TITLE
bugs in REA voltage_level allocation

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#48]
**Bug 1**
I found a lot of entries in the table `supply.ego_res_powerplant` where the allocation of REA to their voltage level seem to be odd ([our allocation table](http://oep.iks.cs.ovgu.de/redmine/projects/open_ego/wiki/Methoden_Zuordnung_von_Erzeugern_und_Verbrauchern_zu_Spannungsebenen_und_Netzknoten)).
Example: Just try
```
SELECT count(id)
  FROM supply.ego_res_powerplant
  WHERE voltage_level = 5 AND electrical_capacity < 10;
```
This will return 2634 very small plants (P<10 kW) which are to be allocated to voltage_level 7 (LV), not 5 (MV). I guess there're a lot more datasets affected..

Same bug can be found in the prior table `supply.ego_renewable_power_plants_germany` and the prior table of the prior table from opsd `orig_geo_opsd.renewable_power_plants_germany` (Strangely enough in those 2 tables there are 2660 entries for the query above :open_mouth: - wait..what?

So where does this come from? From the original EnergyMap/KW-Liste dataset? If so, I guess we have to replace the original entries (at least for the distribution grid).

**Bug 2**
I found another bug in a script, voltage level 7 is wrongly allocated (>100 kW), see [here](https://github.com/openego/data_processing/blob/a2126af5b624fcda73bf2e3e0332634e8d3831f8/orig_geo_powerplants/proc_renewable_power_plants_germany.sql#L68). I'm not sure if this is the latest script for the allocation..?!

**Bug 3**
This is rather a comment: [Here](https://github.com/openego/data_processing/blob/a2126af5b624fcda73bf2e3e0332634e8d3831f8/orig_geo_powerplants/proc_power_plant_germany.sql#L310-L328) you assign the voltage level according to the capacity (same as in REA). But in the conventional PP table the unit is MW, hence e.g. `BETWEEN 0 AND 0.099` (v_level = 7) and `BETWEEN 0.1 AND 0.29` (v_level = 6) will exclude 1 kW of the range. This probably does not affect any plants but I don't want to leave this unmentioned..

Alright, that's it.

**Comment by IlkaCu** [comment]
We did not adjust the voltage level of those power plants having an entry on this in the original datasets. If this is not suitable for DINGO we should discuss whether to adjust the voltage level of all power plants according to our allocation table or identify and adjust only the outliers.

>  Bug 2
I found another bug in a script, voltage level 7 is wrongly allocated (>100 kW), see here. I'm not sure if this is the latest script for the allocation..?!

I fixed this bug on the dev branch. Thanks!

**Comment by nesnoj** [comment]
I think there is no difference between the two options if we use our allocation table as reference, is there?

Let's check the counts per v_level for P<100 kW:

v_level | count | sum capacity
--------- | ------- | ----------------
1 | 4 | 20.69
2 | 3 | 143.93
3 | 85 | 3405.645
4 | 46 | 2060.824
5 | 18592 | 809030.060
6 | 11005 | 466155.741
7 | 1504806 | 20055134.762

In this example the allocation is wrong for 2% of the PP (but 6% of the capacity!).
Quite clear is that - in this case - allocations to v_level 1-4 are just odd. But I'm not sure about the fluid boundaries in 5-7.

**Comment by IlkaCu** [comment]
I do see a difference between both options - as you said for power plants < 100 kW an allocation to the voltage levels 1-4 would be odd and unrealistic. They are for sure outliers. But it isn't completely unrealistic to have PP like this in voltage level 5 or 6, is it? We could keep the information on the voltage level for these PP and only adjust the outliers.
But from my point of view we could also argue that the data base is inaccurate and we use our allocation table for all PP.

**Comment by nesnoj** [comment]
Yes I guess some scenarios aren't completely unrealistic but it is hard to define better thresholds than used in the dena VNS to detect outliers.
I did a more detailed inspection checking the allocation of capacity classes (<1 MW) to v_level with
```
WITH ranges AS (
    SELECT (ten*100)::text||'..'||(ten*100+99)::text||' kW' AS range,
           ten*100 AS r_min, ten*100+99 AS r_max
      FROM generate_series(0,9) AS t(ten))
SELECT s.voltage_level, r.range, count(s.*)
  FROM ranges r
  LEFT JOIN supply.ego_res_powerplant s ON s.electrical_capacity BETWEEN r.r_min AND r.r_max
 WHERE s.electrical_capacity < 1000
 GROUP BY s.voltage_level, r.range
 ORDER BY s.voltage_level, r.range;
```
In v_levels 5 and 6 most of the allocated PP are from capacity classes different from the range in our alloc table.

I'd recommend to apply our alloc table to all PP - could you update your script plz?

**Comment by IlkaCu** [comment]
All right! I'll adjust the script tomorrow morning. But these changes will influence the whole data processing. How do we deal with that?

**Comment by nesnoj** [comment]
Great - thanks!
We've to re-run some parts of dp v0.2 anyway for different reasons ([example](https://github.com/openego/data_processing/issues/45#issuecomment-278338513))...and in the end a whole re-run is on schedule too prior to the release?!
I'd appreciate if we could do this very soon..

**Comment by IlkaCu** [comment]
I adjusted the script _proc_renewable_power_plants_germany.sql_ on the dev branch and ran the essential part to update table _supply.ego_res_powerplant_. 

Is this bug also an issue for the conventional PP list?

**Comment by nesnoj** [comment]
Looks good, thank you.
Yes indeed, the conv. PP contains a lot of odd entries like PP with cap<20 MW allocated to v_level 1.
U can check with
```
WITH ranges AS (
    SELECT (ten*10)::text||'..'||(ten*10+9)::text||' MW' AS range,
           ten*10 AS r_min, ten*10+9 AS r_max
      FROM generate_series(0,9) AS t(ten))
SELECT s.voltage_level, r.range, count(s.*)
  FROM ranges r
  LEFT JOIN supply.ego_conv_powerplant s ON s.capacity BETWEEN r.r_min AND r.r_max
 WHERE s.capacity < 100
 GROUP BY s.voltage_level, r.range
 ORDER BY s.voltage_level, r.range;
```
I'd recommend to apply our table to conv. PP too..

**Comment by IlkaCu** [comment]
Done!
I adjusted the script and updated table _supply.ego_conv_powerplant_

**Comment by nesnoj** [comment]
Thanks for updating!
**Note:** In the table there're some PP in v_level 3 which have got no capacity (empty)..
If there's no further need for discussion you might close this issue.

**Comment by IlkaCu** [comment]
I had to reopen this issue. We came up with one reason against using the allocation table for all generators. In case of wind power plants pooled in a wind park the allocation table is not applicable as they are usually connected to a voltage level according to the installed capacity of the wind park.

**Comment by nesnoj** [comment]
Uhh yes, we didn't take this into account...
So we r to decide whether we simply roll-back changes or if we re-allocate tech-specific. Could you plz re-create the old table data in a temporary table to allow for some re-analysis?

**Comment by IlkaCu** [comment]
You can find the old results in _orig_geo_powerplants.proc_renewable_power_plants_germany_
We could keep the voltage_level information for wind power plants and overwrite it for the remaining technologies based on the allocation table. For wind power plants the voltage_level seems to be well-maintained - we only found two wind power plants without a voltage_level information in the original data set. 
I already analysed the voltage_levels for wind power plants with generation_subtype = 'wind_onshore'

v_level | count 
--------- | -------
1 | 736
2 | 30
3 | 7232 
4 | 2127
5 | 13535 
6 | 382 
7 | 1128

**Comment by IlkaCu** [comment]
We could also allow wind power plants to be connected to higher voltage levels than the one identified by our allocation table, but not to lower ones.

**Comment by Ludee** [comment]
also consider new issue #58

**Comment by nesnoj** [comment]
In this context I assume "higher" means higher voltage (e.g. 2 MW WEC, v_level=5 can be allocated to v_level 4).
This seems to be a reasonable approach but I'm still struggling...
Example: We got 9979 plants whose nom. capacity is <17.5 MW (to be v_level 4..7) with v_level tag = 1,2 or 3 (in sum 23.8 GW). Ok, most is wind, after filtering (allowing for your proposal and exclude offshore) we still got 669 plants (~1.9 GW) left. 86% of the remaining plants are PV in v_level 3 (avg. capacity of 4 MW). Seems odd?!

**Comment by nesnoj** [comment]
I guess we cannot really solve this one satisfying. To finish quickly I propose:
We take the v_level of WEC as given in the original dataset as suggested by you and use our allocation table for the rest.
Ok?

**Comment by IlkaCu** [comment]
Then I apply our allocation table for all technologies except for wind. In the case of wind_onshore I would keep the 'original' voltage level from the power plant list, except for those plants assigned to a voltage_level higher than the one suggested by the allocation table.
