### ISSUE TITLE
consistent use of status quo scenario

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#49]
For the status-quo scenario we decided to go for 2014. I'm not sure if the same year is implemented consistently:

1. Demand: It seems to be 2013 (see [here](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/python_scripts/demand_per_mv_grid_district.py#L25) or [here](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/python_scripts/peak_load_per_load_area.py#L39))
2. Weather: 2011 (average weather year)
3. Generation: The PP datasets e.g. `supply.ego_renewable_power_plants_germany` states "31.12.2015" - does anybody actually filter these datasets?
4. OSM: 01.10.2016
5. ...more?

Comments, additions?

**Comment by lukasol** [comment]
from the grid's perspective, Status-Quo means the download date of the actual OSM dataset applied.

**Comment by nesnoj** [comment]
Ok, I added OSM

**Comment by IlkaCu** [comment]
The original data on electricity demand taken from the statistical offices are from the year 2011. The reference year for our weather data is as well 2011.

**Comment by wolfbunke** [comment]
Hi @nesnoj a description of our "basic" Scenario parameters can be found in the project redmine: http://oep.iks.cs.ovgu.de/redmine/projects/open_ego/wiki/Szenariorahmen. In the next weeks we should update our parameter because many new things came additional along.

**Comment by nesnoj** [comment]
Further discussions could take place at next project meeting

**Comment by IlkaCu** [comment]
Shall we discuss this topic at the upcoming project meeting? Or is it already obsolete?
