### ISSUE TITLE
Not connected lines in model_draft.ego_grid_pf_hv_line

### ISSUE THREAD

**Issue by s3pp** [openego/data_processing#50]
The following query statement results in two entries, both lines are only on one side connected.
Connected to the same bus, which bus_id is 19519. 

```SQL
select * from model_draft.ego_grid_pf_hv_line where bus0 is null or bus1 is null
```

@lukasol Is this a bug? Or is it something that is allowed to happen?

**Comment by lukasol** [comment]
sorry for late reply...i didn't get a notification.

i can reproduce the two lines also with the latest status of the grid topology model. generally i'd say it should not happen and is a bug (there is also no geom of the lines). is it something that affects calculations? i could just insert a query deleting one side connected lines...?!

**Comment by ulfmueller** [comment]
I do not know this problem precisely. But it definitely affects PyPSA pf calculations. Lines always have to be connected at both ends otherwise PyPSA will rise an error.
Yeah, please insert that query deleting such lines because they'll only cause problems!

**Comment by lukasol** [comment]
i just deleted the respective lines in the datasets in model_draft and grid schema.

will update the code on that now.

**Comment by ulfmueller** [comment]
Can you insert the same 'check and delete' for transformers? That would be convenient.

**Comment by lukasol** [comment]
transformers are automatically included, since they are part of branches/lines.

i added the deletion query to the code, should not occur any longer.
