### ISSUE TITLE
allocation of REA to LV grid districts

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#52]
I'd like to allocate all REA from `model_draft.ego_supply_rea` which are allocated to a LV load area (la_id) to the subjacent LV grid districts. I'd create a new table and use your [snippet from `ego_rea_m5.sql`](https://github.com/openego/data_processing/blob/a1744b86b77de5931ac5940cabd8c31416db5085/dataprocessing/renewable_energy_allocation/ego_rea_m5.sql#L208-L218). @Ludee, have u got any objections or hints to be considered?

**Comment by Ludee** [comment]
m5 allocates all RES considered LV and randomly distributes on the 50m lattice inside LA.
You then want to get the LVGD id. That sounds fine, no objections. Did it work out?

**Comment by Ludee** [comment]
I integrated the REA part in **model_draft.ego_supply_res_powerplant**
So the table **model_draft.ego_supply_rea** will not be used anymore.
The **la_id** will be created in the next run. I will leave this issue open until it's done.

**Comment by Ludee** [comment]
Done

**Comment by nesnoj** [comment]
not yet :)
(LVGD != LA)

**Comment by Ludee** [comment]
ok, it's on my list
