### ISSUE TITLE
create clear legend for BPMN

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#53]
there are several conventions that should be normalized and documented.

**Comment by Ludee** [comment]
bpmn/eGo_bpmn_legend_key.graphml

I will keep it open for feedback.

**Comment by lukasol** [comment]
if that was a quest for feedback: i like it!
The only thing I do not get is the different arrows for data. Why is one bold and the other one grey?

**Comment by Ludee** [comment]
No more feedback. Done
