### ISSUE TITLE
rename scripts and snippets

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#55]
We need a convention for the scripts, because the names are confusing and odd.
Suggestions based on the table naming convention:
1. Start with **ego_dp_**
2. then **field** (see BPMN and headers)
3. use the schema if possible
4. then a **goodname** ;)

List of all current scripts:

**setup structure**
- [x] ego_scenario_log_setup.sql,				# setup scenario log table
- ego_dp_structure_scenariolog.sql
- [x] ego_boundaries_vg250_setup.sql,			# setup borders
- ego_dp_structure_boundaries_vg250.sql
- [x] analyse_osm_landuse.sql,            		#  setup OSM landuse
- ego_dp_structure_osm_landuse.sql
**substation**
- [x] get_substations.sql,                 		# setup hvmv substations
- ego_dp_substation_hvmv.sql
- [x] get_substations_ehv.sql,             		# setup ehv substations
- ego_dp_substation_ehv.sql
- [x] otg_id_to_substations.sql,           		# assign osmTGmod-id
- ego_dp_substation_otg.sql
- [x] ego_grid_hvmv_substation.sql,				# hvmv substation voronoi
- ego_dp_substation_hvmv_voi.sql
- [x] Voronoi_ehv.sql,						    # ehc substation voronoi
- ego_dp_substation_ehv_voi.sql
**grid district**
- [x] process_eGo_grid_district.sql,          	# mv griddistrict
- ego_dp_mv_griddistrict.sql
**load area**
- [x] setup_osm_landuse.sql, 					# osm landuse sector
- ego_dp_loadarea_landuse.sql
- [x] process_eGo_osm_loads_industry.sql, 		# osm industry
- ego_dp_loadarea_industry_consumer.sql
- [x] process_eGo_osm_loads.sql,            	# osm loads
- ego_dp_loadarea_loads.sql
- [x] setup_zensus_population_per_ha.sql,   	# setup zensus
- ego_dp_loadarea_census.sql
- [x] process_eGo_loads_melted.sql,        		# melt osm and zensus cluster
- ego_dp_loadarea_loadmelt.sql
- [x] process_eGo_loads_per_grid_district.sql, 	# loadarea per mv-griddistrict
- ego_dp_loadarea_loadcut_griddistrict.sql
- [x] ego_demand_loads_per_mv_voronoi.sql, 	    # loadarea per mv-voronoi
- ego_dp_loadarea_loadcut_voronoi.sql
- [x] process_eGo_consumption.sql,			   	# consumption per loadarea
- ego_dp_loadarea_consumption.sql
- [x] peak_load_per_load_area.py,				# peak loads
- ego_dp_loadarea_peakload.py
- [x] ego_mv_griddistrict_results.sql,        		# results for mv-griddistrict
- ego_dp_loadarea_griddistrict_results.sql
- [x] ego_paper_result.sql,						# results and statistics
- ego_dp_statistic.sql
**powerflow**
- [x] voronoi_weatherpoint.sql,				    # weatherpoint voronoi
- ego_dp_powerflow_voronoi_weatherpoint.sql
- [x] calc_ego_hv_powerflow.sql,			 	# setup for hv powerflow
- ego_dp_powerflow_hv_setup.sql
- [x] osmtgmod_to_pypsa.sql,					# osmTGmod2pyPSA
- ego_dp_powerflow_osmtgmod_to_pypsa.sql
- [x] assignment_generator_bus.sql,       		# generators
- ego_dp_powerflow_assignment_generator.sql
- [x] assignment_load_bus.sql,            		# loads
- ego_dp_powerflow_assignment_load.sql
- [x] renpass_gis_ResultsTOPF.sql,			    # 
- ego_dp_powerflow_timeseries_generator.sql
- [x] demand_per_mv_grid_district.py,			# 
- ego_dp_powerflow_griddistrict_demand.py
- [x] demandseries_TOPF.sql,					# 
- ego_dp_powerflow_timeseries_demand.sql
- [x] LOPF_data.sql,							# 
- ego_dp_powerflow_lopf_data.sql
**low voltage**
- [x] process_eGo_mvlv_substation.sql,			#
- ego_dp_lv_substation.sql
- [x] process_eGo_lv_grid_districts.sql		    # 
- ego_dp_lv_griddistrict.sql

**Comment by Ludee** [comment]
@ulfmueller @IlkaCu 
Can you add the **powerflow** scipts?

**Comment by Ludee** [comment]
When the last scripts are done, I will do:
`git mv file_from file_to` and commit

**Comment by IlkaCu** [comment]
The script voronoi_weatherpoint.sql is redundant and can be removed from the dataprocessing.

**Comment by Ludee** [comment]
All names are in. Thanks @IlkaCu 
I will make a commit in the "dev" branch.

**Comment by Ludee** [comment]
To not mix up the current run and debugging, I will postpone it.

**Comment by IlkaCu** [comment]
I noticed that the weatherpoint voronoi is still used in the dataprocessing. For v0.2 the script _ego_dp_powerflow_voronoi_weatherpoint.sql_ should stay in the dataprocessing. Before the release of v0.3 I will adjust the dataprocessing and remove it.

**Comment by Ludee** [comment]
All snippets renamed. Done

**Comment by Ludee** [comment]
For documentation:

git mv ego_scenario_log_setup.sql ego_dp_structure_scenariolog.sql
git mv ego_boundaries_vg250_setup.sql ego_dp_structure_boundaries_vg250.sql
git mv analyse_osm_landuse.sql ego_dp_structure_osm_landuse.sql

git mv get_substations.sql ego_dp_substation_hvmv.sql
git mv get_substations_ehv.sql ego_dp_substation_ehv.sql
git mv otg_id_to_substations.sql ego_dp_substation_otg.sql
git mv ego_grid_hvmv_substation.sql ego_dp_substation_hvmv_voronoi.sql
git mv Voronoi_ehv.sql ego_dp_substation_ehv_voronoi.sql

git mv process_eGo_grid_district.sql ego_dp_mv_griddistrict.sql

git mv setup_osm_landuse.sql ego_dp_loadarea_landuse.sql
git mv process_eGo_osm_loads_industry.sql ego_dp_loadarea_industry_consumer.sql
git mv process_eGo_osm_loads.sql ego_dp_loadarea_loads.sql
git mv setup_zensus_population_per_ha.sql ego_dp_loadarea_census.sql
git mv process_eGo_loads_melted.sql ego_dp_loadarea_loadmelt.sql
git mv process_eGo_loads_per_grid_district.sql ego_dp_loadarea_loadcut_griddistrict.sql
git mv ego_demand_loads_per_mv_voronoi.sql ego_dp_loadarea_loadcut_voronoi.sql
git mv process_eGo_consumption.sql ego_dp_loadarea_consumption.sql
git mv peak_load_per_load_area.py ego_dp_loadarea_peakload.py
git mv ego_mv_griddistrict_results.sql ego_dp_loadarea_griddistrict_results.sql
git mv ego_paper_result.sql ego_dp_loadarea_statistic.sql

git mv voronoi_weatherpoint.sql ego_dp_powerflow_voronoi_weatherpoint.sql
git mv calc_ego_hv_powerflow.sql ego_dp_powerflow_hv_setup.sql
git mv osmtgmod_to_pypsa.sql ego_dp_powerflow_osmtgmod_to_pypsa.sql

git mv assignment_generator_bus.sql ego_dp_powerflow_assignment_generator.sql
git mv assignment_load_bus.sql ego_dp_powerflow_assignment_load.sql
git mv renpass_gis_ResultsTOPF.sql ego_dp_powerflow_timeseries_generator.sql
git mv demand_per_mv_grid_district.py ego_dp_powerflow_griddistrict_demand.py
git mv demandseries_TOPF.sql ego_dp_powerflow_timeseries_demand.sql
git mv LOPF_data.sql ego_dp_powerflow_lopf_data.sql

git mv process_eGo_mvlv_substation.sql ego_dp_lv_substation.sql
git mv process_eGo_lv_grid_districts.sql ego_dp_lv_griddistrict.sql
