### ISSUE TITLE
Description of code-snippets within eGo_data_processing.py

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#56]
We want to add a short sentence as a description to every snippet within [eGo_data_processing.py.](https://github.com/openego/data_processing/blob/dev/dataprocessing/eGo_data_processing.py) 
Please add or adjust the comment behind the respective sql- or python-snippet and tick the checkbox.  

       

- [x]          'ego_scenario_log_setup.sql'
- [x]          'ego_boundaries_vg250_setup.sql'
- [x]          'analyse_osm_landuse.sql'
- [x]          'get_substations.sql'
- [x]          'get_substations_ehv.sql'
- [x]          'otg_id_to_substations.sql'
- [x]          'ego_grid_hvmv_substation.sql'
- [x]          'Voronoi_ehv.sql'
- [x]          'process_eGo_grid_district.sql'
- [x]          'setup_osm_landuse.sql'
- [x]          'process_eGo_osm_loads_industry.sql'
- [x]          'process_eGo_osm_loads.sql'
- [x]         'setup_zensus_population_per_ha.sql'
- [x]          'process_eGo_loads_melted.sql'
- [x]          'process_eGo_loads_per_grid_district.sql'
- [x]          'ego_demand_loads_per_mv_voronoi.sql'
- [x]          'process_eGo_consumption.sql'
- [x]          'peak_load_per_load_area.py'
- [x]         'ego_mv_griddistrict_results'
- [x]         'ego_paper_result.sql'
- [x]          'voronoi_weatherpoint.sql'
- [x]          'calc_ego_hv_powerflow.sql'
- [x]          'osmtgmod_to_pypsa.sql'
- [x]          'assignment_generator_bus.sql'
- [x]          'assignment_load_bus.sql'
- [x]          'renpass_gis_ResultsTOPF.sql'
- [x]         'demand_per_mv_grid_district.py'
- [x]          'demandseries_TOPF.sql'
- [x]          'LOPF_data.sql'
- [x]         'process_eGo_mvlv_substation.sql'
- [x]         'process_eGo_lv_grid_districts.sql'

**Comment by Ludee** [comment]
finished with commit cac7c1db631e4ed6d24d1c61234a946f91dbfa4c
