### ISSUE TITLE
Setup Power Plant Lists

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#58]
A quick look at the two new scripts open up a few questions and possible improvements:

- [x] Missing header and license
- [x] Table supply.ego_renewable_powerplant does not exist 
- [x] Table supply.ego_conventional_powerplant does not exist 
- [x] supply.ego_ tables are not "Original Data" (OD). They are already processed. They should be named OPSD something?
- [x] missing PKeys in model_draft.ego_supply_conv_ und _re
- [x] Overall missing possibility to rerun the two scripts (drops and add column)
- [x] Some parts are overwriting columns. I would prefer a new column (like voltage_level_new or geom_new)

**Comment by IlkaCu** [comment]
Thanks for listing these open issues - most of them were already on my personal to-do list. 
But I do not see a problem in overwriting columns in the processed power plant lists as we keep the original tables in the supply schema, which enables comparisons.

**Comment by IlkaCu** [comment]
I am aware that the tables supply.ego_renewable_powerplant and supply.ego_conventional_powerplant are no 'original data', that's why we name them 'supply.ego_'- but they are our input data. We don't want to give them an 'opsd-name' as they are no officially released data by the OPSD project. The lists in their current configuration were created by wolfbunke.

**Comment by Ludee** [comment]
> But I do not see a problem in overwriting columns in the processed power plant lists as we keep the original tables in the supply schema, which enables comparisons.

It is not a real problem, but it is somehow not clean. You end up with two different columns that have the same name but contain different information. I would always prefer and suggest the **column_new**.

**Comment by Ludee** [comment]
I have the open issue #57 where I have to adapt the REA to the new RES table.
Since it uses the voltage levels I will include some new columns to the model_draft table.
They will we all called **rea_** something. Hope it makes no problems on your side!

**Comment by IlkaCu** [comment]
ok

**Comment by Ludee** [comment]
> The lists in their current configuration were created by wolfbunke.

So this is a good example for PREPROCESSING. I'm not sure how we handle this in open_eGo? 
It plays an important part when looking at reproducibility. I will make it an open issue for v0.3!

**Comment by Ludee** [comment]
Status?

**Comment by IlkaCu** [comment]
For the release v0.2 I would treat the supply.ego_ tables as input tables and discuss the detailed design of the preprocessing in #59. 
Furthermore from my point of view it is reasonable to overwrite columns in tables of the model_draft as long as we have a table with the 'original' data in the supply schema, which also ensures the reproducibility.

**Comment by Ludee** [comment]
I can live with that.
