### ISSUE TITLE
Place and style of data preprocessing

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#59]
Preprocessing describes everything that is not included in the dataprocessing.
Main tasks are download, unzip, convert, combine, filter, import into oedb and setup (rights, metadata, etc)

Since this plays an important role for the reproducibility of the process we need a concept for it.
The perfect solution would be some sort of script that does that (semi)-automated but for most imports it is not worth the effort. There is also the special case OSM data which should be updated more often.

Feel free to add thoughts, comments and suggestions here.

**Comment by gplssm** [comment]
Once done, take up on #15

**Comment by IlkaCu** [comment]
During the last project meeting we agreed on a new structure for the DP repository including the preprocessing part. See #96
