### ISSUE TITLE
Invalid package name

### ISSUE THREAD

**Issue by MGlauer** [openego/data_processing#6]
Python packages must not contain the character '-'. Your current project can not be imported by other packages. 
Rename your package `graphml-parsing` according to [the style guides](https://www.python.org/dev/peps/pep-0008/#id38)

**Comment by MGlauer** [comment]
You might want to use[`git mv`](https://git-scm.com/docs/git-mv) for renaming the folder in order to avoid re-uploading everything.

http://stackoverflow.com/questions/11183788/in-a-git-repository-how-to-properly-rename-a-directory

**Comment by apoorva-ovgu** [comment]
renamed the package to gmlparser
