### ISSUE TITLE
Deal with source 'chp' in power plant registries 2035/2050

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#61]
The power plant registries of future scenarios include power plants with generation_type='chp', which is not represented in the powerflow sources. A procedure to assign these chp plants to the existing sources needs to be developed.

**Comment by wolfbunke** [comment]
For the beginning we use gas as fuel (generation_typ) and chp as subtype. Next week I like to show you my ideas so that we can decide on this.

**Comment by ulfmueller** [comment]
is that the same question as in #70 ? If yes, it is redundant and can be closed as well.

**Comment by wolfbunke** [comment]
Not really the question was if small chp and EEG gas plants should remain in the "eGo 100" scenario.  By the main scenario definition they shouldn't be included. At the moment there are all decommissioned.

**Comment by wolfbunke** [comment]
I think you can close this ticket.

**Comment by ulfmueller** [comment]
> Not really the question was if small chp and EEG gas plants should remain in the "eGo 100" scenario. By the main scenario definition they shouldn't be included. At the moment there are all decommissioned.

I am pretty sure, that was not the original question posted here by @IlkaCu . If that what you are talking about is really still an issue then create another issue which addresses that problem.
Anyhow if I understand you right, the issue you raised is not really a problem, correct? There will appear no conventional small chp in the eGo 100 scenario, correct?

**Comment by wolfbunke** [comment]
yes, sorry your right! This is done by using gas as generation_type and chp as subtype.
