### ISSUE TITLE
Copyleft information in README

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#62]
Add an template and explanation to the README file. 
Should contain a short summary of the rights and obligations of the license and how we want to be cited.

**Comment by IlkaCu** [comment]
Who works on this?

**Comment by Ludee** [comment]
@EdithaK 
@ulfmueller 
@lukasol 
please confirm my commit and close issue

**Comment by Ludee** [comment]
https://github.com/openego/data_processing/blob/release/v0.2.6/README.md

**Comment by lukasol** [comment]
Just corrected some typos, I'm ok with that now.

**Comment by ulfmueller** [comment]
I am totally fine with it. Sorry for late reply!
@EdithaK please check [this](https://github.com/openego/data_processing/blob/dev/README.md) out and if you also agree close the issue!

**Comment by EdithaK** [comment]
I agree
