### ISSUE TITLE
Demand data from primary sources

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#63]
A colleague is using the demand data for a local project in "Sachsen-Anhalt".
She checked the demand.ego_demand_per_federalstate table and thinks the value "elec_consumption_tertiary_sector" is too high (7182 in table/ ca. 2000 from her source)

@elisagaudchau

**Comment by elisagaudchau** [comment]
i think maybe its the value in Terajoule and not converted in GWh like the others...

**Comment by IlkaCu** [comment]
You are right! Thanks for revealing it. I will fix this immediately and check the other values once again. 
The statistical office of Sachsen-Anhalt gives a value of 1995 million kWh for the tertiary sector.

**Comment by IlkaCu** [comment]
I fixed this issue some time ago.
