### ISSUE TITLE
versioning of important tables

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#67]
The key tables are copied into the OEP-schemas with a version number:

**key**
original table
ORM
versioning table

**Substation**
model_draft.ego_grid_ehv_substation
**ORM???**
grid.ego_dp_ehv_substation

model_draft.ego_grid_hvmv_substation
EgoGridHvmvSubstation
grid.ego_dp_hvmv_substation

model_draft.ego_grid_mvlv_substation
EgoGridMvlvSubstation
grid.ego_dp_mvlv_substation

**Catchment Area**
model_draft.ego_grid_ehv_substation_voronoi
grid.ego_dp_ehv_griddistrict

model_draft.ego_grid_mv_griddistrict
grid.ego_dp_mv_griddistrict

model_draft.ego_grid_lv_griddistrict
grid.ego_dp_lv_griddistrict

**Loadarea**
_Peak loads will be included here_
model_draft.ego_demand_loadarea
EgoDemandLoadarea
demand.ego_dp_loadarea

**Generators**
model_draft.ego_supply_res_powerplant
EgoSupplyResPowerplant
supply.ego_dp_res_powerplant

model_draft.ego_supply_conv_powerplant
EgoConvPowerplant
supply.ego_dp_conv_powerplant

Status can be seen here: model_draft.ego_scenario_overview

Problem for future version: When changing (adding, removing, datatype change) columns, the versioning table has to be changed and old versions get lost or lot of manual work is needed.
The OEP needs to do this task and we need a way to activate the "revisions"!

**Comment by Ludee** [comment]
Attention for LV GD name!

**Comment by Ludee** [comment]
Attention EHV GD has SRID 4326 not 3035 as the rest

**Comment by Ludee** [comment]
versioning completed

**Comment by ulfmueller** [comment]
@Ludee : Is there a standard procedure for the copying? Do you have a sql scripts which inserts the version column to the tables?

**Comment by ulfmueller** [comment]
> Problem for future version: When changing (adding, removing, datatype change) columns, the versioning table has to be changed and old versions get lost or lot of manual work is needed.
The OEP needs to do this task and we need a way to activate the "revisions"!

@MGlauer : How do we 'activate the revisions'?
I particularly have already precedent case where I would to add two versions of datasets to the grid schema. So the older one should be part of the 'revisions'...

**Comment by Ludee** [comment]
There are two new SQL:
1. create the tables as copy of the table with addition column **version**
-> https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_structure_versioning.sql
2. copy data from model_draft to tables and fill version number

This is the SQL way without proper revision. We will try to do this using the new API.

**Comment by Ludee** [comment]
I'm not sure about the versioning of the **powerplant** tables.
The "original" tables are 
supply.ego_conventional_powerplant
supply.ego_renewable_powerplant

The eGoDP tables are 
model_draft.ego_supply_conv_powerplant
model_draft.ego_supply_res_powerplant

The versioning tables can be
**supply.ego_dp_conv_powerplant
supply.ego_dp_res_powerplant**

What do you think? @ulfmueller @IlkaCu @gplssm @nesnoj

**Comment by gplssm** [comment]
We agreed on the proposed names of new tables in versioned schemas

**Comment by Ludee** [comment]
Versioning erfolgreich abgeschlossen!

![grafik](https://cloud.githubusercontent.com/assets/14353512/25008517/43fb44f0-2064-11e7-879e-1587edfa036c.png)

**Comment by Ludee** [comment]
@Ludee Document the versioning and ScenarioLog somewhere!

**Comment by gplssm** [comment]
Is this still an open issue or can we treat this one as resolved?
