### ISSUE TITLE
Fix local imports

### ISSUE THREAD

**Issue by MGlauer** [openego/data_processing#7]
Currently you are importing your modules using `from NodeClass import Node`. This does work only if the python environment is run from the root folder of your project. I.e. it is not possible to import your current project in other projects. 
Imports in a python package should start at the root of the package and mention the full path to the imported module. I guess we can fix the folder `graphml-parsing` as root folder (after renaming it - see #6 ). Thus your imports should look like this: `from graphml{-}parsing.NodeClass import Node`

**Comment by apoorva-ovgu** [comment]
all imports now look like gmlparsing.<class> import <class object>

**Comment by MGlauer** [comment]
It seems this issue was reintroduced in 34dd6833

**Comment by prathamesh-pradhan** [comment]
Fixed gmlparsing as root folder while importing class files in MakeObjects.py
