### ISSUE TITLE
CHP fuel / generation types

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#70]
At the moment we have a random allocation of chp sizes and fuels types which is not really realistic e.g lignite 7KW unite.

ToDo: 

- [ ] make a category list of fuels and size
- [ ] integrate list in allocation script

Script:
https://github.com/openego/data_processing/tree/feature/res-allo-future/calc_geo_powerplants/distribution_chp_plants_nep2035

**Comment by IlkaCu** [comment]
As a temporary solution we defined all small chp plants to have fuel_type='gas'.

**Comment by nesnoj** [comment]
General remark: If you use random functions, make sure you consider reproducibility. E.g. in python using a [predefined seed](https://docs.python.org/3/library/random.html#notes-on-reproducibility).

**Comment by wolfbunke** [comment]
thanks for the hint!

**Comment by wolfbunke** [comment]
The "temporary solution" is at the moment integrated as solution. The assumption  is that all small chp plants are powered by gas and are part in the `model_draft.ego_dp_supply_conv_powerplant` of the `scenario = 'ego-nep2035' `. 
At the moment I like to close this ticket for V3 and if needed reopen it, next week as feature-branch. 
What do you think?

**Comment by lukasol** [comment]
I think it is fine, if all small chp units are gas-fired. Everything else would be not realistic in my point of view. So if you can validate that we're only looking at gas, we can stick to the temporary solution.

**Comment by ulfmueller** [comment]
I also think that the so-called 'temporay solution' is generally ok.
@gplssm This is what @wolfbunke tried to explain.
1. actual implementation: The future small chp (concerning the NEP 2035 scenario) are fired by gas.
2. possibly the allocation of the type of fuel could be more complex and diverse

I - like @lukasol and @wolfbunke - prefer 1.. For me, 2 could be a future feature (maybe nice-to-have but with low priority)

**Comment by wolfbunke** [comment]
This ticket can be closed. This assumption of small chp plants needs to be documented later  in the scenario documentation.
