### ISSUE TITLE
vital bug in model_draft.ego_supply_res_powerplant

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#73]
Bug still there and DP not completed!

https://github.com/openego/data_processing/blob/release/v0.2.6/dataprocessing/sql_snippets/ego_dp_preprocessing_res_powerplant.sql#L14-L17

Still not possible to release and frustration-index is increasing further!

**Comment by IlkaCu** [comment]
What's the exact problem here? 
As this is one of our preprocessing scripts, it doesn't have to run every time we are starting the clean-run. Nevertheless we should consider whether the division between pre-processing and data processing in its current configuration is viable or not - but this discussion should be postponed this to v0.3.

**Comment by Ludee** [comment]
I think all scripts that are included in the .py execution file are part of the DP.
You are right that it doesn't has to be executed every time (every version), but for a release it must be executed! We decided to release so I included all scripts. And this one is not working.
We should not release code that is not working. 
@nesnoj said the transformation of the data type (from varchar to int) was already included somewhere (dev or master?) but is not in the release branch.

Despite the decision to postpone everything to v0.3 this is crucial to finalize v0.2 as it is not working right now!

**Comment by IlkaCu** [comment]
I solved the issue by replacing all percentage signs within the code: 9235b791f9a257f189a19e80d9f3216defc157f1

**Comment by Ludee** [comment]
confirmed bugfix for the script, thank you!

What's about the data type of the column "voltage_level".
I think it's still a varchar. Do we need it as a int? @nesnoj @IlkaCu

**Comment by Ludee** [comment]
`SELECT 	voltage_level
FROM	model_draft.ego_supply_res_powerplant
GROUP BY voltage_level`

"04 (HS/MS)"
""
"03 (HS)"
"5"
"07 (NS)"
"3"
"7"
"02 (HöS/HS)"
"1"
"01 (HöS)"
"6"
"4"
"05 (MS)"
"06 (MS/NS)"

Unable to change due to mixed entries!

'ego_dp_powerflow_assignment_generator.sql',
operator does not exist: character varying >= integer
LINE 273:   AND voltage_level >= 3;

**Comment by IlkaCu** [comment]
I'll take care of it!

**Comment by Ludee** [comment]
my suggestion is to copy the text (04 (HS/MS)) to a column named **voltage_level_var** _varchar_ and take the **voltage_level** _int_ for the update.

**Comment by IlkaCu** [comment]
I adjusted the script according to @Ludee's suggestions

**Comment by Ludee** [comment]
confirmed successful bugfix! Thank you very much @IlkaCu 

One side questions remains. What about RES without voltage info (voltage_level = NULL)?
`SELECT	voltage_level, generation_type, generation_subtype, count(*) AS cnt
FROM 	model_draft.ego_supply_res_powerplant
WHERE voltage_level IS NULL
GROUP BY	voltage_level,generation_type, generation_subtype
ORDER BY voltage_level;`

result:
**generation_type, generation_subtype, count**
"biomass";"biomass";1
"solar";"";2
"solar";"solar_roof_mounted";44683
"wind";"wind_onshore";984

**Comment by IlkaCu** [comment]
I made two adjustments in the script, which should solve this issue. 
It seems that this bug sneaked in during the last adjustment of the comparison operators.

**Comment by Ludee** [comment]
problem with NULL was solved by @IlkaCu 
Restart REA now
