### ISSUE TITLE
Replace ego_dp_loadarea_peakload.py by SQL script

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#76]
Implement calculation of peak loads for Load Areas similar to https://github.com/openego/data_processing/blob/65ef25e1ea1407745477e3a2212cca26c187c94f/dataprocessing/sql_snippets/ego_dp_lv_consumption_peakload.sql

The intended SQL script that calculates peak loads for LAs then updates directly the table _model_draft.ego_demand_loadarea_.

**Comment by Ludee** [comment]
delete table _model_draft.ego_demand_loadarea_peak_load_ after fix

**Comment by Ludee** [comment]
#121
