### ISSUE TITLE
Merge power plant tables

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#77]
Currently, 4 power plant tables in the schema supply exist. These can be reduced to only 2 tables. Therefore, 3 processing steps based on the original OPSD power plant table(s) have to combined.

1. @wolfbunke Does some manipulation of the OPSD table in the preprocessing
2. @IlkaCu Adds voltage levels for each generation unit
3. @Ludee Does allocation of generation units

Edit these scripts such that only two tables result there that contain results of all scripts.

**Comment by IlkaCu** [comment]
This issue is tackled in #114 and #105
