### ISSUE TITLE
Too many arguments on init

### ISSUE THREAD

**Issue by MGlauer** [openego/data_processing#8]
The version on commit ee263473 is not functional. The execution of MakeObjects.py throws:

> Traceback (most recent call last):
>   File "MakeObjects.py", line 164, in <module>
>     makeGraph(None)
>   File "MakeObjects.py", line 39, in makeGraph
>     nodeArray=makeNode(nodes)
>   File "MakeObjects.py", line 61, in makeNode
>     makeGraph(graphs) #mutual recursion
>   File "MakeObjects.py", line 41, in makeGraph
>     nodeArray.extend(makeNode(nodes))
>   File "MakeObjects.py", line 67, in makeNode
>     allStartEv.extend(makeEvent(activities,tmpArray[-1]))
>   File "MakeObjects.py", line 127, in makeEvent
>     eobj = Event(property.attrib["name"], property.attrib["value"],innode)
> TypeError: __init__() takes 3 positional arguments but 4 were given
>

**Comment by apoorva-ovgu** [comment]
updated event class by including a reference to its parent node
