### ISSUE TITLE
Sweden without load and generation

### ISSUE THREAD

**Issue by ulfmueller** [openego/data_processing#80]
in the latest complete dataset there is no load and generation in Sweden. Do you know where that comes from @s3pp ?

**Comment by lukasol** [comment]
I guess that is due to the subnetworks (#78). Sweden is one of them.

**Comment by s3pp** [comment]
Still missing in v0.2.10. The bug is not related to existing subnetworks.

**Comment by lukasol** [comment]
Are the DC connections considered? Note that as an osmTGmod output they are stored in a separate table (otg_ehvhv_branch_data in contrast to otg_ehvhv_dcline_data).

**Comment by ulfmueller** [comment]
the lines should not be relevant for that bug. the generation and demand is allocated to the country nodes no matter of how they are connected by lines or not...

**Comment by s3pp** [comment]
I'm positive this is happening in ego_dp_powerflow_timeseries_generator.sql. There is a reference to all ids < 27 in model_draft.calc_ego_neighbouring_states to get relevant bus_ids. Unfortunately Sweden has 27.

**Comment by lukasol** [comment]
Will be tested in #95
