### ISSUE TITLE
RES allocation fails

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#82]
Currently `model_draft.ego_supply_res_powerplant` has got no geoms as already reported via mail.

**Comment by IlkaCu** [comment]
The assignment of generators to buses relies on the RES allocation as around 3400 RES generators are located outside the area covered by grid districts. 
So we wonder when you are going to work on this bugfix? We need to decide whether to wait for it or continue the dp excluding this power plants.

**Comment by Ludee** [comment]
In the REA script setup the ones without MVGD are assigned with a NN.
https://github.com/openego/data_processing/blob/release/v0.2.6/dataprocessing/renewable_energy_allocation/ego_dp_rea_setup.sql#L122-L215
Of course it should be executed before the PF part.

**Comment by IlkaCu** [comment]
Still I would like to know about your time schedule concerning this bugfix. Just for our own plannings.

**Comment by Ludee** [comment]
Will not fix it this week/weekend. I'm only in office today and our server is down due to relocation.

**Comment by nesnoj** [comment]
I can give it a try - @IlkaCu I gonna give u a buzz later today..

**Comment by Ludee** [comment]
It was the CRS that was not right in the rea_setup, so the subst_id wasn't calculated and all other methods depend on that.
