### ISSUE TITLE
Re-run DP

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#84]
We'd like to re-run parts of DP now after we (hopefully) fixed #81 and #82:

1. `ego_dp_preprocessing_res_powerplant.sql`
2. [REA-Allocation](https://github.com/openego/data_processing/blob/5a286407d077aa48cb51666fd10b3f29dd6ad025/dataprocessing/eGo_data_processing.py#L83-L97)
3. [Powerflow](https://github.com/openego/data_processing/blob/5a286407d077aa48cb51666fd10b3f29dd6ad025/dataprocessing/eGo_data_processing.py#L99-L114)

Please give us a go.

**Comment by IlkaCu** [comment]
GO! :+1: 
If there are any bugs in the PF part, just hand it over to us and we will continue with the PF scripts.

**Comment by nesnoj** [comment]
cheers

**Comment by Ludee** [comment]
Just started PF now. I had to move the order of running and included the REA into eGoDP. 
It is a "proper" section now and dependencies can be handheld much easier.

**Comment by nesnoj** [comment]
@IlkaCu We stopped PF, sorry for the confusion. U can start it now.
