### ISSUE TITLE
use of different CRS in geno assignment nep2035

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#85]
@IlkaCu In e89ca2088bf53856cc21e6af7bc31ae9c3eacc67 you removed the Transform statement, but geoms from CRS 3035 and 4326 are used. This bugfix might be a featurefix? ;)

**Comment by IlkaCu** [comment]
This script still refers to table model_draft.ego_supply_rea_2035, which seems to be wrong, should be model_draft.ego_supply_res_powerplant_2035. 
In that case you are right!

**Comment by IlkaCu** [comment]
I'll fix this in the release branch

**Comment by Ludee** [comment]
I noticed a lot of CRS mixtures in the data processing.
I remember that we said we will do everything in 3035 when processing in egoDP.
Mixing CRS is always a pain and slows down the scripts a lot because ST_Transform has "costs" every time.

I'm not sure why you stick to 4326 in so many tables!?

**Comment by IlkaCu** [comment]
We did not agree on 3035 as the only CRS used in our data model. 
We said we either use 3035 OR 4326!
http://oep.iks.cs.ovgu.de/redmine/projects/open_ego/wiki/Koordinatenreferenzsysteme_(CRS)

**Comment by Ludee** [comment]
You are right, I'm sorry for that.
Still the issue stays the same. Watch out when mixing! This also applies to index comparison (&&).

**Comment by IlkaCu** [comment]
I fixed this! As mentioned in another issue, just hand the dp over to us if there are any bugs in the PF part

**Comment by nesnoj** [comment]
is this one done? If so, plz close it @IlkaCu
