### ISSUE TITLE
YARAB: Yust Another REA Allocation Bug

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#87]
I noticed that there's an issue in REA allocation to LA/LVGD (table `model_draft.ego_supply_res_powerplant`):

1. `subst_id` and `geom` match (`geom` within the corresponding MVGD)
2. `mvlv_subst_id` and `mvlv_subst_id` match (MV-LV station is located within corresponding LA and LVGD)
3. **BUT:** 1. and 2. do not match

(`la_id` of REA is correct)

I'm not sure if this is due to a new bug or due to the partial re-run #84. @Ludee Have you got an idea?

To facilitate further work in DINGO, I'd write a short script to fix the ids for just one MVGD (subst_id=3545) - I guess you don't care @ulfmueller @IlkaCu @lukasol ? (u use the same buggy data which affects your aggregation of genos in script `ego_dp_powerflow_assignment_generator.sql`?)

**Comment by IlkaCu** [comment]
> To facilitate further work in DINGO, I'd write a short script to fix the ids for just one MVGD (subst_id=3545) - I guess you don't care @ulfmueller @IlkaCu @lukasol ? (u use the same buggy data which affects your aggregation of genos in script ego_dp_powerflow_assignment_generator.sql?) 
I think that's all right for us. Our assignments scripts are already done.

**Comment by nesnoj** [comment]
Check results after next dp run and close issue if valid.

**Comment by nesnoj** [comment]
Should be fixed. Re-check in https://github.com/openego/dingo/issues/169

**Comment by nesnoj** [comment]
Exemplarily tested - seems to be ok.
