### ISSUE TITLE
Conventional pp outside Germany

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#88]
Conventional power plants which are located outside of Germany (mainly hydro power plants in Austria and Luxembourg) and connected to voltage_level 3 are not assigned to any substation by the current DP. I will fix this using a NN.

**Comment by nesnoj** [comment]
Are you gonna relocate these PP to the Grid Districts or just the subst_id determined by NN?

**Comment by IlkaCu** [comment]
I wasn't planning to relocate them as their location seems to be correct - they are foreign pp connected to the German grid. 
All of these power plants are assigned to voltage_level 3, so they are not relevant for DINGO. Any objections?

**Comment by nesnoj** [comment]
ok sorry, got this wrong.
