### ISSUE TITLE
Expand DP by scripts for 2050 scenario

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#89]
Scripts for 2050 scenario are developed in branch [feature/future-scenarios](https://github.com/openego/data_processing/tree/feature/future-scenarios/dataprocessing/sql_snippets).

**Comment by ClaraBuettner** [comment]
I've uploaded all expanded scripts into the branch. But I'm not sure with the generator_assignment-script. It needs more than 20 hours to run and still some powerplants don't get a subst_id (about 100 000). I can't see a reason why. 
In addition I couldn't test the sorage-script because there is a table missing in oedb.

**Comment by IlkaCu** [comment]
Did you try to plot the power plants which didn't get a subst_id in QGIS?

**Comment by ClaraBuettner** [comment]
![subst_id](https://cloud.githubusercontent.com/assets/22964326/26315301/fdb316a0-3f10-11e7-9252-e1ef1def7d56.PNG)

The borders seem to be a problem...

**Comment by IlkaCu** [comment]
Its the renewable power plants with voltage_level =>3 which are located outside the area covered by grid districts. We are working on a solution for this problem already. 
Are those plants located in the North sea offshore wind power plants?

**Comment by ClaraBuettner** [comment]
Yes, some are offshore wind powerplants. They have an otg_id but no subst_id.

**Comment by lukasol** [comment]
Just for your info: I will push the assignment of extendable storages for the eGo 100 scenario directly in the  [lopf data script](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_powerflow_lopf_data.sql) of the [dev](https://github.com/openego/data_processing/tree/dev) branch.

**Comment by IlkaCu** [comment]
'ego 100' and 'NEP 2035' scenarios are included in the dev branch
