### ISSUE TITLE
Incorrect handling of DataObjects and Tasks

### ISSUE THREAD

**Issue by MGlauer** [openego/data_processing#9]
The version of 029244c2f produces the following result:

> EVENT_CHARACTERISTIC_START
> Residential
> Retail
> Industrial
> Agricultural
> Polygon
> Open Street Map
> Urban Landuse
> Urban Sectors
> Buffer & Union
> OSM Loads
> Loads OSM
> EVENT_CHARACTERISTIC_INTERMEDIATE_CATCHING

This does not look right: 
- The execution can not start with the comment, as the polygon object must be present in order to enter the activity "Urban Landuse".
    - Same for "Urban Sectors" and "OSM Loads"
- The execution of the comment is part of the execution of "Urban Landuse"
- You must not visit the "Open Street Map" DataObject after "Polygon" as the arrow goes the other way round

You should distinguish between Data Objects and Tasks, as Data Objects are entities that are passed thorough the execution and states are entered and exited.

**Comment by apoorva-ovgu** [comment]
Correct handling in the newest version of the file:
data objects in order, then the task, then its annotation, and then its next elements.
For eg:
EVENT_CHARACTERISTIC_START
Open Street Map
Polygon
Urban Landuse
Residential Retail Industrial Agricultural
Urban Sectors
OSM Loads
Buffer & Union
Loads OSM
EVENT_CHARACTERISTIC_INTERMEDIATE_CATCHING

**Comment by apoorva-ovgu** [comment]
To be uploaded in the morning: distinguish between Data Objects and Tasks

**Comment by apoorva-ovgu** [comment]
uploaded the files
