### ISSUE TITLE
Wind park aggregation of future wind power plants

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#90]
In case of wind power plants the installed capacity of a whole wind park determines the grid level to which the plants are connected. To allocate future wind power plants to a realistic grid level, this needs to be taken into account and a methodology to assign future wind power plants to a realistic grid level need to be developed. 
It might be an option to aggregate future wind power plants to wind parks and assign these to a grid level according to the installed capacity of the whole wind park. 
Alternative methodologies should be considered as well.

**Comment by wolfbunke** [comment]
At the moment @Ludee has implemented wind farms in the [rea script m2](https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/rea/ego_dp_rea_m2.sql) by using the voltage level as an wind farm indicator `voltage_level = 4`. The methodology of the Prox2Now algorithm is extending the future wind power plants by average capacity and voltage level. Therefore this method should work.
But 100% I am not sure if this approach with  `voltage_level = 4` is good or right without having an validation on the results.

I think we should test it if changing is necessity. or?

**Comment by ulfmueller** [comment]
Since the methodology seems relatively applicable and useful we can see this as solved.
For the testing/validation of the methodology I created a new issue #126 , which can be done posterior to the v03.
