### ISSUE TITLE
Integration of rea for future scenarios 2035 and 2050

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#91]
Hi, I plan to use new changes of the method [ (rea)](https://github.com/openego/data_processing/tree/release/v0.2.6/dataprocessing/sql_snippets/rea) for the scenarios NEP 2035 and 2050.

The Idea is following:

- [ ] branch path release/v0.2.6/dataprocessing/sql_snippets/rea
- [ ] create to new folders (../rea/2035 and ../2050) 
- [ ] change the code in order to create to new db tables
- [ ] the table naming is close to the given plus the suffix of the scenario ( _rea, _rea_2035, _rea_2050)
- [ ] solving the problem of keeping the same geo-position of units of all scenarios 

The first result will be three tables:
* model_draft.ego_supply_rea
* model_draft.ego_supply_rea_2035
* model_draft.ego_supply_rea_2050

for the tools dingo and/or eDisGo, eTraGo, ...

By having this status we can discuss further steps. What do you think? At the PT we have also time of a further development of those ideas.

**Comment by nesnoj** [comment]
But this is on schedule for pd release 0.3, isn't it?
Find our recent thoughts on this in [RM](http://oep.iks.cs.ovgu.de/redmine/issues/1870659638?issue_count=189&issue_position=1&next_issue_id=1870659636#note-6).

**Comment by wolfbunke** [comment]
oh, yes thank you!

**Comment by wolfbunke** [comment]
After the talks we change the tables to one. I create a new issue and close this.
