### ISSUE TITLE
Insert new version number in ego_scenario

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#93]
The last bug in our homerun v0.2.10 was caused by the missing version number 'v0.2.10' in table model_draft_ego_scenario. 
The versioned tables have a [foreign key](https://github.com/openego/data_processing/blob/release/v0.2.6/dataprocessing/sql_snippets/ego_dp_structure_versioning.sql#L38-L41) linked to the named table. 
At which point in the DP do we insert the current version number in table model_draft.ego_scenario? 
I just found the script [ego_dp_structure_scenariolog.sql](https://github.com/openego/data_processing/blob/release/v0.2.6/dataprocessing/sql_snippets/ego_dp_structure_scenariolog.sql), but this is not supposed to be executed in every DP run, is it? @Ludee: Any ideas how to solve this?

**Comment by Ludee** [comment]
The script  [ego_dp_structure_scenariolog.sql
](https://github.com/openego/data_processing/blob/release/v0.2.6/dataprocessing/sql_snippets/ego_dp_structure_scenariolog.sql#L26-L39) is designed to be executed in the run. It includes the list of versions. When using "search/replace" it has to be checked to not replace the old versions ;)

Sorry for not documenting this versioning structure properly.

**Comment by ulfmueller** [comment]
Thanks for the clarification and adjustment. 
I will execute the structure_scenariolog.sql and than the versioning script.
