### ISSUE TITLE
Move statements setting metadata to designated script(s)

### ISSUE THREAD

**Issue by s3pp** [openego/data_processing#94]
By now meta data is set in each script separately. Performing an update on the format/bumping up the meta data version is therefore difficult. It has to be searched for these statements. Maybe this task would get easier by putting meta data queries in a designated place/script/scripts. 

Issue is not assigned. Possible task for power week.

**Comment by IlkaCu** [comment]
What do you think about this proposal? 
I'm not sure if it is realistic to implement these changes in v0.3.

**Comment by wolfbunke** [comment]
At the beginning we had /have the folder  **data_processing/documentation/SQL Documentation** for the first meta data per schema. Maybe it is an good idea to store this scripts all there. Additional we could also rename the folder ***SQL Documentation*** into ***metadata*** or similar?

What do you think?

**Comment by Ludee** [comment]
I'm not sure about this procedure.
We have made the rule that "every table" in the oedb has to have metadata.
This is not applicable for all tables in "model_draft", so we said it's only for "public" tables.

At the moment, all metadata are in the script [ego_dp_versioning.sql](ego_dp_versioning.sql).
It's all in one place but it's also quite long and confusing. 

Options are:
1. Leave the metadata in the "versioning" script
2. Outsource the metadata to Documentation folder

a. Have all in one script
b. Have one Script for each table

**Comment by IlkaCu** [comment]
I prefer option 1a, which is the way we are already handling it. 
But currently many of the model_draft-tables do have meta data which are not mandatory according to our 'rule'. How should be deal with this? Should the rather delete all meta data from the model_draft to avoid storing unmaintained data or should we keep the current information knowing it isn't updated?

**Comment by Ludee** [comment]
I agree with you @IlkaCu. -> stay with 1a.
My suggestion that I already tested in eGoDP is to give all model_draft tables a mini-comment with the name and the version number. This way we can see the latest version that created that table. It doesn't need maintenance and version number changes anyway.

What do you think?

```
COMMENT ON TABLE model_draft.ego_political_boundary_hvmv_subst_per_gem IS '{
	"comment": "eGoDP - Temporary table",
	"version": "v0.2.10" }' ;
```
